// Renders every generated contract file from the TypeBox sources in this
// directory. `npm run contract:generate` (server/scripts/generate-contracts.ts)
// writes them; the drift test renders them in memory and compares with the
// committed files. Clients never run this and never fetch a schema at runtime.

import fs from "fs";
import path from "path";
import prettier from "prettier";
import { TSchema } from "@sinclair/typebox";
import { DelphiJobResult } from "./delphiJobResult";
import { Pca2 } from "./pca2";
import { clientReportValidatorSource } from "./clientReportValidator";

export const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");

const SOURCE_NOTE =
  "Generated by `npm run contract:generate` in server/ from server/src/contracts/*.ts. Do not edit; edit the TypeBox source and regenerate.";

// The keywords the generated schemas may use. The client-report validator
// implements exactly these; any other keyword fails generation.
const KEYWORD_ORDER = [
  "$schema",
  "$id",
  "$comment",
  "title",
  "description",
  "type",
  "const",
  "enum",
  "anyOf",
  "properties",
  "required",
  "patternProperties",
  "additionalProperties",
  "items",
  "minItems",
  "maxItems",
  "uniqueItems",
  "minimum",
  "maximum",
  "minLength",
  "pattern",
  "minProperties",
  "maxProperties",
];
const SCHEMA_MAP_KEYWORDS = new Set(["properties", "patternProperties"]);

function canonical(node: any, where: string): any {
  if (Array.isArray(node))
    return node.map((n, i) => canonical(n, `${where}/${i}`));
  if (node === null || typeof node !== "object") return node;
  for (const key of Object.keys(node)) {
    if (!KEYWORD_ORDER.includes(key)) {
      throw new Error(
        `contract schema uses unsupported keyword "${key}" at ${where}`
      );
    }
  }
  const out: any = {};
  for (const key of KEYWORD_ORDER) {
    if (!(key in node)) continue;
    const value = node[key];
    if (SCHEMA_MAP_KEYWORDS.has(key)) {
      out[key] = {};
      for (const name of Object.keys(value)) {
        out[key][name] = canonical(value[name], `${where}/${key}/${name}`);
      }
    } else if (key === "anyOf") {
      out[key] = value.map((n: any, i: number) =>
        canonical(n, `${where}/anyOf/${i}`)
      );
    } else if (
      key === "items" ||
      (key === "additionalProperties" && typeof value === "object")
    ) {
      out[key] = canonical(value, `${where}/${key}`);
    } else {
      out[key] = value;
    }
  }
  return out;
}

export function schemaDocument(schema: TSchema): any {
  // JSON round trip drops TypeBox's symbol-keyed metadata.
  const plain = JSON.parse(JSON.stringify(schema));
  return canonical(
    {
      $schema: "http://json-schema.org/draft-07/schema#",
      $comment: SOURCE_NOTE,
      ...plain,
    },
    "#"
  );
}

// --- TypeScript types from the schemas ------------------------------------

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function jsdoc(text: string | undefined, indent = ""): string {
  if (!text) return "";
  return `${indent}/** ${text.replace(/\*\//g, "*\\/")} */\n`;
}

class TypeEmitter {
  private named = new Map<string, { schema: any; text: string | null }>();
  private order: string[] = [];

  declare(schema: any): string {
    const name = schema.title;
    const existing = this.named.get(name);
    if (existing) {
      if (JSON.stringify(existing.schema) !== JSON.stringify(schema)) {
        throw new Error(`two different schemas are titled "${name}"`);
      }
      return name;
    }
    this.named.set(name, { schema, text: null });
    this.order.push(name);
    const body = this.body(schema);
    const doc = jsdoc(schema.description);
    const text =
      body.startsWith("{") && !body.startsWith("{}")
        ? `${doc}export interface ${name} ${body}`
        : `${doc}export type ${name} = ${body}`;
    this.named.get(name).text = text;
    return name;
  }

  private ref(schema: any): string {
    return schema.title ? this.declare(schema) : this.body(schema);
  }

  private body(schema: any): string {
    if (schema.anyOf) {
      return schema.anyOf.map((s: any) => this.ref(s)).join(" | ");
    }
    if (schema.const !== undefined) return JSON.stringify(schema.const);
    switch (schema.type) {
      case undefined:
        return "unknown";
      case "string":
        return "string";
      case "number":
      case "integer":
        return "number";
      case "boolean":
        return "boolean";
      case "null":
        return "null";
      case "array": {
        const item = this.ref(schema.items);
        return item.includes(" | ") ? `Array<${item}>` : `${item}[]`;
      }
      case "object":
        return this.object(schema);
      default:
        throw new Error(`no TypeScript mapping for type ${schema.type}`);
    }
  }

  private object(schema: any): string {
    const properties = schema.properties || {};
    const required = new Set(schema.required || []);
    const patterns = Object.values(schema.patternProperties || {}) as any[];
    const lines: string[] = [];
    for (const [key, child] of Object.entries<any>(properties)) {
      const name = IDENTIFIER.test(key) ? key : JSON.stringify(key);
      const doc = child.title ? "" : jsdoc(child.description, "  ");
      lines.push(
        `${doc}  ${name}${required.has(key) ? "" : "?"}: ${this.ref(child)}`
      );
    }
    if (patterns.length > 1)
      throw new Error("only one patternProperties entry is supported");
    if (patterns.length === 1) {
      lines.push(`  [key: string]: ${this.ref(patterns[0])}`);
    } else if (schema.additionalProperties !== false) {
      lines.push("  [key: string]: unknown");
    }
    if (lines.length === 0) return "Record<string, never>";
    return `{\n${lines.join("\n")}\n}`;
  }

  render(): string {
    return this.order.map((name) => this.named.get(name).text).join("\n\n");
  }
}

function alphaTypesSource(): string {
  const emitter = new TypeEmitter();
  emitter.declare(schemaDocument(DelphiJobResult));
  emitter.declare(schemaDocument(Pca2));
  return [
    `// ${SOURCE_NOTE}`,
    "// Contracts: delphi-job-result/1 (DelphiJobResult) and pca2/1 (Pca2).",
    "",
    emitter.render(),
    "",
    "export type DelphiJobStatus = DelphiJobResult['status']",
    "",
    "/** A GET /api/v3/math/pca2 response filtered with ?keys=. */",
    "export type Pca2Subset = Partial<Pca2>",
    "",
  ].join("\n");
}

// --- outputs --------------------------------------------------------------

const ALPHA_PRETTIER = {
  printWidth: 100,
  semi: false,
  singleQuote: true,
  trailingComma: "none" as const,
};

function json(value: unknown): string {
  return JSON.stringify(value, null, 2) + "\n";
}

function alphaJson(value: unknown): string {
  return prettier.format(JSON.stringify(value), {
    ...ALPHA_PRETTIER,
    parser: "json",
  });
}

export type ContractOutput = {
  path: string;
  client: string | null;
  content: string;
};

/** Every generated file, keyed by path relative to the repository root. */
export function renderContracts(): ContractOutput[] {
  const delphi = schemaDocument(DelphiJobResult);
  const pca2 = schemaDocument(Pca2);
  const reportHeader = `// ${SOURCE_NOTE}\n// A dependency-free validator for the delphi-job-result/1 and pca2/1 schemas.`;
  return [
    {
      path: "server/src/contracts/delphiJobResult.schema.json",
      client: null,
      content: json(delphi),
    },
    {
      path: "server/src/contracts/pca2.schema.json",
      client: null,
      content: json(pca2),
    },
    {
      path: "client-participation-alpha/src/api/contract/delphiJobResult.schema.json",
      client: "client-participation-alpha",
      content: alphaJson(delphi),
    },
    {
      path: "client-participation-alpha/src/api/contract/pca2.schema.json",
      client: "client-participation-alpha",
      content: alphaJson(pca2),
    },
    {
      path: "client-participation-alpha/src/api/delphi.types.ts",
      client: "client-participation-alpha",
      content: prettier.format(alphaTypesSource(), {
        ...ALPHA_PRETTIER,
        parser: "typescript",
      }),
    },
    {
      path: "client-report/src/contract/delphiJobResult.schema.json",
      client: "client-report",
      content: json(delphi),
    },
    {
      path: "client-report/src/contract/pca2.schema.json",
      client: "client-report",
      content: json(pca2),
    },
    {
      path: "client-report/src/contract/validate.js",
      client: "client-report",
      content: clientReportValidatorSource(reportHeader),
    },
  ];
}

/** Outputs whose client directory is present (a server-only checkout, such as the server image, has none). */
export function presentOutputs(root = REPO_ROOT): ContractOutput[] {
  return renderContracts().filter(
    (o) =>
      o.client === null ||
      fs.existsSync(path.join(root, o.client, "package.json"))
  );
}
