'use strict';
// Pins `contract/negotiation.json` from the ACTUAL middleware the server runs, so
// the Rust negotiator is judged against negotiator@0.6.4 rather than against a
// reading of it. Run with --write to regenerate; run bare to verify the pin.
//
//   NODE_PATH=/Users/colinmegill/polis/server/node_modules \
//     node server-rs/tools/negotiation-parity.cjs [--write]
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),assert=require('node:assert/strict');
const Negotiator=require('negotiator');
// compression/index.js:37-45 — the lists depend on the runtime's brotli support.
const hasBrotliSupport='createBrotliCompress' in zlib;
const SUPPORTED_ENCODING=hasBrotliSupport?['br','gzip','deflate','identity']:['gzip','deflate','identity'];
const PREFERRED_ENCODING=hasBrotliSupport?['br','gzip']:['gzip'];
assert.ok(hasBrotliSupport,'the pinned profile assumes a brotli-capable Node; regenerate the contract if that changes');
const HEADERS=[
 'gzip','GZIP','gzip;q=1','gzip;q=1.0','gzip;q=0','gzip;q=0.0','gzip;q=abc',
 'gzip, deflate','gzip, br','br, gzip','deflate','identity','identity;q=0',
 '*','*;q=0','*, gzip;q=0','gzip;q=0, deflate','gzip;q=0.9, br;q=0.5',
 'br;q=0.5, gzip;q=0.9','gzip ;q=0.5',' gzip , deflate ','gzip;foo=bar;q=0.4',
 'compress','compress, gzip','','   ','x-gzip','gzip;q=0.001',
];
const answer=accept=>{
 const negotiator=new Negotiator({headers:{'accept-encoding':accept}});
 let method=negotiator.encoding(SUPPORTED_ENCODING,PREFERRED_ENCODING);
 // compression/index.js:202-204, with the default enforceEncoding of identity.
 if(!accept&&SUPPORTED_ENCODING.indexOf('identity')!==-1)method='identity';
 // A negotiation that fails or lands on identity means "do not transform".
 return (!method||method==='identity')?'identity':method;
};
const table=HEADERS.map(h=>[h,answer(h)]);
const file=path.resolve(__dirname,'../contract/negotiation.json');
const body=JSON.stringify({
 note:'Generated by tools/negotiation-parity.cjs from the installed middleware; do not hand-edit.',
 compression:require('compression/package.json').version,
 negotiator:require('negotiator/package.json').version,
 node:process.version,
 hasBrotliSupport,
 supported:SUPPORTED_ENCODING,
 preferred:PREFERRED_ENCODING,
 table,
},null,2)+'\n';
if(process.argv.includes('--write')){
 fs.writeFileSync(file,body);
 console.log(`negotiation parity table written: ${table.length} headers`);
}else{
 const pinned=fs.readFileSync(file,'utf8');
 assert.equal(pinned,body,'contract/negotiation.json is stale; rerun with --write and review the diff');
 console.log(`negotiation parity table verified: ${table.length} headers`);
}
