githubRepoOwner: compdemocracy
githubRepoName: polis
githubHost: github.com
githubRemote: origin
githubBranch: edge
requireChecks: true
requireApproval: false
defaultReviewers: []
mergeMethod: squash
mergeQueue: false
prTemplateType: stack
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
createDraftPRs: true
