// Generated by tools/generate-contract.py from hash-pinned ordered wire.
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
fn present<'de, D: serde::Deserializer<'de>, T: Deserialize<'de>>(
    d: D,
) -> Result<Option<T>, D::Error> {
    T::deserialize(d).map(Some)
}
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EmptyObject {}
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GroupdashclustersitemData {
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "center")]
    pub center: Vec<f64>,
    #[serde(rename = "members")]
    pub members: Vec<u64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct BasedashclustersData {
    #[serde(rename = "x")]
    pub x: Vec<f64>,
    #[serde(rename = "y")]
    pub y: Vec<f64>,
    #[serde(rename = "id")]
    pub id: Vec<u64>,
    #[serde(rename = "count")]
    pub count: Vec<u64>,
    #[serde(rename = "members")]
    pub members: Vec<Vec<u64>>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GroupdashvotesentryVotesentryData {
    #[serde(rename = "A")]
    pub a: u64,
    #[serde(rename = "D")]
    pub d: u64,
    #[serde(rename = "S")]
    pub s: u64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GroupdashvotesentryData {
    #[serde(rename = "votes")]
    pub votes: BTreeMap<u32, GroupdashvotesentryVotesentryData>,
    #[serde(rename = "n-members")]
    pub n_dash_members: u64,
    #[serde(rename = "id")]
    pub id: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PcaCommentdashprojectionData {
    Empty(EmptyObject),
    Matrix(Vec<Vec<f64>>),
}
impl Default for PcaCommentdashprojectionData {
    fn default() -> Self {
        Self::Empty(EmptyObject {})
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct PcaData {
    #[serde(rename = "comps")]
    pub comps: Vec<Vec<f64>>,
    #[serde(rename = "center")]
    pub center: Vec<f64>,
    #[serde(rename = "comment-extremity")]
    pub comment_dash_extremity: Vec<f64>,
    #[serde(rename = "comment-projection")]
    pub comment_dash_projection: PcaCommentdashprojectionData,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RepnessentryitemData {
    #[serde(rename = "tid")]
    pub tid: u64,
    #[serde(rename = "p-test")]
    pub p_dash_test: f64,
    #[serde(
        rename = "n-agree",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub n_dash_agree: Option<u64>,
    #[serde(rename = "repness")]
    pub repness: f64,
    #[serde(rename = "n-trials")]
    pub n_dash_trials: u64,
    #[serde(rename = "n-success")]
    pub n_dash_success: u64,
    #[serde(rename = "p-success")]
    pub p_dash_success: f64,
    #[serde(
        rename = "best-agree",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub best_dash_agree: Option<bool>,
    #[serde(rename = "repful-for")]
    pub repful_dash_for: String,
    #[serde(rename = "repness-test")]
    pub repness_dash_test: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ConsensusAgreeitemData {
    #[serde(rename = "tid")]
    pub tid: u64,
    #[serde(rename = "p-test")]
    pub p_dash_test: f64,
    #[serde(rename = "n-trials")]
    pub n_dash_trials: u64,
    #[serde(rename = "n-success")]
    pub n_dash_success: u64,
    #[serde(rename = "p-success")]
    pub p_dash_success: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ConsensusDisagreeitemData {
    #[serde(rename = "tid")]
    pub tid: u64,
    #[serde(rename = "p-test")]
    pub p_dash_test: f64,
    #[serde(rename = "n-trials")]
    pub n_dash_trials: u64,
    #[serde(rename = "n-success")]
    pub n_dash_success: u64,
    #[serde(rename = "p-success")]
    pub p_dash_success: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ConsensusData {
    #[serde(rename = "agree")]
    pub agree: Vec<ConsensusAgreeitemData>,
    #[serde(rename = "disagree")]
    pub disagree: Vec<ConsensusDisagreeitemData>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct VotesdashbaseentryData {
    #[serde(rename = "A")]
    pub a: Vec<u64>,
    #[serde(rename = "D")]
    pub d: Vec<u64>,
    #[serde(rename = "S")]
    pub s: Vec<u64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ModerationData {
    #[serde(rename = "meta_tids")]
    pub meta_tids: Vec<u64>,
    #[serde(rename = "mod_in_tids")]
    pub mod_in_tids: Vec<u64>,
    #[serde(rename = "mod_out_tids")]
    pub mod_out_tids: Vec<u64>,
    #[serde(rename = "mod_out_ptpts")]
    pub mod_out_ptpts: Vec<u64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct VoteStatsCommentStatsentryData {
    #[serde(rename = "n_agree")]
    pub n_agree: u64,
    #[serde(rename = "n_votes")]
    pub n_votes: u64,
    #[serde(rename = "n_disagree")]
    pub n_disagree: u64,
    #[serde(rename = "agree_ratio")]
    pub agree_ratio: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct VoteStatsParticipantStatsentryData {
    #[serde(rename = "n_agree")]
    pub n_agree: u64,
    #[serde(rename = "n_votes")]
    pub n_votes: u64,
    #[serde(rename = "n_disagree")]
    pub n_disagree: u64,
    #[serde(rename = "agree_ratio")]
    pub agree_ratio: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct VoteStatsData {
    #[serde(rename = "n_pass")]
    pub n_pass: u64,
    #[serde(rename = "n_agree")]
    pub n_agree: u64,
    #[serde(rename = "n_votes")]
    pub n_votes: u64,
    #[serde(rename = "n_disagree")]
    pub n_disagree: u64,
    #[serde(rename = "comment_stats")]
    pub comment_stats: BTreeMap<u32, VoteStatsCommentStatsentryData>,
    #[serde(rename = "participant_stats")]
    pub participant_stats: BTreeMap<u32, VoteStatsParticipantStatsentryData>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RepnessFullGroupRepnessentryitemData {
    #[serde(rename = "na")]
    pub na: u64,
    #[serde(rename = "nd")]
    pub nd: u64,
    #[serde(rename = "ns")]
    pub ns: u64,
    #[serde(rename = "pa")]
    pub pa: f64,
    #[serde(rename = "pd")]
    pub pd: f64,
    #[serde(rename = "ra")]
    pub ra: f64,
    #[serde(rename = "rd")]
    pub rd: f64,
    #[serde(rename = "pat")]
    pub pat: f64,
    #[serde(rename = "pdt")]
    pub pdt: f64,
    #[serde(rename = "rat")]
    pub rat: f64,
    #[serde(rename = "rdt")]
    pub rdt: f64,
    #[serde(rename = "repful")]
    pub repful: String,
    #[serde(
        rename = "n_agree",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub n_agree: Option<u64>,
    #[serde(rename = "group_id")]
    pub group_id: u64,
    #[serde(
        rename = "best_agree",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub best_agree: Option<bool>,
    #[serde(rename = "comment_id")]
    pub comment_id: u64,
    #[serde(rename = "agree_metric")]
    pub agree_metric: f64,
    #[serde(rename = "disagree_metric")]
    pub disagree_metric: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RepnessFullCommentRepnessitemData {
    #[serde(rename = "pa")]
    pub pa: f64,
    #[serde(rename = "pd")]
    pub pd: f64,
    #[serde(rename = "gid")]
    pub gid: u64,
    #[serde(rename = "tid")]
    pub tid: u64,
    #[serde(rename = "repness")]
    pub repness: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RepnessFullConsensusCommentsAgreeitemData {
    #[serde(rename = "tid")]
    pub tid: u64,
    #[serde(rename = "p-test")]
    pub p_dash_test: f64,
    #[serde(rename = "n-trials")]
    pub n_dash_trials: u64,
    #[serde(rename = "n-success")]
    pub n_dash_success: u64,
    #[serde(rename = "p-success")]
    pub p_dash_success: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RepnessFullConsensusCommentsDisagreeitemData {
    #[serde(rename = "tid")]
    pub tid: u64,
    #[serde(rename = "p-test")]
    pub p_dash_test: f64,
    #[serde(rename = "n-trials")]
    pub n_dash_trials: u64,
    #[serde(rename = "n-success")]
    pub n_dash_success: u64,
    #[serde(rename = "p-success")]
    pub p_dash_success: f64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RepnessFullConsensusCommentsData {
    #[serde(rename = "agree")]
    pub agree: Vec<RepnessFullConsensusCommentsAgreeitemData>,
    #[serde(rename = "disagree")]
    pub disagree: Vec<RepnessFullConsensusCommentsDisagreeitemData>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct RepnessFullData {
    #[serde(rename = "comment_ids")]
    pub comment_ids: Vec<u64>,
    #[serde(rename = "group_repness")]
    pub group_repness: BTreeMap<u32, Vec<RepnessFullGroupRepnessentryitemData>>,
    #[serde(rename = "comment_repness")]
    pub comment_repness: Vec<RepnessFullCommentRepnessitemData>,
    #[serde(rename = "consensus_comments")]
    pub consensus_comments: RepnessFullConsensusCommentsData,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct GroupClustersitemData {
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "center")]
    pub center: Vec<f64>,
    #[serde(rename = "members")]
    pub members: Vec<u64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct ParticipantInfoentryData {
    #[serde(rename = "group")]
    pub group: u64,
    #[serde(rename = "n_pass")]
    pub n_pass: u64,
    #[serde(rename = "n_agree")]
    pub n_agree: u64,
    #[serde(rename = "n_votes")]
    pub n_votes: u64,
    #[serde(rename = "n_disagree")]
    pub n_disagree: u64,
    #[serde(rename = "group_correlations")]
    pub group_correlations: BTreeMap<u32, f64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default, deny_unknown_fields)]
pub struct MathData {
    #[serde(rename = "group-clusters")]
    pub group_dash_clusters: Vec<GroupdashclustersitemData>,
    #[serde(rename = "base-clusters")]
    pub base_dash_clusters: BasedashclustersData,
    #[serde(rename = "group-votes")]
    pub group_dash_votes: BTreeMap<u32, GroupdashvotesentryData>,
    #[serde(rename = "group-aware-consensus")]
    pub group_dash_aware_dash_consensus: BTreeMap<u32, f64>,
    #[serde(rename = "user-vote-counts")]
    pub user_dash_vote_dash_counts: BTreeMap<u32, u64>,
    #[serde(rename = "in-conv")]
    pub in_dash_conv: Vec<u64>,
    #[serde(rename = "n-cmts")]
    pub n_dash_cmts: u64,
    #[serde(rename = "pca")]
    pub pca: PcaData,
    #[serde(rename = "tids")]
    pub tids: Vec<u64>,
    #[serde(rename = "n")]
    pub n: u64,
    #[serde(rename = "repness")]
    pub repness: BTreeMap<u32, Vec<RepnessentryitemData>>,
    #[serde(rename = "consensus")]
    pub consensus: ConsensusData,
    #[serde(rename = "votes-base")]
    pub votes_dash_base: BTreeMap<u32, VotesdashbaseentryData>,
    // server/src/utils/pca.ts:64 declares `lastModTimestamp?: number | null`; ensureCompletePcaStructure does not repair it, so a stored number reaches the wire.
    #[serde(rename = "lastModTimestamp")]
    pub lastmodtimestamp: Option<u64>,
    #[serde(rename = "lastVoteTimestamp")]
    pub lastvotetimestamp: u64,
    #[serde(rename = "comment-priorities")]
    pub comment_dash_priorities: BTreeMap<u32, f64>,
    #[serde(rename = "math_tick")]
    pub math_tick: u64,
    #[serde(
        rename = "proj",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub proj: Option<BTreeMap<u32, Vec<f64>>>,
    #[serde(
        rename = "mod-in",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub mod_dash_in: Option<Vec<u64>>,
    #[serde(
        rename = "mod-out",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub mod_dash_out: Option<Vec<u64>>,
    #[serde(
        rename = "meta-tids",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub meta_dash_tids: Option<Vec<u64>>,
    #[serde(
        rename = "moderation",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub moderation: Option<ModerationData>,
    #[serde(
        rename = "vote_stats",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub vote_stats: Option<VoteStatsData>,
    #[serde(
        rename = "last_updated",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub last_updated: Option<u64>,
    #[serde(
        rename = "repness_full",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub repness_full: Option<RepnessFullData>,
    #[serde(
        rename = "comment_count",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub comment_count: Option<u64>,
    #[serde(
        rename = "group_clusters",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub group_clusters: Option<Vec<GroupClustersitemData>>,
    // census: emitted by the Python engine output (math/python_conversion) alongside the extras this model already carries; not observed in any stored row, since the writer normalizes before publication. Modelled optional so a stored copy is served, not refused.
    #[serde(
        rename = "conversation_id",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub conversation_id: Option<String>,
    #[serde(
        rename = "participant_info",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub participant_info: Option<BTreeMap<u32, ParticipantInfoentryData>>,
    #[serde(
        rename = "participant_count",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub participant_count: Option<u64>,
    #[serde(
        rename = "comment_priorities",
        skip_serializing_if = "Option::is_none",
        deserialize_with = "present"
    )]
    pub comment_priorities: Option<BTreeMap<u32, f64>>,
    /// Set only when the stored blob omitted `mod-in`; ensureCompletePcaStructure
    /// appends it after every other extra key, so it must serialize last.
    #[serde(
        rename = "mod-in",
        skip_deserializing,
        skip_serializing_if = "Option::is_none"
    )]
    pub mod_dash_in_appended: Option<Vec<u64>>,
    /// Set only when the stored blob omitted `mod-out`; ensureCompletePcaStructure
    /// appends it after every other extra key, so it must serialize last.
    #[serde(
        rename = "mod-out",
        skip_deserializing,
        skip_serializing_if = "Option::is_none"
    )]
    pub mod_dash_out_appended: Option<Vec<u64>>,
    /// Set only when the stored blob omitted `meta-tids`; ensureCompletePcaStructure
    /// appends it after every other extra key, so it must serialize last.
    #[serde(
        rename = "meta-tids",
        skip_deserializing,
        skip_serializing_if = "Option::is_none"
    )]
    pub meta_dash_tids_appended: Option<Vec<u64>>,
}
pub struct Subset<'a> {
    pub data: &'a MathData,
    pub keys: &'a [String],
}
impl Serialize for Subset<'_> {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        let mut map = serializer.serialize_map(None)?;
        let mut seen = std::collections::HashSet::new();
        for key in self.keys {
            if !seen.insert(key) {
                continue;
            }
            match key.as_str() {
                "group-clusters" => map.serialize_entry(key, &self.data.group_dash_clusters)?,
                "base-clusters" => map.serialize_entry(key, &self.data.base_dash_clusters)?,
                "group-votes" => map.serialize_entry(key, &self.data.group_dash_votes)?,
                "group-aware-consensus" => {
                    map.serialize_entry(key, &self.data.group_dash_aware_dash_consensus)?
                }
                "user-vote-counts" => {
                    map.serialize_entry(key, &self.data.user_dash_vote_dash_counts)?
                }
                "in-conv" => map.serialize_entry(key, &self.data.in_dash_conv)?,
                "n-cmts" => map.serialize_entry(key, &self.data.n_dash_cmts)?,
                "pca" => map.serialize_entry(key, &self.data.pca)?,
                "tids" => map.serialize_entry(key, &self.data.tids)?,
                "n" => map.serialize_entry(key, &self.data.n)?,
                "repness" => map.serialize_entry(key, &self.data.repness)?,
                "consensus" => map.serialize_entry(key, &self.data.consensus)?,
                "votes-base" => map.serialize_entry(key, &self.data.votes_dash_base)?,
                "lastModTimestamp" => map.serialize_entry(key, &self.data.lastmodtimestamp)?,
                "lastVoteTimestamp" => map.serialize_entry(key, &self.data.lastvotetimestamp)?,
                "comment-priorities" => {
                    map.serialize_entry(key, &self.data.comment_dash_priorities)?
                }
                "math_tick" => map.serialize_entry(key, &self.data.math_tick)?,
                "proj" => {
                    if let Some(value) = &self.data.proj {
                        map.serialize_entry(key, value)?;
                    }
                }
                "mod-in" => {
                    if let Some(value) = self
                        .data
                        .mod_dash_in
                        .as_ref()
                        .or(self.data.mod_dash_in_appended.as_ref())
                    {
                        map.serialize_entry(key, value)?;
                    }
                }
                "mod-out" => {
                    if let Some(value) = self
                        .data
                        .mod_dash_out
                        .as_ref()
                        .or(self.data.mod_dash_out_appended.as_ref())
                    {
                        map.serialize_entry(key, value)?;
                    }
                }
                "meta-tids" => {
                    if let Some(value) = self
                        .data
                        .meta_dash_tids
                        .as_ref()
                        .or(self.data.meta_dash_tids_appended.as_ref())
                    {
                        map.serialize_entry(key, value)?;
                    }
                }
                "moderation" => {
                    if let Some(value) = &self.data.moderation {
                        map.serialize_entry(key, value)?;
                    }
                }
                "vote_stats" => {
                    if let Some(value) = &self.data.vote_stats {
                        map.serialize_entry(key, value)?;
                    }
                }
                "last_updated" => {
                    if let Some(value) = &self.data.last_updated {
                        map.serialize_entry(key, value)?;
                    }
                }
                "repness_full" => {
                    if let Some(value) = &self.data.repness_full {
                        map.serialize_entry(key, value)?;
                    }
                }
                "comment_count" => {
                    if let Some(value) = &self.data.comment_count {
                        map.serialize_entry(key, value)?;
                    }
                }
                "group_clusters" => {
                    if let Some(value) = &self.data.group_clusters {
                        map.serialize_entry(key, value)?;
                    }
                }
                "conversation_id" => {
                    if let Some(value) = &self.data.conversation_id {
                        map.serialize_entry(key, value)?;
                    }
                }
                "participant_info" => {
                    if let Some(value) = &self.data.participant_info {
                        map.serialize_entry(key, value)?;
                    }
                }
                "participant_count" => {
                    if let Some(value) = &self.data.participant_count {
                        map.serialize_entry(key, value)?;
                    }
                }
                "comment_priorities" => {
                    if let Some(value) = &self.data.comment_priorities {
                        map.serialize_entry(key, value)?;
                    }
                }
                _ => {}
            }
        }
        map.end()
    }
}
