// Generated by `npm run contract:generate` in server/ from server/src/contracts/*.ts. Do not edit; edit the TypeBox source and regenerate.
// Contracts: delphi-job-result/1 (DelphiJobResult) and pca2/1 (Pca2).

/** One Delphi job's outputs as one versioned envelope, discriminated by status. */
export type DelphiJobResult =
  | DelphiJobResultReady
  | DelphiJobResultPending
  | DelphiJobResultRunning
  | DelphiJobResultFailed
  | DelphiJobResultEmpty

/** A completed root. as_of is its completed_at. */
export interface DelphiJobResultReady {
  contract_version: 'delphi-job-result/1'
  /** Public job id: a uuid, or the frozen alias of a legacy import. */
  job_id: string
  run_id: string | null
  /** The conversation's zinvite, never zid. */
  conversation_id: string
  report_id: string | null
  status: 'ready'
  as_of: string
  inputs: JobInputs
  attempt: null
  failure: null
  pinned: boolean
  label: string | null
  outputs: DelphiJobOutputs
  omitted: DelphiFamily[]
}

/** The math snapshot the root captured at start, and the models and prompt versions it ran with. Null leaves mean the root did not record it (legacy imports). */
export interface JobInputs {
  math_tick: number | null
  math_env: string | null
  vote_count: number | null
  comment_count: number | null
  model: JobModels
  prompt_version: JobPromptVersions
}

export interface JobModels {
  topic_names: string
  narrative: string | null
  statement: string | null
  embedding: string | null
}

export interface JobPromptVersions {
  topic_names: string | null
  narrative: string | null
  statement: string | null
}

/** Every family present here is absent from `omitted`, and the reverse. */
export interface DelphiJobOutputs {
  topics_by_layer?: TopicsByLayer
  assignments?: Assignments
  keywords?: Keywords
  umap?: Umap
  visualizations?: Visualization[]
  narratives?: Narratives
  collective_statements?: CollectiveStatement[]
  topic_stats?: TopicStats
  consensus_inputs?: ConsensusInputs
}

/** Keyed by layer id. */
export interface TopicsByLayer {
  [key: string]: Topic[]
}

export interface Topic {
  /** `<job_id>#<layer>#<cluster>`. */
  topic_key: string
  layer_id: number
  cluster_id: number
  topic_name: string
  model_name: string
  comment_count: number
  member_tids: number[]
}

/** tid -> layer id -> cluster id (-1 is unassigned). Topic membership is carried by Topic.member_tids and topic_stats[*].comment_tids. */
export interface Assignments {
  [key: string]: {
    [key: string]: number
  }
}

/** Keyed by topic_key. */
export interface Keywords {
  [key: string]: string[]
}

export interface Umap {
  nodes: UmapNode[]
  edges?: UmapEdge[]
}

/** A comment position. Participant-safe: never carries comment text. */
export interface UmapNode {
  tid: number
  x: number
  y: number
  /** Layer id -> cluster id (-1 is unassigned). */
  layer_cluster: {
    [key: string]: number
  }
  weight?: number
}

export interface UmapEdge {
  source: number
  target: number
  weight: number
  distance?: number
  is_nearest_neighbor?: boolean
}

export interface Visualization {
  /** For example `interactive` or `static_png`. */
  type: string
  layer_id: number
  url: string
  key: string
}

/** Keyed by section. */
export interface Narratives {
  [key: string]: NarrativeSection
}

export type NarrativeSection = NarrativeSectionValid | NarrativeSectionInvalid

export interface NarrativeSectionValid {
  model: string
  created_at: string
  source_topic_job_id: string | null
  /** Length of the stored model output. The raw text is never served. */
  raw_len: number
  validity: 'valid'
  invalid_reason: null
  parsed: NarrativeDocument
}

export interface NarrativeDocument {
  id?: string
  title?: string
  paragraphs: NarrativeParagraph[]
  [key: string]: unknown
}

export interface NarrativeParagraph {
  id?: string
  title?: string
  sentences: NarrativeSentence[]
  [key: string]: unknown
}

export interface NarrativeSentence {
  clauses: NarrativeClause[]
  [key: string]: unknown
}

export interface NarrativeClause {
  text: string
  citations: number[]
  [key: string]: unknown
}

/** A section whose stored output failed parsing or validation. Listed, never dropped and never repaired. */
export interface NarrativeSectionInvalid {
  model: string
  created_at: string
  source_topic_job_id: string | null
  /** Length of the stored model output. The raw text is never served. */
  raw_len: number
  validity: 'invalid'
  invalid_reason: NarrativeInvalidReason
  parsed: null
}

export type NarrativeInvalidReason = 'truncated_json' | 'unparseable_json' | 'schema_mismatch'

/** A stored statement. Reads list stored statements and never generate one. */
export interface CollectiveStatement {
  statement_id: string
  topic_key: string
  topic_name: string
  created_at: string
  model: string
  inputs: CollectiveStatementInputs
  statement: NarrativeDocument
}

/** What the statement was computed against; null where a legacy statement did not record it. */
export interface CollectiveStatementInputs {
  topic_job_id: string
  assignments_job_id: string | null
  math_tick: number | null
}

/** Keyed by topic_key. */
export interface TopicStats {
  [key: string]: TopicStatsEntry
}

/** Computed server-side from the captured math snapshot. */
export interface TopicStatsEntry {
  comment_tids: number[]
  agree: number
  disagree: number
  seen: number
  group_aware_consensus: number | null
  normalized_consensus: number | null
}

/** The subset of the captured math (inputs.math_tick) the topic pages need, so a page never mixes live pca2 with an older topic set. */
export interface ConsensusInputs {
  group_votes: Pca2GroupVotes
  repness: Pca2Repness
}

/** Keyed by group id. */
export interface Pca2GroupVotes {
  [key: string]: Pca2GroupVoteEntry
}

export interface Pca2GroupVoteEntry {
  /** Keyed by tid. */
  votes: {
    [key: string]: Pca2VoteCounts
  }
  'n-members'?: number
  [key: string]: unknown
}

export interface Pca2VoteCounts {
  /** Agree votes. */
  A: number
  /** Disagree votes. */
  D: number
  /** Seen: every vote cast on the comment by the group, agree, disagree and pass. */
  S: number
  [key: string]: unknown
}

/** Representative comments, keyed by group id. */
export interface Pca2Repness {
  [key: string]: Pca2RepnessEntry[]
}

export interface Pca2RepnessEntry {
  tid: number
  'repful-for'?: string
  'p-success'?: number
  [key: string]: unknown
}

export type DelphiFamily =
  | 'topics_by_layer'
  | 'assignments'
  | 'keywords'
  | 'umap'
  | 'visualizations'
  | 'narratives'
  | 'collective_statements'
  | 'topic_stats'
  | 'consensus_inputs'

/** Queued and not started. */
export interface DelphiJobResultPending {
  contract_version: 'delphi-job-result/1'
  /** Public job id: a uuid, or the frozen alias of a legacy import. */
  job_id: string
  run_id: string | null
  /** The conversation's zinvite, never zid. */
  conversation_id: string
  report_id: string | null
  status: 'pending'
  as_of: string | null
  inputs: JobInputs | null
  attempt: null
  failure: null
  pinned: boolean
  label: string | null
  outputs: DelphiJobNoOutputs
  /** Every family: this state carries no outputs. */
  omitted: DelphiFamily[]
}

export type DelphiJobNoOutputs = Record<string, never>

/** Started. as_of is its started_at; attempt is the current attempt. */
export interface DelphiJobResultRunning {
  contract_version: 'delphi-job-result/1'
  /** Public job id: a uuid, or the frozen alias of a legacy import. */
  job_id: string
  run_id: string | null
  /** The conversation's zinvite, never zid. */
  conversation_id: string
  report_id: string | null
  status: 'running'
  as_of: string
  inputs: JobInputs | null
  attempt: number
  failure: null
  pinned: boolean
  label: string | null
  outputs: DelphiJobNoOutputs
  /** Every family: this state carries no outputs. */
  omitted: DelphiFamily[]
}

/** Terminal. as_of is its started_at; attempt is the attempt that ended the run. A rerun is a new root. */
export interface DelphiJobResultFailed {
  contract_version: 'delphi-job-result/1'
  /** Public job id: a uuid, or the frozen alias of a legacy import. */
  job_id: string
  run_id: string | null
  /** The conversation's zinvite, never zid. */
  conversation_id: string
  report_id: string | null
  status: 'failed'
  as_of: string
  inputs: JobInputs | null
  attempt: number
  failure: Failure
  pinned: boolean
  label: string | null
  outputs: DelphiJobNoOutputs
  /** Every family: this state carries no outputs. */
  omitted: DelphiFamily[]
}

/** Never carries log text, an exception message or a stack trace. */
export interface Failure {
  code: FailureCode
  stage: string | null
  attempt: number
  at: string
}

export type FailureCode =
  | 'stage_failed'
  | 'manifest_invalid'
  | 'timeout'
  | 'lease_expired'
  | 'unknown_stage'
  | 'provider_failed'
  | 'cancelled'

/** No root exists for the scope (never run). */
export interface DelphiJobResultEmpty {
  contract_version: 'delphi-job-result/1'
  job_id: null
  run_id: null
  /** The conversation's zinvite, never zid. */
  conversation_id: string
  report_id: string | null
  status: 'empty'
  as_of: null
  inputs: null
  attempt: null
  failure: null
  pinned: false
  label: null
  outputs: DelphiJobNoOutputs
  /** Every family: this state carries no outputs. */
  omitted: DelphiFamily[]
}

/** GET /api/v3/math/pca2 response body (full document). A response filtered with ?keys= carries a subset of these properties with the same types (Pca2Subset). */
export interface Pca2 {
  'group-clusters': Pca2GroupCluster[]
  'base-clusters': Pca2BaseClusters
  'group-votes'?: Pca2GroupVotes
  /** Keyed by tid. */
  'group-aware-consensus'?: {
    [key: string]: number
  }
  /** Keyed by pid. */
  'user-vote-counts': {
    [key: string]: number
  }
  'in-conv': number[]
  'n-cmts': number
  n: number
  pca: Pca2Pca
  tids?: number[]
  'mod-in'?: number[]
  'mod-out'?: number[]
  'meta-tids'?: number[]
  repness: Pca2Repness
  consensus: Pca2Consensus
  'votes-base'?: {
    [key: string]: unknown
  }
  /** Keyed by tid. */
  'comment-priorities'?: {
    [key: string]: number
  }
  lastModTimestamp?: number | null
  lastVoteTimestamp?: number
  /** The math generation, numeric in JSON. The math_env label is carried only in the ETag. */
  math_tick: number
  [key: string]: unknown
}

export interface Pca2GroupCluster {
  id: number
  center: number[]
  /** Base-cluster ids, not participant ids. */
  members: number[]
  [key: string]: unknown
}

export interface Pca2BaseClusters {
  x: number[]
  y: number[]
  id: number[]
  count: number[]
  /** One array of participant ids per base cluster. */
  members: number[][]
  [key: string]: unknown
}

export interface Pca2Pca {
  /** [dimension][participant]. */
  comps: number[][]
  center: number[]
  'comment-extremity': number[]
  'comment-projection': unknown
  [key: string]: unknown
}

export interface Pca2Consensus {
  agree: Pca2ConsensusEntry[]
  disagree: Pca2ConsensusEntry[]
  [key: string]: unknown
}

export interface Pca2ConsensusEntry {
  tid: number
  [key: string]: unknown
}

export type DelphiJobStatus = DelphiJobResult['status']

/** A GET /api/v3/math/pca2 response filtered with ?keys=. */
export type Pca2Subset = Partial<Pca2>
