var s = {};

s.agree = "Agree";
s.disagree = "Disagree";
s.pass = "Pass / Unsure";

s.modSpam = "Spam";
s.modOffTopic = "Off Topic";
s.modImportant = "Important";
s.modSubmitInitialState = "Skip (none of the above), next comment";
s.modSubmit = "Done, next comment";

s.x_wrote = "wrote:";
s.x_tweeted = "tweeted:";
s.group_123 = "Group:";
s.majorityOpinion = "Majority Opinion";
s.majorityOpinionShort = "Majority";
s.info = "Info";
s.addPolisToYourSite = "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>";
s.privacy = "Privacy";
s.TOS = "TOS";
s.writePrompt = "Share your perspective...";
s.anonPerson = "Anonymous";
s.helpWhatAmISeeingTitle = "What am I seeing?";
s.helpWhatAmISeeing = "People who vote similarly are grouped. Click a group to see which viewpoints they share.";
s.helpWhatDoIDoTitle = " What do I do?";
s.helpWhatDoIDo = "Vote on other people's comments by clicking 'agree' or 'disagree'. Write a comment (keep each to a single idea). Invite your friends to the discussion!";
s.writeCommentHelpText = "If your perspective isn't already represented, <strong>write</strong> a comment!</i>";
s.heresHowGroupVoted = "Here's how Group {{GROUP_NUMBER}} voted:";
s.one_person = "{{x}} person";
s.x_people = "{{x}} people";
s.acrossAllPtpts = "Across all participants:";
s.xPtptsSawThisComment = " saw this comment";
s.xOfThoseAgreed = "of those participants agreed";
s.xOfthoseDisagreed = "of those participants disagreed";
s.opinionGroups = "Opinion Groups";
s.pctAgreed = "{{pct}}% Agreed";
s.pctDisagreed = "{{pct}}% Disagreed";
s.pctAgreedOfGroup = "{{pct}}% of Group {{group}} Agreed";
s.pctDisagreedOfGroup = "{{pct}}% of Group {{group}} Disagreed";
s.commentSent = "Comment Sent! Other participants will see your comment and agree or disagree.";
s.connectFacebook = "Connect Facebook";
s.connectTwitter = "Connect Twitter";
s.connectToPostPrompt = "Connect an identity to comment. We will not post to your timeline.";
s.tip = "Tip:";
s.tipCommentsRandom = "Comments are displayed randomly. You are not directly replying to anyone.";
s.tipOneIdea = "Break up long comments that contain multiple ideas. This makes it easier for others to vote on your comment.";
s.tipNoQuestions = "Comments should make statements rather than ask questions. Participants will agree or disagree with the statements you make.";
s.notSentSinceDemo = "(not really, this is a demo)";
s.submitComment = "Submit";
s.tipStarred = "Marked as important.";
s.participantHelpWelcomeText = "Welcome to a new kind of discussion - <span style='font-weight: 700;'>vote</span> on people's opinions and <span style='font-weight: 700;'>contribute</span> your own.";
s.participantHelpGroupsText = "People who vote similarly <span style='font-weight: 700;'>are grouped.</span> Click a group to see which viewpoints they share <a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...more</a>";
s.helpWhatAreGroupsDetail = "<p>You've probably seen 'recommended products' on Amazon, or 'recommended movies' on Netflix. Each of those services uses statistics to group you with people who buy and watch similar things, then show you things that those people bought or watched.</p> <p> When you cast a vote on a comment, you are grouped with people who voted like you did! You can see those groups below. Each is made up of people who have similar opinions. There are fascinating insights to discover in each conversation. Go ahead - click a group to see what brought them together and what makes them unique! </p>";
s.socialConnectPrompt = "Connect to see friends and people you follow in the visualization.";
s.connectFbButton = "Connect with Facebook";
s.connectTwButton = "Connect with Twitter";
s.polis_err_reg_fb_verification_email_sent = "Please check your email for a verification link, then return here to continue.";
s.polis_err_reg_fb_verification_noemail_unverified = "Your Facebook account is unverified. Please verify your email address with Facebook, then return here to continue.";

module.exports = s;
