var s = {};

s.agree = "Son d'accordo";
s.disagree = "Non la penso così";
s.pass = "Passo / Non so";

s.modSpam = "Spam";
s.modOffTopic = "Off Topic / Fuori Tema";
s.modImportant = "Importante";
s.modSubmitInitialState = "Salta / nessuna risposta va bene / passa al prossimo";
s.modSubmit = "Ok, passa al prossimo";

s.x_wrote = "dice:";
s.x_tweeted = "twitta:";
s.group_123 = "Gruppo:";
s.majorityOpinion = "Opinione della maggioranza";
s.majorityOpinionShort = "Maggioranza";
s.info = "Info";
s.addPolisToYourSite = "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>";
s.privacy = "Privacy";
s.TOS = "TOS";
s.writePrompt = "Condividi il tuo punto di vista...";
s.anonPerson = "Anonimo";
s.helpWhatAmISeeingTitle = "Cos'è questo?";
s.helpWhatAmISeeing = "Chi vota in modo simile viene aggregato. Clicca su un gruppo per conoscere quali punti di vista vengono condivisi.";
s.helpWhatDoIDoTitle = " Che faccio?";
s.helpWhatDoIDo = "Vota sui commenti degli altri, cliccando su \"Son d'accordo\" o \"Non la penso così.\". Scrivi un commento (uno per ogni singola idea). Invita i tuoi amici alla discussione!";
s.writeCommentHelpText = "Se il tuo punto di vista manca, <strong>scrivi</strong> un commento!</i>";
s.heresHowGroupVoted = "Ecco come il Gruppo {{GROUP_NUMBER}} ha votato:";
s.one_person = "{{x}} persona";
s.x_people = "{{x}} persone";
s.acrossAllPtpts = "Tra tutti i partecipanti:";
s.xPtptsSawThisComment = " ha/hanno visto questo commento.";
s.xOfThoseAgreed = "di quei partecipanti è d'accordo";
s.xOfthoseDisagreed = "di quei partecipanti non la pensa così";
s.opinionGroups = "Gruppi di opinione";
s.pctAgreed = "{{pct}}% Son d'accordo";
s.pctDisagreed = "{{pct}}% Non la pensano così.";
s.pctAgreedOfGroup = "{{pct}}% del Gruppo {{group}} è d'accordo";
s.pctDisagreedOfGroup = "{{pct}}% del Gruppo {{group}} non la pensa così";
s.commentSent = "Commento Inviato! Altri partecipanti vedranno il tuo commento e saranno d'accordo o meno.";
s.connectFacebook = "Collegati tramite Facebook";
s.connectTwitter = "Collegati tramite Twitter";
s.connectToPostPrompt = "Collega un identità al commento. Non posteremo nulla sul tuo profilo.";
s.tip = "Attenzione:";
s.tipCommentsRandom = "I commenti vengono mostrati casualmente. Non stai rispondendo a nessuno.";
s.tipOneIdea = "Spezza i commenti lunghi quando essi contengono più idee. Questo renderà più facile per gli altri votare sul tuo commento.";
s.tipNoQuestions = "I commenti dovrebbero contenere affermazioni ed evitare di avere la forma di una domanda. I partecipanti saranno d'accordo con i tuoi commenti singoli o la penseranno diversamente.";
s.notSentSinceDemo = "(non davvero, questa è solo una demo)";
s.submitComment = "Invia";
s.tipStarred = "Segnato come importante.";
s.participantHelpWelcomeText = "Benvenuti a un nuovo tipo di discussione - <span style='font-weight: 700;'>votate</span> sulle opinioni della gente o <span style='font-weight: 700;'>controbuite</span> alla vostra.";
s.participantHelpGroupsText = "Chi vota in modo simile <span style='font-weight: 700;'>viene aggregato.</span> Clicca su un gruppo per conoscere quali punti di vista vengono condivisi.<a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...continua</a>";
s.helpWhatAreGroupsDetail = "<p>Avrai visto le raccomandazioni di Amazon sui prodotti o di Netflix sui film o le serie. Ognuno di quei servizi usa le statistiche per unirti a gruppi che comprano o guardano cose simili per poi farti vedere quali cose quelle persone hanno guardato o ascoltato.</p> <p> Quando voti o commenti, vieni messo insieme alle persone che votano no come hai fatto tu! Puoi vedere quei gruppi qui sotto. Ognuno è fatto di persone che hanno opzioni simili. Ci sono alcuni insight molto interessanti da scoprire in ogni conversazione. Vai avanti! Clicca su un gruppo e scopri quali punti di vista sono condivisi e cosa hanno di unico! </p>";
s.socialConnectPrompt = "Collegati per vedere le persone e gli amici che segui nella visualizzazione.";
s.connectFbButton = "Collegati tramite Facebook";
s.connectTwButton = "Collegati tramite Twitter";
s.polis_err_reg_fb_verification_email_sent = "Per favore, controlla la mail e cerca il link di attivazione, poi continua da qui.";
s.polis_err_reg_fb_verification_noemail_unverified = "Il tuo account Facebook non è verificato. Per favore verifica il tuo indirizzo mail di Facebook, poi torna qui per proseguire.";

module.exports = s;
