// Copyright (C) 2012-present, Polis Technology Inc. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

var s = {};

s.agree = "赞成";
s.disagree = "反对";
s.pass = "略过 / 不确定";
s.x_wrote = "表示：";
s.x_tweeted = "推文：";
s.group_123 = "群组：";
s.majorityOpinion = "共同意见";
s.majorityOpinionShort = "共识";
s.info = "说明";
s.addPolisToYourSite = "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>";
s.privacy = "隐私";
s.TOS = "使用条款";
s.writePrompt = "分享您的观点...";
s.anonPerson = "匿名人士";
s.helpWhatAmISeeingTitle = "这是什么？";
s.helpWhatAmISeeing = "立场相近的人，会自动归类到同一个群组。点击群组，就可以看到这些人的共同意见。";
s.helpWhatDoIDoTitle = " 我可以做什么？";
s.helpWhatDoIDo = "针对其他人的意见，按下「赞成」或「反对」。你也可以写下您的观点（每个意见单独一则）。邀请朋友来一起讨论！";
s.writeCommentHelpText = "如果您的观点没有人写过，请务必将它<strong>写下来</strong>！</i>";
s.heresHowGroupVoted = "这是群组 {{GROUP_NUMBER}} 的看法：";
s.one_person = "{{x}} 人";
s.x_people = "{{x}} 人";
s.acrossAllPtpts = "所有参与者：";
s.xPtptsSawThisComment = "位参与者看过这个意见。";
s.xOfThoseAgreed = "位参与者表示赞成。";
s.xOfthoseDisagreed = "位参与者表示反对。";
s.pctAgreed = "{{pct}}% 赞成";
s.pctDisagreed = "{{pct}}% 反对";
s.pctAgreedOfGroup = "群组 {{group}} 里，有 {{pct}}% 的人赞成";
s.pctDisagreedOfGroup = "群组 {{group}} 里，有 {{pct}}% 的人反对";
s.commentSent = "意见已送出！";
s.connectFacebook = "链接 Facebook";
s.connectTwitter = "链接 Twitter";
s.connectToPostPrompt = "发表意见前，请先链接登录帐号。我们不会贴文在您的墙上。";
s.tip = "秘诀：";
s.tipCommentsRandom = "意见会随机显示。您不需要回复别人的看法。";
s.tipOneIdea = "有多个意见请分开来写，一次一个，好让其他人表达赞成或反对。";
s.tipNoQuestions = "请直接陈述您的感受或观点，不要使用问句。";
s.notSentSinceDemo = "（纯属测试，并未送出）";
s.submitComment = "送出";
s.tipStarred = "已经标记为重点。";
s.participantHelpWelcomeText = "欢迎来到一种崭新的讨论方式 - 对众人的意见<span style='font-weight: 700;'>投票</span>，并且<span style='font-weight: 700;'>贡献</span>您的观点。";
s.participantHelpGroupsText = "立场相近的人，会<span style='font-weight: 700;'>自动归类到同一个群组。</span>点击群组，就可以看到这些人的共同意见<a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...</a>";
s.helpWhatAreGroupsDetail = "<p>您可能在其他网站上看过「推荐产品」或「推荐电影」的服务。这些服务使用统计信息，找出和您品味相近的人，然后用那些人的纪录来向您推荐。</p> <p>当您在这里按下「赞成」或「反对」时，您就会自动将您的头像移动到相近的群组里！上方显示的每个群组，都是由立场相近的人组成的。这样的公开讨论，每次都能展现出令人意外的洞见。请点击一个群组 - 看看他们共同的意见、发现某个群组的独特之处！";
s.socialConnectPrompt = "链接帐号，就可以看到您的朋友、追踪的人的立场如何。";
s.connectFbButton = "与 Facebook 链接";
s.connectTwButton = "与 Twitter 链接";

module.exports = s;
