// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

var s = {};

s.agree = "Согласен";
s.disagree = "Не согласен";
s.pass = "Пропустить / Не уверен";

s.importantCheckbox = "Этот комментарий важен";
s.howImportantPrompt = "Насколько важен этот комментарий?";
s.howImportantLow = "Мало";
s.howImportantMedium = "Среднее";
s.howImportantHigh = "Сильно";

s.modSpam = "Спам";
s.modOffTopic = "Отступление от темы";
s.modImportant = "Важный";
s.modSubmitInitialState = "Пропустить (ни один из этих), следующий комментарий";
s.modSubmit = "Закончить, следующий комментарий";

s.x_wrote = "написал:";
s.comments_remaining = "{{num_comments}} осталось";
s.comments_remaining2 = "{{num_comments}} осталось комментариев";
s.group_123 = "Группа:";
s.comment_123 = "Комментарий:";
s.majorityOpinion = "Мнение большинства";
s.majorityOpinionShort = "Большинство";
s.info = "Информация";
s.addPolisToYourSite = "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>";
s.privacy = "Приватность";
s.TOS = "Условия";
s.writePrompt = "Поделитесь своим мнением...";
s.anonPerson = "Анонимный пользователь";
s.helpWhatAmISeeingTitle = "Что это такое?";
s.helpWhatAmISeeing = "Пользователи, которые голосуют похоже, объединены в группы. Нажмите на группу, чтобы посмотреть какие мнения их объединяют.";
s.helpWhatDoIDoTitle = " Что здесь нужно делать?";
s.helpWhatDoIDo = "Голосуйте за комментарии других людей, нажимая 'согласен' или 'не согласен'. Напишите комментарий с одной идеей или мыслью. Пригласите друзей поучаствовать в диалоге!";
s.writeCommentHelpText = "Ваше мнение не представлено в карточках выше? <b>Добавьте новый комментарий</b> в поле ниже.";
s.helpWriteListIntro = "Как написать хороший комментарий?";
s.helpWriteListStandalone = "В комментарии должна быть только одна идея или мысль";
s.helpWriteListRaisNew = "Добавляйте новые мысли, идеи или проблемы";
s.helpWriteListShort = "Пишите кратко: не больше 140 символов";
s.heresHowGroupVoted = "Как группа {{GROUP_NUMBER}} голосовала:";
s.one_person = "{{x}} человек";
s.x_people = "{{x}} людей";
s.acrossAllPtpts = "По всем участников:";
s.xPtptsSawThisComment = " увидели этот комментарии";
s.xOfThoseAgreed = "этих участников согласны";
s.xOfthoseDisagreed = "этих участников не согласны";
s.opinionGroups = "Группы мнений";
s.topComments = "Самые популярные комментарии";
s.divisiveComments = "Разделяющие комментарии";
s.pctAgreed = "{{pct}}% согласны";
s.pctDisagreed = "{{pct}}% не согласны";
s.pctAgreedLong = "{{pct}}% из тех, кто голосовал за комментарий {{comment_id}}, согласны.";
s.pctAgreedOfGroup = "{{pct}}% группы {{group}} согласны";
s.pctDisagreedOfGroup = "{{pct}}% группы {{group}} не согласны";
s.pctDisagreedLong = "{{pct}}% из тех, кто голосовал о комментарии {{comment_id}}, не согласны.";
s.pctAgreedOfGroupLong = "{{pct}}% из группы {{group}}, кто голосовал о комментарии {{comment_id}}, согласны.";
s.pctDisagreedOfGroupLong = "{{pct}}% из тех, кто в группе {{group}} и голосовал за комментарий {{comment_id}}, не согласны.";
s.commentSent = "Комметарий отправлен! Только другие участники увидят ваш комментарий и будут голосовать, соглашаясь или не соглашаясь.";
s.commentSendFailed = "Произошла ошибка при отправке вашего комментария.";
s.commentSendFailedEmpty = "Произошла ошибка при отправке вашего комментария - Комментарий не должен быть пуст.";
s.commentSendFailedTooLong = "Произошла ошибка при отправке вашего комментария - Комментарий слишком длинный.";
s.commentSendFailedDuplicate = "Произошла ошибка при отправке вашего комментария - Одинаковый комментарий уже существует.";
s.commentErrorDuplicate = "Одинаковый комментарий уже существует.";
s.commentErrorConversationClosed = "Это диалог закрыт. Новые комментарии не могут быть добавлены.";
s.commentIsEmpty = "Комментарий пустой";
s.commentIsTooLong = "Комментарий слишком длинный";
s.hereIsNextStatement = "Вы успешно проголосовали. Переходите вверх, чтобы увидеть следующие комментарии.";

s.tip = "Подсказка:";
s.commentWritingTipsHintsHeader = "Советы для написания комментариев";
s.tipCharLimit = "Комментарии ограничены {{char_limit}} символами.";
s.tipCommentsRandom = "Помните, что комментарии отображаются в случайном порядке. Вы не должны отвечать напрямую на комментарии других пользователей.";
s.tipOneIdea = "Разбивайте длинные комментарии с несколькими мыслями. Другим пользователям будет проще голосовать за ваш комментарий.";
s.tipNoQuestions = "Комментарии не должны задавать вопрос. Участники соглашаются или не соглашаются с каждым комментарием.";
s.commentTooLongByChars = "Ограничение длины комментария превышено на {{CHARACTERS_COUNT}} символов.";
s.notSentSinceDemo = "(не отправлено из-за демо-режима)";
s.submitComment = "Отправить";
s.tipStarred = "Отмечен как важный.";
s.participantHelpWelcomeText = "Добро пожаловать в новый способ вести диалог: <em>голосуйте</em> за комментарии других людей.";
s.participantHelpGroupsText = "Люди, которые похоже голосуют <span style='font-weight: 700;'>выделяются в группы.</span> Нажмите на группу, чтобы увидеть какие мнения их объединяют. <a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...больше</a>";
s.participantHelpGroupsNotYetText = "Визуализация появится, когда 7 участников начнут голосовать";
s.helpWhatAreGroupsDetail = "<p>Возможно, вы видели 'рекомендованные товары' на Amazon или 'рекомендованные фильмы' на Netflix. Каждый из этих сервисов использует статистику, чтобы группировать людей в группы с похожими покупками или просмотренными фильмами. Затем сервисы показывают то, что другие люди в этих группах смотрят или покупают.</p> <p> Когда пользователь голосует за разные комментарии, он группируются с другими людьми, которые отвечают похоже! Вы можете увидеть эт группы внизу. Каждая из них состоит из людей с похожими мнениями. В каждом диалоге можно найти интересные детали. Попробуйте поисследовать: нажмите на группу и посмотрите, какие мнения объединяют этих пользователей. </p>";
s.showTranslationButton = "Включить перевод через стороннюю программу";
s.hideTranslationButton = "Выключить перевод";
s.thirdPartyTranslationDisclaimer = "Перевод предоставлен сторонней компанией";

s.notificationsAlreadySubscribed = "Вы подписаны на обновления этого диалога.";
s.notificationsGetNotified = "Получайте уведомления когда появляются новые комментарии:";
s.notificationsEnterEmail = "Введите ваш адрес электронной почты для уведомлений о новых комментариях:";
s.labelEmail = "Email";
s.notificationsSubscribeButton = "Подписаться";
s.notificationsSubscribeErrorAlert = "Ошибка при подписке";
s.noCommentsYet = "Пока нет комментариев.";
s.noCommentsYetSoWrite = "Начните этот диалог добавив комментарий.";
s.noCommentsYetSoInvite = "Начните этот диалог пригласив участников или добавив комментарий.";
s.noCommentsYouVotedOnAll = "Вы проголосовали за все комментарии.";
s.noCommentsTryWritingOne = "Если вам есть что добавить, попробуйте написать свой комментарий.";
s.convIsClosed = "Этот диалог закрыт.";
s.noMoreVotingAllowed = "Голосование закрыто.";

module.exports = s;
