import React from "react";

// Shown under a narrative section or collective statement written by a local
// model (LLM_PROVIDER=ollama on the server and Delphi). Hosted output gets no note.
export const localModelNoteText = (model) =>
  `Generated by a local model (${model || "unknown model"}); quality differs from the hosted model.`;

const LocalModelNote = ({ provider, model, style }) => {
  if (provider !== "ollama") return null;
  return (
    <p
      className="local-model-note"
      data-testid="local-model-note"
      style={{ margin: "4px 0", fontSize: "0.85em", color: "#666", fontStyle: "italic", ...style }}
    >
      {localModelNoteText(model)}
    </p>
  );
};

export default LocalModelNote;
