import React from "react";

// Shown under a narrative section or collective statement written by a local
// model (LLM_PROVIDER=ollama on the server and Delphi). Hosted output gets no note.
export const localModelNoteText = (model) =>
  `Generated by a local model (${model || "unknown model"}); quality differs from the hosted model.`;

// ``as="span"`` renders inside an existing paragraph (a <p> cannot hold a <p>).
const LocalModelNote = ({ provider, model, style, as: Tag = "p" }) => {
  if (provider !== "ollama") return null;
  return (
    <Tag
      className="local-model-note"
      data-testid="local-model-note"
      style={{ display: "block", margin: "4px 0", fontSize: "0.85em", color: "#666", fontStyle: "italic", ...style }}
    >
      {localModelNoteText(model)}
    </Tag>
  );
};

export default LocalModelNote;
