import React from "react";
import { render, screen } from "@testing-library/react";
import "@testing-library/jest-dom";
import LocalModelNote from "./LocalModelNote.jsx";

describe("LocalModelNote", () => {
  it("names the local model and the quality difference", () => {
    render(<LocalModelNote provider="ollama" model="llama3.1:8b" />);
    expect(screen.getByTestId("local-model-note")).toHaveTextContent(
      "Generated by a local model (llama3.1:8b); quality differs from the hosted model."
    );
  });

  it("renders as a span inside an existing paragraph", () => {
    render(
      <p data-testid="outer">
        text <LocalModelNote as="span" provider="ollama" model="llama3.1:8b" />
      </p>
    );
    const note = screen.getByTestId("local-model-note");
    expect(note.tagName).toBe("SPAN");
    expect(screen.getByTestId("outer").querySelector("p")).toBeNull();
  });

  it("renders nothing for hosted or unrecorded provenance", () => {
    const { container, rerender } = render(<LocalModelNote provider="anthropic" model="claude-opus-4-8" />);
    expect(container).toBeEmptyDOMElement();
    rerender(<LocalModelNote model="claude-opus-4-8" />);
    expect(container).toBeEmptyDOMElement();
  });
});
