"""Deterministic seeded generator for the certification bundle's boundary and
stress cases.

P-022 section A, "Boundaries": matrices immediately below/at/above the legacy
10k-participant and 5k-comment thresholds; one/two/too-few eligible voters;
all-pass and constant columns; no eligible comments; repeated timestamps;
out-of-order commits; a dormant zid outside the boot lookback; the previously
measured 33,422 x 783 scale control (declared, and materialised only under
``--include-heavy`` — that benchmark is context, not proof of current memory or
DB cost); and the cache-cap+1 LRU cohort the churn workload cycles.

The generator has its OWN IDENTITY in the manifest — ``generator_id``,
``generator_version``, ``seed``, per-case parameters and a per-case logical
digest — so generated data can never be mistaken for extracted production data.
Nothing here reads a database.

Determinism: every case derives its own ``random.Random`` from the string
``"<generator_id>:<generator_version>:<seed>:<case id>"``, so adding, removing
or reordering cases cannot perturb another case's bytes. Re-running the
generator with the same config reproduces byte-identical files.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Sequence

from polismath.replay import fixture_extract as fx
from polismath.replay import prodclone as pc

GENERATED_SCHEMA_VERSION = "certify-generated/1"

#: Epoch of the synthetic timeline: 2024-01-01T00:00:00Z in integer ms. Fixed so
#: generated bytes do not depend on when the generator ran.
BASE_MS = 1_704_067_200_000
DAY_MS = 86_400_000

_VOTE_VALUES = (-1, 1, 0)  # raw storage signs: agree, disagree, pass


def case_rng(generated: dict[str, Any], case_id: str):
    import random

    return random.Random(
        f"{generated['generator_id']}:{generated['generator_version']}:"
        f"{generated['seed']}:{case_id}"
    )


def case_identity(generated: dict[str, Any], case: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema_version": GENERATED_SCHEMA_VERSION,
        "generator_id": generated["generator_id"],
        "generator_version": generated["generator_version"],
        "seed": generated["seed"],
        "case_id": case["id"],
        "case_parameters": {k: v for k, v in case.items() if k != "notes"},
        "provenance": "SYNTHETIC — generated, never extracted from production. "
                      "Transform ancestry: none; this case has no production parent.",
    }


# ---------------------------------------------------------------------------
# Shape builders — pure, return (vote_rows, comment_rows, participant_rows) in
# the same raw shape fixture_extract.build_events consumes.
# ---------------------------------------------------------------------------


def _comment_rows(n_comments: int, *, mod_out_all: bool, base_ms: int) -> list[dict[str, Any]]:
    return [
        {
            "tid": t,
            "pid": 0,
            "created": base_ms + t,
            "modified": base_ms + t,
            "mod": -1 if mod_out_all else 0,
            "is_meta": False,
        }
        for t in range(n_comments)
    ]


def _participant_rows(n_participants: int, *, base_ms: int) -> list[dict[str, Any]]:
    return [
        {"pid": p, "mod": 0, "created": base_ms + p}
        for p in range(n_participants)
    ]


def build_case_rows(
    case: dict[str, Any], rng,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    """Materialise one generated case. Returns raw ``(votes, comments,
    participants)`` rows shaped exactly like the DB rows the extractor reads."""
    shape = case["shape"]
    n_p = case["participants"]
    n_c = case["comments"]
    vpp = case.get("votes_per_participant", n_c)
    base = BASE_MS - case.get("dormant_age_days", 0) * DAY_MS

    comments = _comment_rows(n_c, mod_out_all=bool(case.get("mod_out_all")), base_ms=base)
    participants = _participant_rows(n_p, base_ms=base)
    votes: list[dict[str, Any]] = []

    if shape == "empty" or n_c == 0 or vpp == 0:
        return votes, comments, participants

    t_cursor = base + 10_000
    for p in range(n_p):
        # Round-robin comment selection with a per-participant offset keeps the
        # sparse shapes deterministic and spread across every column.
        offset = p % n_c
        for k in range(min(vpp, n_c)):
            tid = (offset + k) % n_c
            if shape == "all-pass":
                vote = 0
            elif shape == "constant-column" and tid == 0:
                vote = -1
            else:
                vote = _VOTE_VALUES[rng.randrange(3)]

            if shape == "repeated-timestamps":
                # Every vote of one participant shares a single created value,
                # and the values themselves repeat across participants.
                created = base + 10_000 + (p % 4) * 1000
            elif shape == "out-of-order-commits":
                # Later ordinals carry EARLIER created values for every fourth
                # participant, exercising the strict-timestamp boundary.
                created = t_cursor - (5000 if p % 4 == 3 else 0)
                t_cursor += 1
            else:
                created = t_cursor
                t_cursor += 1

            votes.append({
                "pid": p, "tid": tid, "vote": vote,
                "weight_x_32767": 0, "created": created,
            })

    if shape == "repeated-timestamps":
        # Deliberately plant AMBIGUOUS equal-time opposite votes: the same
        # (pid, tid) cell twice at one created value with opposing signs. The
        # extractor counts these in its census and never invents an order for
        # them; this case is the fixture that ambiguity contract is written
        # against.
        for p in range(0, n_p, 5):
            tid = p % n_c
            created = base + 10_000 + (p % 4) * 1000
            votes.append({"pid": p, "tid": tid, "vote": -1,
                          "weight_x_32767": 0, "created": created})
            votes.append({"pid": p, "tid": tid, "vote": 1,
                          "weight_x_32767": 0, "created": created})

    if shape != "out-of-order-commits":
        # The extractor's frozen order is created ASC then physical order; the
        # generator emits that order directly so generated and extracted streams
        # obey the same ordering contract. out-of-order-commits deliberately
        # does NOT sort — its whole point is a stream whose commit order
        # disagrees with its created order.
        votes.sort(key=lambda r: r["created"])
    return votes, comments, participants


GENERATED_TIE_KEY: dict[str, Any] = {
    "available": True,
    "columns": ["generator_ordinal"],
    "method": "generator-emitted-ordinal",
    "order_by": "generator emission order",
    "guarantee": "stable-tie-key",
    "note": "Generated cases carry their own total order by construction; the "
            "emission order IS the event identity and is reproduced exactly by "
            "re-running the generator with the same seed.",
}


def generate_case_dirs(case: dict[str, Any]) -> list[str]:
    """Fixture slug(s) a case materialises. ``lru-cohort`` expands to
    ``cohort_size`` siblings so the churn workload has cache_cap+1 DISTINCT
    fixtures rather than one conversation silently duplicated."""
    if case["shape"] == "lru-cohort":
        width = len(str(case["cohort_size"] - 1))
        return [f"{case['id']}-{i:0{width}d}" for i in range(case["cohort_size"])]
    return [case["id"]]


def write_case(
    generated: dict[str, Any], case: dict[str, Any],
    payload_root: Path, guard_root: Path,
) -> list[dict[str, Any]]:
    """Write every fixture directory for ``case`` under ``payload_root``.

    Returns one manifest-safe summary per written directory.
    """
    summaries: list[dict[str, Any]] = []
    for member, dir_name in enumerate(generate_case_dirs(case)):
        rng = case_rng(generated, dir_name)
        votes, comments, participants = build_case_rows(case, rng)
        events = fx.build_events(votes, comments)
        meta = fx.stream_meta(
            slug=dir_name, role=f"generated:{case['boundary']}",
            tie_key=GENERATED_TIE_KEY, events=events,
            n_participants=len(participants),
        )
        meta["generated"] = case_identity(generated, case) | {"cohort_member": member}

        target = pc.assert_under_local(payload_root / dir_name, guard_root)
        target.mkdir(parents=True, exist_ok=True)
        fx.write_events_jsonl(target / "events.jsonl", events)
        (target / "events.meta.json").write_text(
            json.dumps(meta, indent=2, sort_keys=True) + "\n")
        fx.write_participants_csv(target / "participants.csv", participants)
        votes_rows, comments_rows, compat = fx.compat_rows_from_events(events)
        meta["compat_csv"] = compat
        (target / "events.meta.json").write_text(
            json.dumps(meta, indent=2, sort_keys=True) + "\n")
        pc.write_votes_csv(target / f"{dir_name}-votes.csv", votes_rows)
        pc.write_comments_csv(target / f"{dir_name}-comments.csv", comments_rows)

        summaries.append({
            "slug": dir_name,
            "role": f"generated:{case['id']}",
            "dir": dir_name,
            "generated": meta["generated"],
            "measured_metrics": case_metrics(events, participants),
            "counts": meta["counts"],
            "logical_digest_sha256": meta["logical_digest_sha256"],
            "ordering_guarantee": meta["ordering"]["guarantee"],
            "equal_time_census": meta["equal_time_census"],
        })
    return summaries


def case_metrics(
    events: Sequence[dict[str, Any]], participants: Sequence[dict[str, Any]],
) -> dict[str, Any]:
    """The same metrics the selector ranks production conversations on, measured
    on a GENERATED case.

    A synthetic substitute is only a substitute if it actually satisfies the
    predicate the missing role was defined by, so the numbers have to be
    measured rather than inferred from the case's name. ``density`` and
    ``matrix_area`` are computed over LATEST DISTINCT (pid, tid) cells, never
    over total revote rows, which would inflate a revote-heavy case into a dense
    one.
    """
    vote_events = [e for e in events if e["kind"] == "vote"]
    comment_events = [e for e in events if e["kind"] == "comment"]
    cells = {(e["pid"], e["tid"]) for e in vote_events}
    n_p = len(participants)
    n_c = len(comment_events)
    area = n_p * n_c
    return {
        "V": len(vote_events),
        "U": len(cells),
        "P": n_p,
        "C": n_c,
        "matrix_area": area,
        "density": (len(cells) / area) if area else None,
        "basis": "density and matrix_area over LATEST DISTINCT (pid, tid) cells",
    }


def write_all(
    generated: dict[str, Any], payload_root: Path, guard_root: Path, *,
    include_heavy: bool = False, only: Sequence[str] | None = None,
    force: Sequence[str] = (),
) -> list[dict[str, Any]]:
    """Write every configured case. ``heavy`` cases are DECLARED in the returned
    summaries but not materialised unless ``include_heavy`` is set.

    ``force`` names case ids that MUST be materialised whatever ``only`` and
    ``include_heavy`` say. It carries the rule that a synthetic role substitute
    is not fulfilled until its generator output actually exists on disk: a role
    standing in for a missing production conversation cannot be satisfied by a
    case that generation was switched off for.
    """
    forced = set(force)
    summaries: list[dict[str, Any]] = []
    for case in generated["cases"]:
        is_forced = case["id"] in forced
        if only is not None and case["id"] not in only and not is_forced:
            continue
        if case.get("heavy") and not include_heavy and not is_forced:
            summaries.append({
                "slug": case["id"],
                "role": f"generated:{case['id']}",
                "dir": None,
                "materialised": False,
                "reason": "heavy scale control declared but not materialised "
                          "(pass --include-heavy)",
                "generated": case_identity(generated, case),
            })
            continue
        summaries.extend(write_case(generated, case, payload_root, guard_root))
    return summaries
