# To build locally, for example:
# docker build -t polis-server:local -f Dockerfile.dev .
# To run locally, for example:
# docker run --rm --name polis-server --env-file .env --network polis-dev_polis_net \
#  -p 5000:5000 polis-server:local

FROM docker.io/node:18-alpine

# Set default NODE_ENV to development unless overridden at build time with --build-arg NODE_ENV=production
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV:-development}

WORKDIR /app

COPY package*.json ./

# Unlike the production Dockerfile, we won't remove these build dependencies.
# So we can use them to re-install and re-build the client assets during development.
RUN apk add --no-cache libpq-dev g++ make python3

COPY . .

EXPOSE 5000

CMD npm run dev
