services:
  e2e-electron:
    image: cypress/included:12.5.1
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js

  e2e-chrome:
    image: cypress/included:12.5.1
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js
    command: --browser chrome

  e2e-firefox:
    image: cypress/included:12.5.1
    volumes:
      - ./cypress:/cypress
      - ./cypress.config.js:/cypress.config.js
    command: --browser firefox
