services:
  e2e-electron:
    image: cypress/included:12.17.3
    environment:
      - CYPRESS_BASE_URL=http://host.docker.internal:80
      - CYPRESS_MAILDEV_URL=http://host.docker.internal:1080
    volumes:
      - .:/e2e
    working_dir: /e2e
    command: npm run test

  e2e-chrome:
    image: cypress/included:12.17.3
    environment:
      - CYPRESS_BASE_URL=http://host.docker.internal:80
      - CYPRESS_MAILDEV_URL=http://host.docker.internal:1080
    volumes:
      - .:/e2e
    working_dir: /e2e
    command: npm run test --browser chrome

  e2e-firefox:
    image: cypress/included:12.17.3
    environment:
      - CYPRESS_BASE_URL=http://host.docker.internal:80
      - CYPRESS_MAILDEV_URL=http://host.docker.internal:1080
    volumes:
      - .:/e2e
    working_dir: /e2e
    command: npm run test --browser firefox
