events {}
http {
 include /etc/nginx/mime.types;
 server {
  listen 8080;
  root /report;
  location /api/ { proxy_pass http://astra-dynamo1424-server:5000; proxy_read_timeout 180s; }
  location / { try_files $uri /index_report.html; }
 }
}
