-- Catalog postconditions only; this file never replays migration DDL.
SELECT NOT EXISTS (SELECT 1 FROM (VALUES
 ('users','uid','integer'),
 ('users','hname','character varying(746)'),
 ('users','created','bigint'),
 ('users','username','character varying(128)'),
 ('users','email','character varying(256)'),
 ('users','is_owner','boolean'),
 ('users','zinvite','character varying(300)'),
 ('users','oinvite','character varying(300)'),
 ('users','tut','smallint'),
 ('users','site_id','character varying(256)'),
 ('users','site_owner','boolean'),
 ('site_domain_whitelist','site_id','character varying(256)'),
 ('site_domain_whitelist','domain_whitelist','character varying(999)'),
 ('site_domain_whitelist','domain_whitelist_override_key','character varying(999)'),
 ('site_domain_whitelist','modified','bigint'),
 ('site_domain_whitelist','created','bigint'),
 ('metrics','uid','integer'),
 ('metrics','type','integer'),
 ('metrics','dur','integer'),
 ('metrics','hashedpc','integer'),
 ('metrics','created','bigint'),
 ('auth_tokens','token','character varying(32)'),
 ('auth_tokens','uid','integer'),
 ('auth_tokens','created','bigint'),
 ('jianiuevyew','uid','integer'),
 ('jianiuevyew','pwhash','character varying(128)'),
 ('apikeysndvweifu','uid','integer'),
 ('apikeysndvweifu','apikey','character varying(32)'),
 ('apikeysndvweifu','created','bigint'),
 ('courses','course_id','integer'),
 ('courses','topic','character varying(1000)'),
 ('courses','description','character varying(1000)'),
 ('courses','owner','integer'),
 ('courses','course_invite','character varying(32)'),
 ('courses','created','bigint'),
 ('conversations','zid','integer'),
 ('conversations','topic','character varying(1000)'),
 ('conversations','description','character varying(50000)'),
 ('conversations','link_url','character varying(9999)'),
 ('conversations','parent_url','character varying(9999)'),
 ('conversations','upvotes','integer'),
 ('conversations','participant_count','integer'),
 ('conversations','is_anon','boolean'),
 ('conversations','is_active','boolean'),
 ('conversations','is_draft','boolean'),
 ('conversations','is_public','boolean'),
 ('conversations','is_data_open','boolean'),
 ('conversations','profanity_filter','boolean'),
 ('conversations','spam_filter','boolean'),
 ('conversations','strict_moderation','boolean'),
 ('conversations','prioritize_seed','boolean'),
 ('conversations','vis_type','integer'),
 ('conversations','write_type','integer'),
 ('conversations','help_type','integer'),
 ('conversations','write_hint_type','integer'),
 ('conversations','style_btn','character varying(500)'),
 ('conversations','socialbtn_type','integer'),
 ('conversations','subscribe_type','integer'),
 ('conversations','branding_type','integer'),
 ('conversations','bgcolor','character varying(20)'),
 ('conversations','help_bgcolor','character varying(20)'),
 ('conversations','help_color','character varying(20)'),
 ('conversations','email_domain','character varying(200)'),
 ('conversations','use_xid_whitelist','boolean'),
 ('conversations','owner','integer'),
 ('conversations','org_id','integer'),
 ('conversations','context','character varying(1000)'),
 ('conversations','course_id','integer'),
 ('conversations','owner_sees_participation_stats','boolean'),
 ('conversations','auth_needed_to_vote','boolean'),
 ('conversations','auth_needed_to_write','boolean'),
 ('conversations','auth_opt_fb','boolean'),
 ('conversations','auth_opt_tw','boolean'),
 ('conversations','auth_opt_allow_3rdparty','boolean'),
 ('conversations','modified','bigint'),
 ('conversations','created','bigint'),
 ('participant_metadata_questions','pmqid','integer'),
 ('participant_metadata_questions','zid','integer'),
 ('participant_metadata_questions','key','character varying(999)'),
 ('participant_metadata_questions','alive','boolean'),
 ('participant_metadata_questions','created','bigint'),
 ('participant_metadata_answers','pmaid','integer'),
 ('participant_metadata_answers','pmqid','integer'),
 ('participant_metadata_answers','zid','integer'),
 ('participant_metadata_answers','value','character varying(999)'),
 ('participant_metadata_answers','alive','boolean'),
 ('participant_metadata_answers','created','bigint'),
 ('contexts','context_id','integer'),
 ('contexts','name','character varying(300)'),
 ('contexts','creator','integer'),
 ('contexts','is_public','boolean'),
 ('contexts','created','bigint'),
 ('inviters','inviter_uid','integer'),
 ('inviters','invited_email','character varying(999)'),
 ('inviters','created','bigint'),
 ('upvotes','uid','integer'),
 ('upvotes','zid','integer'),
 ('oinvites','oinvite','character varying(300)'),
 ('oinvites','note','character varying(999)'),
 ('oinvites','created','bigint'),
 ('einvites','einvite','character varying(100)'),
 ('einvites','email','character varying(999)'),
 ('einvites','created','bigint'),
 ('email_validations','email','character varying(999)'),
 ('email_validations','created','bigint'),
 ('zinvites','zid','integer'),
 ('zinvites','zinvite','character varying(300)'),
 ('zinvites','created','bigint'),
 ('beta','name','character varying(999)'),
 ('beta','email','character varying(200)'),
 ('beta','organization','character varying(200)'),
 ('beta','created','bigint'),
 ('participants','pid','integer'),
 ('participants','uid','integer'),
 ('participants','zid','integer'),
 ('participants','vote_count','integer'),
 ('participants','last_interaction','bigint'),
 ('participants','subscribed','integer'),
 ('participants','last_notified','bigint'),
 ('participants','nsli','smallint'),
 ('participants','mod','integer'),
 ('participants','created','bigint'),
 ('participants_extended','uid','integer'),
 ('participants_extended','zid','integer'),
 ('participants_extended','referrer','character varying(9999)'),
 ('participants_extended','parent_url','character varying(9999)'),
 ('participants_extended','created','bigint'),
 ('participants_extended','modified','bigint'),
 ('participants_extended','subscribe_email','character varying(256)'),
 ('participants_extended','show_translation_activated','boolean'),
 ('participant_locations','zid','integer'),
 ('participant_locations','uid','integer'),
 ('participant_locations','pid','integer'),
 ('participant_locations','lat','double precision'),
 ('participant_locations','lng','double precision'),
 ('participant_locations','created','bigint'),
 ('participant_locations','source','integer'),
 ('xids','uid','integer'),
 ('xids','owner','integer'),
 ('xids','xid','text'),
 ('xids','x_profile_image_url','character varying(3000)'),
 ('xids','x_name','character varying(746)'),
 ('xids','x_email','character varying(256)'),
 ('xids','created','bigint'),
 ('xids','modified','bigint'),
 ('xid_whitelist','owner','integer'),
 ('xid_whitelist','xid','text'),
 ('xid_whitelist','created','bigint'),
 ('notification_tasks','zid','integer'),
 ('notification_tasks','modified','bigint'),
 ('participant_metadata_choices','zid','integer'),
 ('participant_metadata_choices','pid','integer'),
 ('participant_metadata_choices','pmqid','integer'),
 ('participant_metadata_choices','pmaid','integer'),
 ('participant_metadata_choices','alive','boolean'),
 ('participant_metadata_choices','created','bigint'),
 ('twitter_users','uid','integer'),
 ('twitter_users','twitter_user_id','bigint'),
 ('twitter_users','screen_name','character varying(999)'),
 ('twitter_users','name','character varying(9999)'),
 ('twitter_users','followers_count','integer'),
 ('twitter_users','friends_count','integer'),
 ('twitter_users','verified','boolean'),
 ('twitter_users','profile_image_url_https','character varying(9999)'),
 ('twitter_users','location','character varying(9999)'),
 ('twitter_users','response','json'),
 ('twitter_users','modified','bigint'),
 ('twitter_users','created','bigint'),
 ('facebook_users','uid','integer'),
 ('facebook_users','fb_user_id','text'),
 ('facebook_users','fb_name','character varying(9999)'),
 ('facebook_users','fb_link','character varying(9999)'),
 ('facebook_users','fb_public_profile','text'),
 ('facebook_users','fb_login_status','text'),
 ('facebook_users','fb_auth_response','text'),
 ('facebook_users','fb_access_token','text'),
 ('facebook_users','fb_granted_scopes','text'),
 ('facebook_users','fb_location_id','character varying(100)'),
 ('facebook_users','location','character varying(9999)'),
 ('facebook_users','response','text'),
 ('facebook_users','fb_friends_response','text'),
 ('facebook_users','created','bigint'),
 ('facebook_users','modified','bigint'),
 ('social_settings','uid','integer'),
 ('social_settings','polis_pic','character varying(3000)'),
 ('facebook_friends','uid','integer'),
 ('facebook_friends','friend','integer'),
 ('suzinvites','owner','integer'),
 ('suzinvites','zid','integer'),
 ('suzinvites','created','bigint'),
 ('suzinvites','suzinvite','character varying(32)'),
 ('comments','tid','integer'),
 ('comments','zid','integer'),
 ('comments','pid','integer'),
 ('comments','uid','integer'),
 ('comments','created','bigint'),
 ('comments','modified','bigint'),
 ('comments','txt','character varying(1000)'),
 ('comments','velocity','real'),
 ('comments','mod','integer'),
 ('comments','lang','character varying(10)'),
 ('comments','lang_confidence','real'),
 ('comments','active','boolean'),
 ('comments','is_meta','boolean'),
 ('comments','tweet_id','bigint'),
 ('comments','quote_src_url','character varying(1000)'),
 ('comments','anon','boolean'),
 ('comments','is_seed','boolean'),
 ('comment_translations','zid','integer'),
 ('comment_translations','tid','integer'),
 ('comment_translations','src','integer'),
 ('comment_translations','txt','character varying(9999)'),
 ('comment_translations','lang','character varying(10)'),
 ('comment_translations','created','bigint'),
 ('comment_translations','modified','bigint'),
 ('conversation_translations','zid','integer'),
 ('conversation_translations','src','integer'),
 ('conversation_translations','topic','character varying(9999)'),
 ('conversation_translations','description','character varying(9999)'),
 ('conversation_translations','lang','character varying(10)'),
 ('conversation_translations','created','bigint'),
 ('conversation_translations','modified','bigint'),
 ('reports','rid','bigint'),
 ('reports','report_id','character varying(300)'),
 ('reports','zid','integer'),
 ('reports','created','bigint'),
 ('reports','modified','bigint'),
 ('reports','report_name','character varying(999)'),
 ('reports','label_x_neg','character varying(999)'),
 ('reports','label_x_pos','character varying(999)'),
 ('reports','label_y_neg','character varying(999)'),
 ('reports','label_y_pos','character varying(999)'),
 ('reports','label_group_0','character varying(999)'),
 ('reports','label_group_1','character varying(999)'),
 ('reports','label_group_2','character varying(999)'),
 ('reports','label_group_3','character varying(999)'),
 ('reports','label_group_4','character varying(999)'),
 ('reports','label_group_5','character varying(999)'),
 ('reports','label_group_6','character varying(999)'),
 ('reports','label_group_7','character varying(999)'),
 ('reports','label_group_8','character varying(999)'),
 ('reports','label_group_9','character varying(999)'),
 ('report_comment_selections','zid','integer'),
 ('report_comment_selections','rid','bigint'),
 ('report_comment_selections','tid','integer'),
 ('report_comment_selections','selection','smallint'),
 ('report_comment_selections','modified','bigint'),
 ('worker_tasks','created','bigint'),
 ('worker_tasks','math_env','character varying(999)'),
 ('worker_tasks','attempts','smallint'),
 ('worker_tasks','task_data','jsonb'),
 ('worker_tasks','task_type','character varying(99)'),
 ('worker_tasks','task_bucket','bigint'),
 ('worker_tasks','finished_time','bigint'),
 ('math_ticks','zid','integer'),
 ('math_ticks','math_tick','bigint'),
 ('math_ticks','caching_tick','bigint'),
 ('math_ticks','math_env','character varying(999)'),
 ('math_ticks','modified','bigint'),
 ('math_main','zid','integer'),
 ('math_main','math_env','character varying(999)'),
 ('math_main','data','jsonb'),
 ('math_main','last_vote_timestamp','bigint'),
 ('math_main','caching_tick','bigint'),
 ('math_main','math_tick','bigint'),
 ('math_main','modified','bigint'),
 ('math_profile','zid','integer'),
 ('math_profile','math_env','character varying(999)'),
 ('math_profile','data','jsonb'),
 ('math_profile','modified','bigint'),
 ('math_ptptstats','zid','integer'),
 ('math_ptptstats','math_env','character varying(999)'),
 ('math_ptptstats','math_tick','bigint'),
 ('math_ptptstats','data','jsonb'),
 ('math_ptptstats','modified','bigint'),
 ('math_cache','zid','integer'),
 ('math_cache','math_env','character varying(999)'),
 ('math_cache','data','jsonb'),
 ('math_cache','modified','bigint'),
 ('math_bidtopid','zid','integer'),
 ('math_bidtopid','math_env','character varying(999)'),
 ('math_bidtopid','math_tick','bigint'),
 ('math_bidtopid','data','jsonb'),
 ('math_bidtopid','modified','bigint'),
 ('math_exportstatus','zid','integer'),
 ('math_exportstatus','math_env','character varying(999)'),
 ('math_exportstatus','filename','character varying(9999)'),
 ('math_exportstatus','data','jsonb'),
 ('math_exportstatus','modified','bigint'),
 ('math_report_correlationmatrix','rid','bigint'),
 ('math_report_correlationmatrix','math_env','character varying(999)'),
 ('math_report_correlationmatrix','data','jsonb'),
 ('math_report_correlationmatrix','math_tick','bigint'),
 ('math_report_correlationmatrix','modified','bigint'),
 ('votes','zid','integer'),
 ('votes','pid','integer'),
 ('votes','tid','integer'),
 ('votes','vote','smallint'),
 ('votes','weight_x_32767','smallint'),
 ('votes','created','bigint'),
 ('votes_latest_unique','zid','integer'),
 ('votes_latest_unique','pid','integer'),
 ('votes_latest_unique','tid','integer'),
 ('votes_latest_unique','vote','smallint'),
 ('votes_latest_unique','weight_x_32767','smallint'),
 ('votes_latest_unique','modified','bigint'),
 ('crowd_mod','zid','integer'),
 ('crowd_mod','pid','integer'),
 ('crowd_mod','tid','integer'),
 ('crowd_mod','created','bigint'),
 ('crowd_mod','as_important','boolean'),
 ('crowd_mod','as_factual','boolean'),
 ('crowd_mod','as_feeling','boolean'),
 ('crowd_mod','as_notmyfeeling','boolean'),
 ('crowd_mod','as_notgoodidea','boolean'),
 ('crowd_mod','as_notfact','boolean'),
 ('crowd_mod','as_unsure','boolean'),
 ('crowd_mod','as_spam','boolean'),
 ('crowd_mod','as_abusive','boolean'),
 ('crowd_mod','as_offtopic','boolean'),
 ('event_ptpt_no_more_comments','zid','integer'),
 ('event_ptpt_no_more_comments','pid','integer'),
 ('event_ptpt_no_more_comments','votes_placed','smallint'),
 ('event_ptpt_no_more_comments','created','bigint'),
 ('contributer_agreement_signatures','uid','integer'),
 ('contributer_agreement_signatures','name','character varying(746)'),
 ('contributer_agreement_signatures','company_name','character varying(746)'),
 ('contributer_agreement_signatures','github_id','character varying(256)'),
 ('contributer_agreement_signatures','email','character varying(256)'),
 ('contributer_agreement_signatures','agreement_version','integer'),
 ('contributer_agreement_signatures','created','bigint'),
 ('stars','zid','integer'),
 ('stars','pid','integer'),
 ('stars','tid','integer'),
 ('stars','starred','integer'),
 ('stars','created','bigint'),
 ('trashes','zid','integer'),
 ('trashes','pid','integer'),
 ('trashes','tid','integer'),
 ('trashes','trashed','integer'),
 ('trashes','created','bigint'),
 ('permanentcookiezidjoins','zid','integer'),
 ('permanentcookiezidjoins','cookie','character varying(32)'),
 ('permanentcookiezidjoins','created','bigint'),
 ('page_ids','site_id','character varying(100)'),
 ('page_ids','page_id','character varying(100)'),
 ('page_ids','zid','integer'),
 ('demographic_data','uid','integer'),
 ('demographic_data','fb_gender','integer'),
 ('demographic_data','ms_birth_year_estimate_fb','integer'),
 ('demographic_data','ms_gender_estimate_fb','integer'),
 ('demographic_data','fb_timestamp','bigint'),
 ('demographic_data','ms_fb_timestamp','bigint'),
 ('demographic_data','ms_response','character varying(9999)'),
 ('demographic_data','gender_guess','integer'),
 ('demographic_data','birth_year_guess','integer')) AS expected(t,c,typ) WHERE NOT pg_temp.col(t,c,typ))
 AND NOT EXISTS (SELECT 1 FROM unnest(ARRAY['users','site_domain_whitelist','metrics','auth_tokens','jianiuevyew','apikeysndvweifu','courses','conversations','participant_metadata_questions','participant_metadata_answers','contexts','inviters','upvotes','oinvites','einvites','email_validations','zinvites','beta','participants','participants_extended','participant_locations','xids','xid_whitelist','notification_tasks','participant_metadata_choices','twitter_users','facebook_users','social_settings','facebook_friends','suzinvites','comments','comment_translations','conversation_translations','reports','report_comment_selections','worker_tasks','math_ticks','math_main','math_profile','math_ptptstats','math_cache','math_bidtopid','math_exportstatus','math_report_correlationmatrix','votes','votes_latest_unique','crowd_mod','event_ptpt_no_more_comments','contributer_agreement_signatures','stars','trashes','permanentcookiezidjoins','page_ids','demographic_data']) t WHERE to_regclass('public.'||t) IS NULL)
 AND (pg_temp.col('pwreset_tokens','token','character varying(250)') OR pg_temp.col('password_reset_tokens','pwresettoken','character varying(250)'))
 AND to_regprocedure('public.now_as_millis()') IS NOT NULL
 AND pg_temp.con('votes_latest_unique','UNIQUE (zid, pid, tid)');
