-- Catalog postconditions only; this file never replays migration DDL.
SELECT pg_temp.col_exact('conversations','treevite_enabled','boolean',false,'false')
 AND pg_temp.col_exact('treevite_waves','id','bigint',true,'nextval(''treevite_waves_id_seq''::regclass)')
 AND pg_temp.col_exact('treevite_waves','zid','integer',true)
 AND pg_temp.col_exact('treevite_waves','wave','integer',true)
 AND pg_temp.col_exact('treevite_waves','parent_wave','integer',false)
 AND pg_temp.col_exact('treevite_waves','size','integer',false)
 AND pg_temp.col_exact('treevite_waves','invites_per_user','integer',true)
 AND pg_temp.col_exact('treevite_waves','owner_invites','integer',true,'0')
 AND pg_temp.col_exact('treevite_waves','created_at','timestamp with time zone',false,'CURRENT_TIMESTAMP')
 AND pg_temp.col_exact('treevite_waves','updated_at','timestamp with time zone',false,'CURRENT_TIMESTAMP')
 AND pg_temp.con_exact('treevite_waves','PRIMARY KEY (id)')
 AND pg_temp.col_exact('treevite_invites','id','bigint',true,'nextval(''treevite_invites_id_seq''::regclass)')
 AND pg_temp.col_exact('treevite_invites','zid','integer',true)
 AND pg_temp.col_exact('treevite_invites','wave_id','bigint',true)
 AND pg_temp.col_exact('treevite_invites','parent_invite_id','bigint',false)
 AND pg_temp.col_exact('treevite_invites','status','smallint',true,'0')
 AND pg_temp.col_exact('treevite_invites','invite_owner_pid','integer',false)
 AND pg_temp.col_exact('treevite_invites','invite_used_by_pid','integer',false)
 AND pg_temp.col_exact('treevite_invites','invite_used_at','timestamp with time zone',false)
 AND pg_temp.col_exact('treevite_invites','created_at','timestamp with time zone',false,'CURRENT_TIMESTAMP')
 AND pg_temp.col_exact('treevite_invites','updated_at','timestamp with time zone',false,'CURRENT_TIMESTAMP')
 AND pg_temp.con_exact('treevite_invites','PRIMARY KEY (id)')
 AND pg_temp.col_exact('treevite_login_codes','id','bigint',true,'nextval(''treevite_login_codes_id_seq''::regclass)')
 AND pg_temp.col_exact('treevite_login_codes','zid','integer',true)
 AND pg_temp.col_exact('treevite_login_codes','pid','integer',true)
 AND pg_temp.col_exact('treevite_login_codes','login_code_hash','text',true)
 AND pg_temp.col_exact('treevite_login_codes','fp_kid','smallint',true,'1')
 AND pg_temp.col_exact('treevite_login_codes','revoked','boolean',true,'false')
 AND pg_temp.col_exact('treevite_login_codes','expires_at','timestamp with time zone',false)
 AND pg_temp.col_exact('treevite_login_codes','last_used_at','timestamp with time zone',false)
 AND pg_temp.col_exact('treevite_login_codes','created_at','timestamp with time zone',false,'CURRENT_TIMESTAMP')
 AND pg_temp.col_exact('treevite_login_codes','updated_at','timestamp with time zone',false,'CURRENT_TIMESTAMP')
 AND pg_temp.con_exact('treevite_login_codes','PRIMARY KEY (id)')
 AND pg_temp.con_exact('treevite_waves','UNIQUE (zid, wave)')
 AND pg_temp.con_exact('treevite_waves','FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND pg_temp.con_exact('treevite_invites','UNIQUE (zid, invite_code)')
 AND pg_temp.con_exact('treevite_invites','FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND pg_temp.con_exact('treevite_invites','FOREIGN KEY (wave_id) REFERENCES treevite_waves(id) ON DELETE CASCADE')
 AND pg_temp.con_exact('treevite_invites','FOREIGN KEY (parent_invite_id) REFERENCES treevite_invites(id) ON DELETE SET NULL')
 AND pg_temp.con_exact('treevite_invites','FOREIGN KEY (zid, invite_owner_pid) REFERENCES participants(zid, pid)')
 AND pg_temp.con_exact('treevite_invites','FOREIGN KEY (zid, invite_used_by_pid) REFERENCES participants(zid, pid)')
 AND pg_temp.con_exact('treevite_login_codes','FOREIGN KEY (zid, pid) REFERENCES participants(zid, pid) ON DELETE CASCADE')
 AND pg_temp.con_exact('treevite_login_codes','UNIQUE (zid, pid)')
 AND pg_temp.con_exact('treevite_login_codes','UNIQUE (zid, login_code_fingerprint)')
 AND pg_temp.con_exact('treevite_login_codes','UNIQUE (zid, login_code_lookup)')
 AND pg_temp.idx('idx_treevite_waves_zid','CREATE INDEX idx_treevite_waves_zid ON public.treevite_waves USING btree (zid)')
 AND pg_temp.idx('idx_treevite_waves_wave','CREATE INDEX idx_treevite_waves_wave ON public.treevite_waves USING btree (wave)')
 AND pg_temp.idx('idx_treevite_waves_parent','CREATE INDEX idx_treevite_waves_parent ON public.treevite_waves USING btree (zid, parent_wave)')
 AND pg_temp.idx('idx_treevite_invites_zid','CREATE INDEX idx_treevite_invites_zid ON public.treevite_invites USING btree (zid)')
 AND pg_temp.idx('idx_treevite_invites_zid_status','CREATE INDEX idx_treevite_invites_zid_status ON public.treevite_invites USING btree (zid, status)')
 AND pg_temp.idx('idx_treevite_invites_wave_id','CREATE INDEX idx_treevite_invites_wave_id ON public.treevite_invites USING btree (wave_id)')
 AND pg_temp.idx('idx_treevite_invites_parent','CREATE INDEX idx_treevite_invites_parent ON public.treevite_invites USING btree (parent_invite_id)')
 AND pg_temp.idx('idx_treevite_invites_owner_pid','CREATE INDEX idx_treevite_invites_owner_pid ON public.treevite_invites USING btree (invite_owner_pid)')
 AND pg_temp.idx('idx_treevite_invites_used_by_pid','CREATE INDEX idx_treevite_invites_used_by_pid ON public.treevite_invites USING btree (invite_used_by_pid)')
 AND pg_temp.idx('idx_treevite_invites_code','CREATE INDEX idx_treevite_invites_code ON public.treevite_invites USING btree (invite_code)')
 AND pg_temp.idx('idx_treevite_login_codes_zid','CREATE INDEX idx_treevite_login_codes_zid ON public.treevite_login_codes USING btree (zid)')
 AND pg_temp.idx('idx_treevite_login_codes_pid','CREATE INDEX idx_treevite_login_codes_pid ON public.treevite_login_codes USING btree (pid)')
 AND pg_temp.idx('idx_treevite_login_codes_fp','CREATE INDEX idx_treevite_login_codes_fp ON public.treevite_login_codes USING btree (login_code_fingerprint)')
 AND pg_temp.idx('idx_treevite_login_codes_lookup','CREATE INDEX idx_treevite_login_codes_lookup ON public.treevite_login_codes USING btree (zid, login_code_lookup)')
 AND pg_temp.col_exact('treevite_invites','invite_code','character varying(64)',true)
 AND pg_temp.col_exact('treevite_login_codes','login_code_fingerprint','character varying(128)',true)
 AND pg_temp.col_exact('treevite_login_codes','login_code_lookup','character varying(128)',false)
 AND pg_temp.con_exact('treevite_waves','CHECK (((invites_per_user > 0) OR (owner_invites > 0)))')
 AND pg_temp.con_exact('treevite_waves','CHECK (((parent_wave IS NULL) OR (parent_wave >= 0)))')
 AND pg_temp.con_exact('treevite_waves','CHECK (((size IS NULL) OR (size >= 0)))')
 AND pg_temp.con_exact('treevite_waves','CHECK ((invites_per_user >= 0))')
 AND pg_temp.con_exact('treevite_waves','CHECK ((owner_invites >= 0))')
 AND pg_temp.con_exact('treevite_waves','CHECK ((wave >= 1))')
 AND pg_temp.con_exact('treevite_invites','CHECK ((status = ANY (ARRAY[0, 1, 2, 3])))');
