-- Catalog postconditions only; this file never replays migration DDL.
SELECT pg_temp.col('conversations','xid_required','boolean',true,'false')
 AND pg_temp.col('xid_whitelist','zid','integer')
 AND pg_temp.col('xids','zid','integer')
 AND pg_temp.col('xids','pid','integer')
 AND pg_temp.con('xid_whitelist','FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND pg_temp.con('xids','FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND pg_temp.con('xids','FOREIGN KEY (zid, pid) REFERENCES participants(zid, pid) ON DELETE SET NULL')
 AND pg_temp.idx('idx_xid_whitelist_zid','CREATE INDEX idx_xid_whitelist_zid ON public.xid_whitelist USING btree (zid)')
 AND pg_temp.idx('idx_xid_whitelist_xid','CREATE INDEX idx_xid_whitelist_xid ON public.xid_whitelist USING btree (xid)')
 AND pg_temp.idx('idx_xids_zid','CREATE INDEX idx_xids_zid ON public.xids USING btree (zid)')
 AND pg_temp.idx('idx_xids_xid','CREATE INDEX idx_xids_xid ON public.xids USING btree (xid)')
 AND pg_temp.idx('idx_xids_pid','CREATE INDEX idx_xids_pid ON public.xids USING btree (pid)')
 AND pg_temp.idx('idx_xids_zid_xid','CREATE INDEX idx_xids_zid_xid ON public.xids USING btree (zid, xid)')
 AND pg_temp.idx('idx_xids_uid_zid','CREATE INDEX idx_xids_uid_zid ON public.xids USING btree (uid, zid)');
