-- GENERATED by server/bin/build-migration-report.py; do not edit.
-- First deployment only: no existing ledger or queue. Other states refuse.
-- This is a catalog forecast, not DDL success or deployment-health proof.
-- sha256 8fa1066d9fc29c1df528b300199c619a2f9edecf1432926ad6a8146ebc650593 adoption/helpers.sql
-- sha256 0bbe8c3ac74a484580576f45d40dcd3ddae205bb0c63377ff8f053cecf979e0d release.txt
-- sha256 8a8b24fa47a25c613a8329aa79f413ac7461a93b12134045ae1cf2457e2ee3b7 held.txt
-- sha256 c6b5c71247d129964dd89ba560a4522caef1abbb9379ad1b3445d6ed96be805b adoption/000000_initial.sql
-- sha256 28ef33976beb9c7c9248ac800f29aab048f4410c2170ad12e3ade71d72e5ecb5 adoption/000001_update_pwreset_table.sql
-- sha256 c3393049eae0a663ecea42a4917a06b37521a8ff508d39b308f8fd9da5606bf9 adoption/000002_add_xid_constraint.sql
-- sha256 3b1c9a390cbf23882455f1f3d05119df4a306f9a04d18e8c0e2cff3374895b86 adoption/000003_add_origin_permanent_cookie_columns.sql
-- sha256 5fae81bb9ff86062125487df98c1742e7ce5c45466fbeed7f6f63cbf94b1933b adoption/000004_drop_waitinglist_table.sql
-- sha256 02c90a416148f29c0717c01bcc97e66d6e8083ab3a2fabc5dc6bc716e963447e adoption/000005_drop_slack_stripe_canvas.sql
-- sha256 42d43c346ea90d0504698df29f90dd2c7e57860338c633da11410aaf9aaf5148 adoption/000006_update_votes_rule.sql
-- sha256 5a4110278c60157f21e5cb920ece834f6d6f99e6d4fa34b9b55bf0c6e80587c0 adoption/000007_drop_geolocation_fields.sql
-- sha256 a10a1a1881044409d98efd6042b5b28933a4579bce32738be1c4bc268640f172 adoption/000008_add_comment_priority.sql
-- sha256 a5605b5a292f5b4d47849cb7f2b678211e3bcdc9722cf9e5eabe54f455a5aa7c adoption/000009_add_uuid_to_zinvites.sql
-- sha256 23d5179cd0b556a71fe8b1ce56d3ac9e614cdee59832ce7892a012f0193cfe66 adoption/000010_create_oidc_user_mappings.sql
-- sha256 c991ffd93cd9051302dd51ab8d5bd6025128fc9728330e29aa963306a9b80f3e adoption/000011_alter_suzinvites_xid_to_text.sql
-- sha256 c31bd6811efee0808da5abb32ba63c47deebe6c6e89baa1a80ddcacc9e250234 adoption/000012_create_topic_agenda_selections.sql
-- sha256 eed1d9e223322db2b234428d350b6548793e54b94315932658b693d8263a6001 adoption/000013_create_treevite.sql
-- sha256 6b99d93d2f90f03bee170305c4b1305f03636882a84cdd08e107a763f1fc0120 adoption/000014_alter_reports_modlevel.sql
-- sha256 30c8d693d4f0d523c68a375bf0160e71e574f0a155badc363e085c4688ff0625 adoption/000015_add_xid_requirements.sql
-- sha256 ffb57aff8be7bc81bf10899133fe2a243cb20b58eb6b73afb3b76a66d5632478 adoption/000016_add_orig_id.sql
-- sha256 b72fbd498c13aceb7973100331c58b55a468b7e4447645a3e5c93f79a1126fd6 adoption/000017_create_byod_job_table.sql
-- sha256 96bf4a25a5733ac3dce8a7f25a4f374b5ee9bed924e95e048f73a343d2ddf539 adoption/000018_add_topics_enabled.sql
-- sha256 9764fc94c4fe4ac19626381146a588da3f6b4d32cac53ab59ae87b401ea8af8a adoption/000022_add_poll_timestamp_indexes.sql
-- sha256 2652134140cd8796ee3ab64995d509206bab3ebe8a03bba0cf48038a32dc6cea 000000_initial.sql
-- sha256 cb21278194c4b7db510c12bf1a7761b3a905410a7b3769edeb0d1865b6ec047b 000001_update_pwreset_table.sql
-- sha256 a27a8e63c79cd055198fa201b1745c85e0cd0e0b75f228b7153571631e529c07 000002_add_xid_constraint.sql
-- sha256 0d7f27facfecff1327573d3e1a5f65a3277ea94a30bcd8692606f00a7e496d3d 000003_add_origin_permanent_cookie_columns.sql
-- sha256 f2fc4184a965ffad01913d0e71a806c6f7e2aecc5f59279c11b0cd3ed3a77528 000004_drop_waitinglist_table.sql
-- sha256 392e5b8aadb7a85767820ec97fcfb0853821d35089be3e8c3dfe70df24782839 000005_drop_slack_stripe_canvas.sql
-- sha256 8fb05b7b1b6a8b123cea6b2680054d8da2fe48585c51a2f9f108b8b174d85c60 000006_update_votes_rule.sql
-- sha256 f68b69b86112ad52e2cb79a9b631ea77a0285b24201b41c15d9c13257f7cd9cc 000007_drop_geolocation_fields.sql
-- sha256 c867b53be3cca6bce059b19ea9eb3950120fb5840a1476af409924ca55905261 000008_add_comment_priority.sql
-- sha256 43f36fe0b8578bc4b32761a2b9d7a5181a8159ff8b0c7bb0a1a73f802ec5f670 000009_add_uuid_to_zinvites.sql
-- sha256 450a3f69883aa56c3bc85994ab1baf5e208634d88435a156fe2a22738b1d9f9a 000010_create_oidc_user_mappings.sql
-- sha256 00a1eb2d9604804a56705eaac92bb6d37b6c696abdfd9bb079d4a1c494ff0ab6 000011_alter_suzinvites_xid_to_text.sql
-- sha256 cc513693124f031ce1d55e7e73b14b4e3c40a4070e65465adbc621e63b1008cf 000012_create_topic_agenda_selections.sql
-- sha256 4b8334f73246c69bc9ecadd4a2dc00c8cfb642351ba70ed4a9a58b882a4ac53f 000013_create_treevite.sql
-- sha256 c2af6d57af2866f1f259bb41b94dbf730eca499a4b18f092c4aeeebce5a95025 000014_alter_reports_modlevel.sql
-- sha256 186c904addd0c8a42c10057e6ae362fe2799cc076e877bef3ffa14e9852184e7 000015_add_xid_requirements.sql
-- sha256 6cdc0588c000fbbe89d578bc2f0aa60422b92b5320aba737d6d83f89d8d990db 000016_add_orig_id.sql
-- sha256 f27c03a1229f296fab21cee059b743c7137bf502e4178854e596a8efa4808b55 000017_create_byod_job_table.sql
-- sha256 a1e1c0572064d88877d87142bc4e40132b84672bbe84392e99f9f6f4c2ea107e 000018_add_topics_enabled.sql
-- sha256 fedfbcf9fc594c3e53193cacb76dfd35558d81a449d507fcacb3198f5e39beae 000019_create_polis_queue.sql
-- sha256 d50f169ad7afe12d14582a6a746c622d402ecafd8131aae246812263bf2d5e82 000021_create_polis_coordinator.sql
-- sha256 14efc95b14787b52d70680ea06cfef020cd2224e82495258fd8eb324501b7b3e 000022_add_poll_timestamp_indexes.sql
-- sha256 97437ea57d90c51cc664385ebb6e8ec3d8684ac0f8e7b0c60e84df1a010531f7 000023_create_delphi_foundation.sql
-- sha256 68261afb81f286bed45fdff6ab52e052392d1dd32abdb1e78579f72644116697 000024_create_polis_queue_large_class.sql
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL search_path=pg_catalog,public;
SET LOCAL statement_timeout='30s';
SET LOCAL lock_timeout='2s';
WITH checks AS (
SELECT '000000_initial.sql'::text AS migration, (-- Named legacy variants are documented in docs/migration-legacy-contract.md.
-- Contributor agreement tables are outside this release adoption boundary.
-- Catalog postconditions only; this file never replays migration DDL.
SELECT NOT EXISTS (SELECT 1 FROM (VALUES
 ('users','uid','integer'),
 ('users','hname','character varying(746)'),
 ('users','created','bigint'),
 ('users','username','character varying(128)'),
 ('users','email','character varying(256)'),
 ('users','is_owner','boolean'),
 ('users','zinvite','character varying(300)'),
 ('users','oinvite','character varying(300)'),
 ('users','tut','smallint'),
 ('users','site_id','character varying(256)'),
 ('users','site_owner','boolean'),
 ('site_domain_whitelist','site_id','character varying(256)'),
 ('site_domain_whitelist','domain_whitelist','character varying(999)'),
 ('site_domain_whitelist','domain_whitelist_override_key','character varying(999)'),
 ('site_domain_whitelist','modified','bigint'),
 ('site_domain_whitelist','created','bigint'),
 ('metrics','uid','integer'),
 ('metrics','type','integer'),
 ('metrics','dur','integer'),
 ('metrics','hashedpc','integer'),
 ('metrics','created','bigint'),
 ('auth_tokens','token','character varying(32)'),
 ('auth_tokens','uid','integer'),
 ('auth_tokens','created','bigint'),
 ('jianiuevyew','uid','integer'),
 ('jianiuevyew','pwhash','character varying(128)'),
 ('apikeysndvweifu','uid','integer'),
 ('apikeysndvweifu','apikey','character varying(32)'),
 ('apikeysndvweifu','created','bigint'),
 ('courses','course_id','integer'),
 ('courses','topic','character varying(1000)'),
 ('courses','description','character varying(1000)'),
 ('courses','owner','integer'),
 ('courses','course_invite','character varying(32)'),
 ('courses','created','bigint'),
 ('conversations','zid','integer'),
 ('conversations','topic','character varying(1000)'),
 ('conversations','description','character varying(50000)'),
 ('conversations','link_url','character varying(9999)'),
 ('conversations','parent_url','character varying(9999)'),
 ('conversations','upvotes','integer'),
 ('conversations','participant_count','integer'),
 ('conversations','is_anon','boolean'),
 ('conversations','is_active','boolean'),
 ('conversations','is_draft','boolean'),
 ('conversations','is_public','boolean'),
 ('conversations','is_data_open','boolean'),
 ('conversations','profanity_filter','boolean'),
 ('conversations','spam_filter','boolean'),
 ('conversations','strict_moderation','boolean'),
 ('conversations','prioritize_seed','boolean'),
 ('conversations','vis_type','integer'),
 ('conversations','write_type','integer'),
 ('conversations','help_type','integer'),
 ('conversations','write_hint_type','integer'),
 ('conversations','style_btn','character varying(500)'),
 ('conversations','socialbtn_type','integer'),
 ('conversations','subscribe_type','integer'),
 ('conversations','bgcolor','character varying(20)'),
 ('conversations','help_bgcolor','character varying(20)'),
 ('conversations','help_color','character varying(20)'),
 ('conversations','email_domain','character varying(200)'),
 ('conversations','use_xid_whitelist','boolean'),
 ('conversations','owner','integer'),
 ('conversations','org_id','integer'),
 ('conversations','context','character varying(1000)'),
 ('conversations','course_id','integer'),
 ('conversations','owner_sees_participation_stats','boolean'),
 ('conversations','auth_needed_to_vote','boolean'),
 ('conversations','auth_needed_to_write','boolean'),
 ('conversations','auth_opt_fb','boolean'),
 ('conversations','auth_opt_tw','boolean'),
 ('conversations','auth_opt_allow_3rdparty','boolean'),
 ('conversations','modified','bigint'),
 ('conversations','created','bigint'),
 ('participant_metadata_questions','pmqid','integer'),
 ('participant_metadata_questions','zid','integer'),
 ('participant_metadata_questions','key','character varying(999)'),
 ('participant_metadata_questions','alive','boolean'),
 ('participant_metadata_questions','created','bigint'),
 ('participant_metadata_answers','pmaid','integer'),
 ('participant_metadata_answers','pmqid','integer'),
 ('participant_metadata_answers','zid','integer'),
 ('participant_metadata_answers','value','character varying(999)'),
 ('participant_metadata_answers','alive','boolean'),
 ('participant_metadata_answers','created','bigint'),
 ('contexts','context_id','integer'),
 ('contexts','name','character varying(300)'),
 ('contexts','creator','integer'),
 ('contexts','is_public','boolean'),
 ('contexts','created','bigint'),
 ('inviters','inviter_uid','integer'),
 ('inviters','invited_email','character varying(999)'),
 ('inviters','created','bigint'),
 ('upvotes','uid','integer'),
 ('upvotes','zid','integer'),
 ('oinvites','oinvite','character varying(300)'),
 ('oinvites','note','character varying(999)'),
 ('oinvites','created','bigint'),
 ('einvites','einvite','character varying(100)'),
 ('einvites','email','character varying(999)'),
 ('einvites','created','bigint'),
 ('email_validations','email','character varying(999)'),
 ('email_validations','created','bigint'),
 ('zinvites','zid','integer'),
 ('zinvites','zinvite','character varying(300)'),
 ('zinvites','created','bigint'),
 ('beta','name','character varying(999)'),
 ('beta','email','character varying(200)'),
 ('beta','organization','character varying(200)'),
 ('beta','created','bigint'),
 ('participants','pid','integer'),
 ('participants','uid','integer'),
 ('participants','zid','integer'),
 ('participants','vote_count','integer'),
 ('participants','last_interaction','bigint'),
 ('participants','subscribed','integer'),
 ('participants','last_notified','bigint'),
 ('participants','nsli','smallint'),
 ('participants','mod','integer'),
 ('participants','created','bigint'),
 ('participants_extended','uid','integer'),
 ('participants_extended','zid','integer'),
 ('participants_extended','referrer','character varying(9999)'),
 ('participants_extended','parent_url','character varying(9999)'),
 ('participants_extended','created','bigint'),
 ('participants_extended','modified','bigint'),
 ('participants_extended','subscribe_email','character varying(256)'),
 ('participants_extended','show_translation_activated','boolean'),
 ('participant_locations','zid','integer'),
 ('participant_locations','uid','integer'),
 ('participant_locations','pid','integer'),
 ('participant_locations','lat','double precision'),
 ('participant_locations','lng','double precision'),
 ('participant_locations','created','bigint'),
 ('participant_locations','source','integer'),
 ('xids','uid','integer'),
 ('xids','owner','integer'),
 ('xids','xid','text'),
 ('xids','x_profile_image_url','character varying(3000)'),
 ('xids','x_name','character varying(746)'),
 ('xids','x_email','character varying(256)'),
 ('xids','created','bigint'),
 ('xids','modified','bigint'),
 ('xid_whitelist','owner','integer'),
 ('xid_whitelist','xid','text'),
 ('xid_whitelist','created','bigint'),
 ('notification_tasks','zid','integer'),
 ('notification_tasks','modified','bigint'),
 ('participant_metadata_choices','zid','integer'),
 ('participant_metadata_choices','pid','integer'),
 ('participant_metadata_choices','pmqid','integer'),
 ('participant_metadata_choices','pmaid','integer'),
 ('participant_metadata_choices','alive','boolean'),
 ('participant_metadata_choices','created','bigint'),
 ('twitter_users','uid','integer'),
 ('twitter_users','twitter_user_id','bigint'),
 ('twitter_users','screen_name','character varying(999)'),
 ('twitter_users','name','character varying(9999)'),
 ('twitter_users','followers_count','integer'),
 ('twitter_users','friends_count','integer'),
 ('twitter_users','verified','boolean'),
 ('twitter_users','profile_image_url_https','character varying(9999)'),
 ('twitter_users','location','character varying(9999)'),
 ('twitter_users','response','json'),
 ('twitter_users','modified','bigint'),
 ('twitter_users','created','bigint'),
 ('facebook_users','uid','integer'),
 ('facebook_users','fb_user_id','text'),
 ('facebook_users','fb_name','character varying(9999)'),
 ('facebook_users','fb_link','character varying(9999)'),
 ('facebook_users','fb_public_profile','text'),
 ('facebook_users','fb_login_status','text'),
 ('facebook_users','fb_auth_response','text'),
 ('facebook_users','fb_access_token','text'),
 ('facebook_users','fb_granted_scopes','text'),
 ('facebook_users','fb_location_id','character varying(100)'),
 ('facebook_users','location','character varying(9999)'),
 ('facebook_users','response','text'),
 ('facebook_users','fb_friends_response','text'),
 ('facebook_users','created','bigint'),
 ('facebook_users','modified','bigint'),
 ('social_settings','uid','integer'),
 ('social_settings','polis_pic','character varying(3000)'),
 ('facebook_friends','uid','integer'),
 ('facebook_friends','friend','integer'),
 ('suzinvites','owner','integer'),
 ('suzinvites','zid','integer'),
 ('suzinvites','created','bigint'),
 ('suzinvites','suzinvite','character varying(32)'),
 ('comments','tid','integer'),
 ('comments','zid','integer'),
 ('comments','pid','integer'),
 ('comments','uid','integer'),
 ('comments','created','bigint'),
 ('comments','modified','bigint'),
 ('comments','txt','character varying(1000)'),
 ('comments','velocity','real'),
 ('comments','mod','integer'),
 ('comments','lang','character varying(10)'),
 ('comments','lang_confidence','real'),
 ('comments','active','boolean'),
 ('comments','is_meta','boolean'),
 ('comments','tweet_id','bigint'),
 ('comments','quote_src_url','character varying(1000)'),
 ('comments','anon','boolean'),
 ('comments','is_seed','boolean'),
 ('comment_translations','zid','integer'),
 ('comment_translations','tid','integer'),
 ('comment_translations','src','integer'),
 ('comment_translations','txt','character varying(9999)'),
 ('comment_translations','lang','character varying(10)'),
 ('comment_translations','created','bigint'),
 ('comment_translations','modified','bigint'),
 ('conversation_translations','zid','integer'),
 ('conversation_translations','src','integer'),
 ('conversation_translations','topic','character varying(9999)'),
 ('conversation_translations','description','character varying(9999)'),
 ('conversation_translations','lang','character varying(10)'),
 ('conversation_translations','created','bigint'),
 ('conversation_translations','modified','bigint'),
 ('reports','rid','bigint'),
 ('reports','report_id','character varying(300)'),
 ('reports','zid','integer'),
 ('reports','created','bigint'),
 ('reports','modified','bigint'),
 ('reports','report_name','character varying(999)'),
 ('reports','label_x_neg','character varying(999)'),
 ('reports','label_x_pos','character varying(999)'),
 ('reports','label_y_neg','character varying(999)'),
 ('reports','label_y_pos','character varying(999)'),
 ('reports','label_group_0','character varying(999)'),
 ('reports','label_group_1','character varying(999)'),
 ('reports','label_group_2','character varying(999)'),
 ('reports','label_group_3','character varying(999)'),
 ('reports','label_group_4','character varying(999)'),
 ('reports','label_group_5','character varying(999)'),
 ('reports','label_group_6','character varying(999)'),
 ('reports','label_group_7','character varying(999)'),
 ('reports','label_group_8','character varying(999)'),
 ('reports','label_group_9','character varying(999)'),
 ('report_comment_selections','zid','integer'),
 ('report_comment_selections','rid','bigint'),
 ('report_comment_selections','tid','integer'),
 ('report_comment_selections','selection','smallint'),
 ('report_comment_selections','modified','bigint'),
 ('worker_tasks','created','bigint'),
 ('worker_tasks','math_env','character varying(999)'),
 ('worker_tasks','attempts','smallint'),
 ('worker_tasks','task_data','jsonb'),
 ('worker_tasks','task_type','text'),
 ('worker_tasks','task_bucket','bigint'),
 ('worker_tasks','finished_time','bigint'),
 ('math_ticks','zid','integer'),
 ('math_ticks','math_tick','bigint'),
 ('math_ticks','math_env','character varying(999)'),
 ('math_ticks','modified','bigint'),
 ('math_main','zid','integer'),
 ('math_main','math_env','character varying(999)'),
 ('math_main','data','jsonb'),
 ('math_main','last_vote_timestamp','bigint'),
 ('math_main','caching_tick','bigint'),
 ('math_main','math_tick','bigint'),
 ('math_main','modified','bigint'),
 ('math_profile','zid','integer'),
 ('math_profile','math_env','character varying(999)'),
 ('math_profile','data','jsonb'),
 ('math_profile','modified','bigint'),
 ('math_ptptstats','zid','integer'),
 ('math_ptptstats','math_env','character varying(999)'),
 ('math_ptptstats','math_tick','bigint'),
 ('math_ptptstats','data','jsonb'),
 ('math_ptptstats','modified','bigint'),
 ('math_cache','zid','integer'),
 ('math_cache','math_env','character varying(999)'),
 ('math_cache','data','jsonb'),
 ('math_cache','modified','bigint'),
 ('math_bidtopid','zid','integer'),
 ('math_bidtopid','math_env','character varying(999)'),
 ('math_bidtopid','math_tick','bigint'),
 ('math_bidtopid','data','jsonb'),
 ('math_bidtopid','modified','bigint'),
 ('math_exportstatus','zid','integer'),
 ('math_exportstatus','math_env','character varying(999)'),
 ('math_exportstatus','filename','character varying(9999)'),
 ('math_exportstatus','data','jsonb'),
 ('math_exportstatus','modified','bigint'),
 ('math_report_correlationmatrix','rid','bigint'),
 ('math_report_correlationmatrix','math_env','character varying(999)'),
 ('math_report_correlationmatrix','data','jsonb'),
 ('math_report_correlationmatrix','math_tick','bigint'),
 ('math_report_correlationmatrix','modified','bigint'),
 ('votes','zid','integer'),
 ('votes','pid','integer'),
 ('votes','tid','integer'),
 ('votes','vote','smallint'),
 ('votes','weight_x_32767','smallint'),
 ('votes','created','bigint'),
 ('votes_latest_unique','zid','integer'),
 ('votes_latest_unique','pid','integer'),
 ('votes_latest_unique','tid','integer'),
 ('votes_latest_unique','vote','smallint'),
 ('votes_latest_unique','weight_x_32767','smallint'),
 ('votes_latest_unique','modified','bigint'),
 ('crowd_mod','zid','integer'),
 ('crowd_mod','pid','integer'),
 ('crowd_mod','tid','integer'),
 ('crowd_mod','created','bigint'),
 ('crowd_mod','as_important','boolean'),
 ('crowd_mod','as_factual','boolean'),
 ('crowd_mod','as_feeling','boolean'),
 ('crowd_mod','as_notmyfeeling','boolean'),
 ('crowd_mod','as_notgoodidea','boolean'),
 ('crowd_mod','as_notfact','boolean'),
 ('crowd_mod','as_unsure','boolean'),
 ('crowd_mod','as_spam','boolean'),
 ('crowd_mod','as_abusive','boolean'),
 ('crowd_mod','as_offtopic','boolean'),
 ('event_ptpt_no_more_comments','zid','integer'),
 ('event_ptpt_no_more_comments','pid','integer'),
 ('event_ptpt_no_more_comments','votes_placed','smallint'),
 ('event_ptpt_no_more_comments','created','bigint'),
 ('stars','zid','integer'),
 ('stars','pid','integer'),
 ('stars','tid','integer'),
 ('stars','starred','integer'),
 ('stars','created','bigint'),
 ('trashes','zid','integer'),
 ('trashes','pid','integer'),
 ('trashes','tid','integer'),
 ('trashes','trashed','integer'),
 ('trashes','created','bigint'),
 ('permanentcookiezidjoins','zid','integer'),
 ('permanentcookiezidjoins','cookie','character varying(32)'),
 ('permanentcookiezidjoins','created','bigint'),
 ('page_ids','site_id','character varying(100)'),
 ('page_ids','page_id','character varying(100)'),
 ('page_ids','zid','integer'),
 ('demographic_data','uid','integer'),
 ('demographic_data','fb_gender','integer'),
 ('demographic_data','ms_birth_year_estimate_fb','integer'),
 ('demographic_data','ms_gender_estimate_fb','integer'),
 ('demographic_data','fb_timestamp','bigint'),
 ('demographic_data','ms_fb_timestamp','bigint'),
 ('demographic_data','ms_response','character varying(9999)'),
 ('demographic_data','gender_guess','integer'),
 ('demographic_data','birth_year_guess','integer')) AS expected(t,c,typ) WHERE NOT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||(t)) AND a.attname=(c) AND NOT a.attisdropped
 AND (format_type(a.atttypid,a.atttypmod)=(typ)
      -- Exact public bootstrap alternatives to the authoritative legacy contract.
      OR ((t)='worker_tasks' AND (c)='task_type' AND (typ)='text'
          AND format_type(a.atttypid,a.atttypmod)='character varying(99)')
      OR ((t) IN ('pwreset_tokens','password_reset_tokens')
          AND (c) IN ('token','pwresettoken') AND (typ)='character varying(100)'
          AND format_type(a.atttypid,a.atttypmod)='character varying(250)')
      -- Only historical math payloads have an established json equivalent.
      -- Do not adopt arbitrary json columns in newer jsonb contracts.
      OR ((typ)='jsonb' AND a.atttypid='json'::regtype AND (c)='data'
          AND (t) IN ('math_main','math_profile','math_ptptstats','math_cache',
                    'math_bidtopid','math_exportstatus')))
 AND ((NULL) IS NULL OR a.attnotnull=(NULL))
 AND ((NULL) IS NULL OR pg_get_expr(d.adbin,d.adrelid)=(NULL)))))
 AND NOT EXISTS (SELECT 1 FROM unnest(ARRAY['users','site_domain_whitelist','metrics','auth_tokens','jianiuevyew','apikeysndvweifu','courses','conversations','participant_metadata_questions','participant_metadata_answers','contexts','inviters','upvotes','oinvites','einvites','email_validations','zinvites','beta','participants','participants_extended','participant_locations','xids','xid_whitelist','notification_tasks','participant_metadata_choices','twitter_users','facebook_users','social_settings','facebook_friends','suzinvites','comments','comment_translations','conversation_translations','reports','report_comment_selections','worker_tasks','math_ticks','math_main','math_profile','math_ptptstats','math_cache','math_bidtopid','math_exportstatus','math_report_correlationmatrix','votes','votes_latest_unique','crowd_mod','event_ptpt_no_more_comments','stars','trashes','permanentcookiezidjoins','page_ids','demographic_data']) t WHERE to_regclass('public.'||t) IS NULL)
 AND ((SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('pwreset_tokens')) AND a.attname=('token') AND NOT a.attisdropped
 AND (format_type(a.atttypid,a.atttypmod)=('character varying(100)')
      -- Exact public bootstrap alternatives to the authoritative legacy contract.
      OR (('pwreset_tokens')='worker_tasks' AND ('token')='task_type' AND ('character varying(100)')='text'
          AND format_type(a.atttypid,a.atttypmod)='character varying(99)')
      OR (('pwreset_tokens') IN ('pwreset_tokens','password_reset_tokens')
          AND ('token') IN ('token','pwresettoken') AND ('character varying(100)')='character varying(100)'
          AND format_type(a.atttypid,a.atttypmod)='character varying(250)')
      -- Only historical math payloads have an established json equivalent.
      -- Do not adopt arbitrary json columns in newer jsonb contracts.
      OR (('character varying(100)')='jsonb' AND a.atttypid='json'::regtype AND ('token')='data'
          AND ('pwreset_tokens') IN ('math_main','math_profile','math_ptptstats','math_cache',
                    'math_bidtopid','math_exportstatus')))
 AND ((NULL) IS NULL OR a.attnotnull=(NULL))
 AND ((NULL) IS NULL OR pg_get_expr(d.adbin,d.adrelid)=(NULL)))) OR (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('password_reset_tokens')) AND a.attname=('pwresettoken') AND NOT a.attisdropped
 AND (format_type(a.atttypid,a.atttypmod)=('character varying(100)')
      -- Exact public bootstrap alternatives to the authoritative legacy contract.
      OR (('password_reset_tokens')='worker_tasks' AND ('pwresettoken')='task_type' AND ('character varying(100)')='text'
          AND format_type(a.atttypid,a.atttypmod)='character varying(99)')
      OR (('password_reset_tokens') IN ('pwreset_tokens','password_reset_tokens')
          AND ('pwresettoken') IN ('token','pwresettoken') AND ('character varying(100)')='character varying(100)'
          AND format_type(a.atttypid,a.atttypmod)='character varying(250)')
      -- Only historical math payloads have an established json equivalent.
      -- Do not adopt arbitrary json columns in newer jsonb contracts.
      OR (('character varying(100)')='jsonb' AND a.atttypid='json'::regtype AND ('pwresettoken')='data'
          AND ('password_reset_tokens') IN ('math_main','math_profile','math_ptptstats','math_cache',
                    'math_bidtopid','math_exportstatus')))
 AND ((NULL) IS NULL OR a.attnotnull=(NULL))
 AND ((NULL) IS NULL OR pg_get_expr(d.adbin,d.adrelid)=(NULL)))))
 AND ((SELECT to_regclass('public.'||('conversations')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('conversations')) AND attname=('branding_type') AND NOT attisdropped)) OR (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('conversations')) AND a.attname=('branding_type') AND NOT a.attisdropped
 AND (format_type(a.atttypid,a.atttypmod)=('integer')
      -- Exact public bootstrap alternatives to the authoritative legacy contract.
      OR (('conversations')='worker_tasks' AND ('branding_type')='task_type' AND ('integer')='text'
          AND format_type(a.atttypid,a.atttypmod)='character varying(99)')
      OR (('conversations') IN ('pwreset_tokens','password_reset_tokens')
          AND ('branding_type') IN ('token','pwresettoken') AND ('integer')='character varying(100)'
          AND format_type(a.atttypid,a.atttypmod)='character varying(250)')
      -- Only historical math payloads have an established json equivalent.
      -- Do not adopt arbitrary json columns in newer jsonb contracts.
      OR (('integer')='jsonb' AND a.atttypid='json'::regtype AND ('branding_type')='data'
          AND ('conversations') IN ('math_main','math_profile','math_ptptstats','math_cache',
                    'math_bidtopid','math_exportstatus')))
 AND ((NULL) IS NULL OR a.attnotnull=(NULL))
 AND ((NULL) IS NULL OR pg_get_expr(d.adbin,d.adrelid)=(NULL)))))
 AND ((SELECT to_regclass('public.'||('math_ticks')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('math_ticks')) AND attname=('caching_tick') AND NOT attisdropped)) OR (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('math_ticks')) AND a.attname=('caching_tick') AND NOT a.attisdropped
 AND (format_type(a.atttypid,a.atttypmod)=('bigint')
      -- Exact public bootstrap alternatives to the authoritative legacy contract.
      OR (('math_ticks')='worker_tasks' AND ('caching_tick')='task_type' AND ('bigint')='text'
          AND format_type(a.atttypid,a.atttypmod)='character varying(99)')
      OR (('math_ticks') IN ('pwreset_tokens','password_reset_tokens')
          AND ('caching_tick') IN ('token','pwresettoken') AND ('bigint')='character varying(100)'
          AND format_type(a.atttypid,a.atttypmod)='character varying(250)')
      -- Only historical math payloads have an established json equivalent.
      -- Do not adopt arbitrary json columns in newer jsonb contracts.
      OR (('bigint')='jsonb' AND a.atttypid='json'::regtype AND ('caching_tick')='data'
          AND ('math_ticks') IN ('math_main','math_profile','math_ptptstats','math_cache',
                    'math_bidtopid','math_exportstatus')))
 AND ((NULL) IS NULL OR a.attnotnull=(NULL))
 AND ((NULL) IS NULL OR pg_get_expr(d.adbin,d.adrelid)=(NULL)))))
 AND to_regprocedure('public.now_as_millis()') IS NOT NULL
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint WHERE conrelid=to_regclass('public.'||('votes_latest_unique'))
 AND convalidated AND pg_get_constraintdef(oid)=('UNIQUE (zid, pid, tid)')))) AS catalog_match
UNION ALL
SELECT '000001_update_pwreset_table.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT to_regclass('public.password_reset_tokens') IS NULL
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('pwreset_tokens')) AND a.attname=('token') AND NOT a.attisdropped
 AND (format_type(a.atttypid,a.atttypmod)=('character varying(100)')
      -- Exact public bootstrap alternatives to the authoritative legacy contract.
      OR (('pwreset_tokens')='worker_tasks' AND ('token')='task_type' AND ('character varying(100)')='text'
          AND format_type(a.atttypid,a.atttypmod)='character varying(99)')
      OR (('pwreset_tokens') IN ('pwreset_tokens','password_reset_tokens')
          AND ('token') IN ('token','pwresettoken') AND ('character varying(100)')='character varying(100)'
          AND format_type(a.atttypid,a.atttypmod)='character varying(250)')
      -- Only historical math payloads have an established json equivalent.
      -- Do not adopt arbitrary json columns in newer jsonb contracts.
      OR (('character varying(100)')='jsonb' AND a.atttypid='json'::regtype AND ('token')='data'
          AND ('pwreset_tokens') IN ('math_main','math_profile','math_ptptstats','math_cache',
                    'math_bidtopid','math_exportstatus')))
 AND ((NULL) IS NULL OR a.attnotnull=(NULL))
 AND ((NULL) IS NULL OR pg_get_expr(d.adbin,d.adrelid)=(NULL))))
 AND (SELECT to_regclass('public.'||('pwreset_tokens')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('pwreset_tokens')) AND attname=('pwresettoken') AND NOT attisdropped))) AS catalog_match
UNION ALL
SELECT '000002_add_xid_constraint.sql'::text AS migration, (-- Both the public bootstrap variant (owner,xid only) and the authoritative
-- legacy variant (also owner,uid) are supported. Never drop either invariant.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('xids'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('UNIQUE (owner, xid)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 -- If the optional legacy unique index exists, it must enforce the complete key.
 AND NOT EXISTS (
   SELECT 1 FROM pg_index i
   JOIN pg_attribute owner ON owner.attrelid=i.indrelid AND owner.attname='owner'
   JOIN pg_attribute uid ON uid.attrelid=i.indrelid AND uid.attname='uid'
   WHERE i.indrelid=to_regclass('public.xids') AND i.indisunique
     AND i.indnkeyatts=2
     AND ARRAY[i.indkey[0],i.indkey[1]] @> ARRAY[owner.attnum,uid.attnum]
     AND (NOT i.indisvalid OR NOT i.indisready OR NOT i.indislive
          OR NOT i.indimmediate OR i.indpred IS NOT NULL)
 )) AS catalog_match
UNION ALL
SELECT '000003_add_origin_permanent_cookie_columns.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('participants_extended')) AND a.attname=('permanent_cookie') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('character varying(32)') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('participants_extended')) AND a.attname=('origin') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('character varying(9999)') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))) AS catalog_match
UNION ALL
SELECT '000004_drop_waitinglist_table.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT to_regclass('public.waitinglist') IS NULL) AS catalog_match
UNION ALL
SELECT '000005_drop_slack_stripe_canvas.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT to_regclass('public.slack_oauth_access_tokens') IS NULL
 AND to_regclass('public.slack_users') IS NULL
 AND to_regclass('public.slack_user_invites') IS NULL
 AND to_regclass('public.slack_bot_events') IS NULL
 AND to_regclass('public.stripe_accounts') IS NULL
 AND to_regclass('public.stripe_subscriptions') IS NULL
 AND to_regclass('public.coupons_for_free_upgrades') IS NULL
 AND to_regclass('public.lti_users') IS NULL
 AND to_regclass('public.lti_context_memberships') IS NULL
 AND to_regclass('public.canvas_assignment_callback_info') IS NULL
 AND to_regclass('public.canvas_assignment_conversation_info') IS NULL
 AND to_regclass('public.lti_oauthv1_credentials') IS NULL
 AND (SELECT to_regclass('public.'||('conversations')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('conversations')) AND attname=('is_slack') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('conversations')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('conversations')) AND attname=('lti_users_only') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('users')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('users')) AND attname=('plan') AND NOT attisdropped))) AS catalog_match
UNION ALL
SELECT '000006_update_votes_rule.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT EXISTS (SELECT 1 FROM pg_rewrite WHERE ev_class=to_regclass('public.votes') AND rulename='on_vote_insert_update_unique_table' AND ev_enabled='O' AND regexp_replace(pg_get_ruledef(oid), '\s+', ' ', 'g') = 'CREATE RULE on_vote_insert_update_unique_table AS ON INSERT TO public.votes DO INSERT INTO votes_latest_unique (zid, pid, tid, vote, weight_x_32767, modified) VALUES (new.zid, new.pid, new.tid, new.vote, new.weight_x_32767, new.created) ON CONFLICT(zid, pid, tid) DO UPDATE SET vote = excluded.vote, modified = excluded.modified;')) AS catalog_match
UNION ALL
SELECT '000007_drop_geolocation_fields.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT to_regclass('public.geolocation_cache') IS NULL
 AND (SELECT to_regclass('public.'||('participants_extended')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('participants_extended')) AND attname=('country_code_iso') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('participants_extended')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('participants_extended')) AND attname=('encrypted_maxmind_response_city') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('participants_extended')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('participants_extended')) AND attname=('ip_address') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('participants_extended')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('participants_extended')) AND attname=('latitude') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('participants_extended')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('participants_extended')) AND attname=('location') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('participants_extended')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('participants_extended')) AND attname=('longitude') AND NOT attisdropped))
 AND (SELECT to_regclass('public.'||('participants_extended')) IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_attribute
 WHERE attrelid=to_regclass('public.'||('participants_extended')) AND attname=('x_forwarded_for') AND NOT attisdropped))) AS catalog_match
UNION ALL
SELECT '000008_add_comment_priority.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('conversations')) AND a.attname=('importance_enabled') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('boolean') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('false')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('votes')) AND a.attname=('high_priority') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('boolean') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('false')))) AS catalog_match
UNION ALL
SELECT '000009_add_uuid_to_zinvites.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('zinvites')) AND a.attname=('uuid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('uuid') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))) AS catalog_match
UNION ALL
SELECT '000010_create_oidc_user_mappings.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('oidc_user_mappings')) AND a.attname=('oidc_sub') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('character varying(255)') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('oidc_user_mappings')) AND a.attname=('uid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('oidc_user_mappings')) AND a.attname=('created') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('bigint') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('now_as_millis()')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('oidc_user_mappings'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('PRIMARY KEY (oidc_sub)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('oidc_user_mappings'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('UNIQUE (uid)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('oidc_user_mappings'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_oidc_mappings_uid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_oidc_mappings_uid ON public.oidc_user_mappings USING btree (uid)')))) AS catalog_match
UNION ALL
SELECT '000011_alter_suzinvites_xid_to_text.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('suzinvites')) AND a.attname=('xid') AND NOT a.attisdropped
 AND (format_type(a.atttypid,a.atttypmod)=('text')
      -- Exact public bootstrap alternatives to the authoritative legacy contract.
      OR (('suzinvites')='worker_tasks' AND ('xid')='task_type' AND ('text')='text'
          AND format_type(a.atttypid,a.atttypmod)='character varying(99)')
      OR (('suzinvites') IN ('pwreset_tokens','password_reset_tokens')
          AND ('xid') IN ('token','pwresettoken') AND ('text')='character varying(100)'
          AND format_type(a.atttypid,a.atttypmod)='character varying(250)')
      -- Only historical math payloads have an established json equivalent.
      -- Do not adopt arbitrary json columns in newer jsonb contracts.
      OR (('text')='jsonb' AND a.atttypid='json'::regtype AND ('xid')='data'
          AND ('suzinvites') IN ('math_main','math_profile','math_ptptstats','math_cache',
                    'math_bidtopid','math_exportstatus')))
 AND ((true) IS NULL OR a.attnotnull=(true))
 AND ((NULL) IS NULL OR pg_get_expr(d.adbin,d.adrelid)=(NULL))))) AS catalog_match
UNION ALL
SELECT '000012_create_topic_agenda_selections.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('topic_agenda_selections')) AND a.attname=('zid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('topic_agenda_selections')) AND a.attname=('pid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('topic_agenda_selections')) AND a.attname=('archetypal_selections') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('jsonb') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('''[]''::jsonb')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('topic_agenda_selections')) AND a.attname=('delphi_job_id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('text') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('topic_agenda_selections')) AND a.attname=('total_selections') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('0')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('topic_agenda_selections')) AND a.attname=('created_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('topic_agenda_selections')) AND a.attname=('updated_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('topic_agenda_selections'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('PRIMARY KEY (zid, pid)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('topic_agenda_selections'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('topic_agenda_selections'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid, pid) REFERENCES participants(zid, pid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_topic_agenda_selections_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_topic_agenda_selections_zid ON public.topic_agenda_selections USING btree (zid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_topic_agenda_selections_pid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_topic_agenda_selections_pid ON public.topic_agenda_selections USING btree (pid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_topic_agenda_selections_delphi_job_id'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_topic_agenda_selections_delphi_job_id ON public.topic_agenda_selections USING btree (delphi_job_id)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_topic_agenda_selections_created_at'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_topic_agenda_selections_created_at ON public.topic_agenda_selections USING btree (created_at)')))) AS catalog_match
UNION ALL
SELECT '000013_create_treevite.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('conversations')) AND a.attname=('treevite_enabled') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('boolean') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('false')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('bigint') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('nextval(''treevite_waves_id_seq''::regclass)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('zid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('wave') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('parent_wave') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('size') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('invites_per_user') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('owner_invites') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('0')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('created_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_waves')) AND a.attname=('updated_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('PRIMARY KEY (id)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('bigint') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('nextval(''treevite_invites_id_seq''::regclass)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('zid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('wave_id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('bigint') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('parent_invite_id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('bigint') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('status') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('smallint') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('0')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('invite_owner_pid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('invite_used_by_pid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('invite_used_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('created_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('updated_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('PRIMARY KEY (id)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('bigint') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('nextval(''treevite_login_codes_id_seq''::regclass)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('zid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('pid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('login_code_hash') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('text') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('fp_kid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('smallint') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('1')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('revoked') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('boolean') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('false')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('expires_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('last_used_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('created_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('updated_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('CURRENT_TIMESTAMP')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_login_codes'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('PRIMARY KEY (id)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('UNIQUE (zid, wave)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('UNIQUE (zid, invite_code)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (wave_id) REFERENCES treevite_waves(id) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (parent_invite_id) REFERENCES treevite_invites(id) ON DELETE SET NULL')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid, invite_owner_pid) REFERENCES participants(zid, pid)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid, invite_used_by_pid) REFERENCES participants(zid, pid)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_login_codes'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid, pid) REFERENCES participants(zid, pid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_login_codes'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('UNIQUE (zid, pid)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_login_codes'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('UNIQUE (zid, login_code_fingerprint)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_login_codes'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('UNIQUE (zid, login_code_lookup)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_waves_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_waves_zid ON public.treevite_waves USING btree (zid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_waves_wave'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_waves_wave ON public.treevite_waves USING btree (wave)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_waves_parent'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_waves_parent ON public.treevite_waves USING btree (zid, parent_wave)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_invites_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_invites_zid ON public.treevite_invites USING btree (zid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_invites_zid_status'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_invites_zid_status ON public.treevite_invites USING btree (zid, status)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_invites_wave_id'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_invites_wave_id ON public.treevite_invites USING btree (wave_id)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_invites_parent'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_invites_parent ON public.treevite_invites USING btree (parent_invite_id)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_invites_owner_pid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_invites_owner_pid ON public.treevite_invites USING btree (invite_owner_pid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_invites_used_by_pid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_invites_used_by_pid ON public.treevite_invites USING btree (invite_used_by_pid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_invites_code'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_invites_code ON public.treevite_invites USING btree (invite_code)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_login_codes_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_login_codes_zid ON public.treevite_login_codes USING btree (zid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_login_codes_pid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_login_codes_pid ON public.treevite_login_codes USING btree (pid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_login_codes_fp'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_login_codes_fp ON public.treevite_login_codes USING btree (login_code_fingerprint)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_treevite_login_codes_lookup'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_treevite_login_codes_lookup ON public.treevite_login_codes USING btree (zid, login_code_lookup)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_invites')) AND a.attname=('invite_code') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('character varying(64)') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('login_code_fingerprint') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('character varying(128)') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('treevite_login_codes')) AND a.attname=('login_code_lookup') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('character varying(128)') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('CHECK (((invites_per_user > 0) OR (owner_invites > 0)))')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('CHECK (((parent_wave IS NULL) OR (parent_wave >= 0)))')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('CHECK (((size IS NULL) OR (size >= 0)))')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('CHECK ((invites_per_user >= 0))')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('CHECK ((owner_invites >= 0))')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_waves'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('CHECK ((wave >= 1))')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('treevite_invites'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('CHECK ((status = ANY (ARRAY[0, 1, 2, 3])))')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))) AS catalog_match
UNION ALL
SELECT '000014_alter_reports_modlevel.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('reports')) AND a.attname=('mod_level') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('smallint') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('''-2''::integer')))) AS catalog_match
UNION ALL
SELECT '000015_add_xid_requirements.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('conversations')) AND a.attname=('xid_required') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('boolean') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('false')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('xid_whitelist')) AND a.attname=('zid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('xids')) AND a.attname=('zid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('xids')) AND a.attname=('pid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('xid_whitelist'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('xids'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid) REFERENCES conversations(zid) ON DELETE CASCADE')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('xids'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('FOREIGN KEY (zid, pid) REFERENCES participants(zid, pid) ON DELETE SET NULL')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_xid_whitelist_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_xid_whitelist_zid ON public.xid_whitelist USING btree (zid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_xid_whitelist_xid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_xid_whitelist_xid ON public.xid_whitelist USING btree (xid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_xids_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_xids_zid ON public.xids USING btree (zid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_xids_xid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_xids_xid ON public.xids USING btree (xid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_xids_pid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_xids_pid ON public.xids USING btree (pid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_xids_zid_xid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_xids_zid_xid ON public.xids USING btree (zid, xid)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_xids_uid_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_xids_uid_zid ON public.xids USING btree (uid, zid)')))) AS catalog_match
UNION ALL
SELECT '000016_add_orig_id.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('comments')) AND a.attname=('original_id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('uuid') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))) AS catalog_match
UNION ALL
SELECT '000017_create_byod_job_table.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT array_agg(enumlabel::text ORDER BY enumsortorder) FROM pg_enum WHERE enumtypid=to_regtype('public.job_status')) = ARRAY['pending','processing','completed','failed']
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('id') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('nextval(''byod_import_jobs_id_seq''::regclass)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('zid') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('integer') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('s3_key') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('text') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('status') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('job_status') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('''pending''::job_status')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('stage') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('text') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('''init''::text')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('error_message') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('text') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM (NULL)))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('created_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('now()')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('byod_import_jobs')) AND a.attname=('updated_at') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('timestamp with time zone') AND a.attnotnull=(false)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('now()')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_constraint c
 WHERE c.conrelid=to_regclass('public.'||('byod_import_jobs'))
 AND c.convalidated AND NOT c.condeferrable AND NOT c.condeferred
 AND pg_get_constraintdef(c.oid)=('PRIMARY KEY (id)')
 AND (c.contype NOT IN ('p','u') OR EXISTS (
   SELECT 1 FROM pg_index i WHERE i.indexrelid=c.conindid
   AND i.indisvalid AND i.indisready AND i.indislive AND i.indimmediate))
 AND NOT EXISTS (SELECT 1 FROM pg_trigger tr
   WHERE tr.tgconstraint=c.oid AND tr.tgenabled <> 'O')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('idx_byod_jobs_zid'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX idx_byod_jobs_zid ON public.byod_import_jobs USING btree (zid)')))) AS catalog_match
UNION ALL
SELECT '000018_add_topics_enabled.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_attribute a
 LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
 WHERE a.attrelid=to_regclass('public.'||('conversations')) AND a.attname=('topics_enabled') AND NOT a.attisdropped
 AND format_type(a.atttypid,a.atttypmod)=('boolean') AND a.attnotnull=(true)
 AND a.attidentity='' AND a.attgenerated=''
 AND pg_get_expr(d.adbin,d.adrelid) IS NOT DISTINCT FROM ('false')))) AS catalog_match
UNION ALL
SELECT '000022_add_poll_timestamp_indexes.sql'::text AS migration, (-- Catalog postconditions only; this file never replays migration DDL.
SELECT (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('votes_created_idx'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX votes_created_idx ON public.votes USING btree (created)')))
 AND (SELECT EXISTS(SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.'||('comments_modified_idx'))
 AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)=('CREATE INDEX comments_modified_idx ON public.comments USING btree (modified)')))) AS catalog_match
), scope AS (
 SELECT to_regclass('public.migrations') IS NULL
    AND to_regclass('public.schema_migrations') IS NULL
    AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relnamespace='public'::regnamespace
      AND (starts_with(relname,'polis_queue_') OR starts_with(relname,'delphi_')))
    AND NOT EXISTS (SELECT 1 FROM pg_proc WHERE pronamespace='public'::regnamespace
      AND (starts_with(proname,'pq_') OR starts_with(proname,'pd_'))) AS initial_state
), authority AS (
 SELECT
   has_database_privilege(current_user,current_database(),'TEMP')
     AND has_schema_privilege(current_user,'public','USAGE')
     AND has_schema_privilege(current_user,'public','CREATE') AS reconcile_authority,
   EXISTS (SELECT 1 FROM pg_roles WHERE rolname=current_user AND (rolsuper OR rolcreaterole)) AS create_roles,
   NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname IN ('polis_queue_owner','polis_queue_executor')) AS queue_roles_absent,
   has_schema_privilege(current_user,'public','USAGE WITH GRANT OPTION')
     AND has_schema_privilege(current_user,'public','CREATE WITH GRANT OPTION') AS schema_grants,
   EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
     WHERE n.nspname='public' AND c.relname='conversations'
     AND has_table_privilege(current_user,c.oid,'SELECT WITH GRANT OPTION')
     AND has_column_privilege(current_user,c.oid,'topic','UPDATE WITH GRANT OPTION')
     AND has_column_privilege(current_user,c.oid,'zid','REFERENCES WITH GRANT OPTION')) AS table_grants
), readiness AS (
 SELECT initial_state AND (SELECT bool_and(catalog_match) FROM checks)
     AND current_setting('server_version_num')::integer >= 170000 AS can_reconcile,
     create_roles AND queue_roles_absent AND schema_grants AND table_grants AS can_provision,
     initial_state, reconcile_authority, create_roles, queue_roles_absent, schema_grants, table_grants
 FROM scope CROSS JOIN authority
), output AS (
 SELECT migration, catalog_match,
   CASE WHEN NOT initial_state THEN 'REVIEW_EXISTING_LEDGER_OR_QUEUE'
        WHEN NOT catalog_match THEN 'CATALOG_MISMATCH'
        WHEN NOT can_reconcile THEN 'BLOCKED_BY_OTHER_CATALOG_CHECK'
        WHEN NOT reconcile_authority THEN 'REVIEW_MIGRATION_SESSION_AUTHORITY'
        ELSE 'WOULD_ADOPT' END AS outcome
 FROM checks CROSS JOIN readiness
 UNION ALL
 SELECT migration, NULL::boolean,
   CASE WHEN NOT can_reconcile THEN 'BLOCKED_RECONCILIATION'
        WHEN NOT reconcile_authority OR NOT can_provision THEN 'REVIEW_MIGRATION_SESSION_AUTHORITY'
        ELSE 'WOULD_APPLY' END
 FROM (VALUES ('000019_create_polis_queue.sql'),('000023_create_delphi_foundation.sql'),
              ('000024_create_polis_queue_large_class.sql')) p(migration) CROSS JOIN readiness
 UNION ALL
 SELECT migration, NULL::boolean, 'OUTSIDE_RELEASE'
 FROM (VALUES ('000020'),('000021'),('000025'),('000026')) p(migration)
)
SELECT migration, catalog_match, outcome FROM output ORDER BY migration;
ROLLBACK;
