// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Do not delete empty comment line below. It's required to mitigate a bug.
// See: https://github.com/box/mojito/issues/588

//

module.exports = {
  "agree": "Enig",
  "disagree": "Uenig",
  "pass": "Spring over / Usikker",
  "modOffTopic": "Off topic",
  "modImportant": "Vigtigt",
  "modSubmitInitialState": "Spring over (ingen af ovenstående), næste kommentar",
  "modSubmit": "Færdig, næste kommentar",

  "x_wrote": "skrev:",
  "x_tweeted": "tweetede:",
  "comments_remaining": "{{num_comments}} tilbage",
  "comments_remaining2": "{{num_comments}} tilbage",
  "group_123": "Gruppe:",
  "comment_123": "Kommentar:",
  "majorityOpinion": "Flertallets mening",
  "majorityOpinionShort": "Flertallet",
  "privacy": "Privatliv",
  "TOS": "Vilkår for brug",
  "writePrompt": "Del dit perspektiv...",
  "anonPerson": "Anonym",
  "helpWhatAmISeeingTitle": "Hvad er det jeg ser?",
  "helpWhatAmISeeing": "Personer der stemmer tilsvarende grupperes. Klik på en gruppe for at se de holdninger de deler.",
  "helpWhatDoIDoTitle": " Hvad skal jeg gøre?",
  "helpWhatDoIDo": "Stem på andres kommentaterer ved at klikke 'enig' eller 'uenig. Skriv en kommentar (hold hver kommentar til én idé). Inviter andre venner til samtalen!",
  "writeCommentHelpText": "Hvis dit perspektiv ikke er repræsenteret, så <strong>skriv</strong> en kommentar!</i>",
  "helpWriteListIntro": "Hvad er en god kommentar?",
  "helpWriteListStandalone": "Enkeltstående idé",
  "helpWriteListRaisNew": "Rejser nye perspektiver, erfaringer eller problemstillinger",
  "helpWriteListShort": "Klar og præcis (begrænset til 140 tegn)",
  "heresHowGroupVoted": "Her er hvordan gruppe {{GROUP_NUMBER}} stemte:",
  "x_people": "{{x}} personer",
  "acrossAllPtpts": "På tværs af alle deltagere:",
  "xPtptsSawThisComment": " så denne kommentar",
  "xOfThoseAgreed": "af disse deltagere var enige",
  "xOfthoseDisagreed": "af disse deltagere var uenige",
  "opinionGroups": "Meningsgrupper",
  "pctAgreed": "{{pct}}% var enige",
  "pctDisagreed": "{{pct}}% var uenige",
  "pctAgreedLong": "{{pct}}% af alle der stemte på kommentaren {{comment_id}} var enige.",
  "pctAgreedOfGroup": "{{pct}}% af gruppe {{group}} var enige",
  "pctDisagreedOfGroup": "{{pct}}% af gruppe {{group}} var uenige",
  "pctDisagreedLong": "{{pct}}% af alle der stemte på kommentaren {{comment_id}} var uenige.",
  "pctAgreedOfGroupLong": "{{pct}}% af gruppen {{group}} som stemte på kommentaren {{comment_id}} var enige.",
  "pctDisagreedOfGroupLong": "{{pct}}% af gruppen {{group}}som stemte på kommentaren {{comment_id}} var uenige.",
  "commentSent": "Kommentar sendt! Andre deltagere kan se din kommentar og være enig eller uenig i den.",
  "commentSendFailed": "Der opstod et problem ved afsendense af kommentaren.",
  "commentSendFailedEmpty": "Der opstod et problem ved afsendense af kommentaren - bør ikke være tom.",
  "commentSendFailedTooLong": "Der opstod et problem ved afsendense af kommentaren - den er for lang.",
  "commentSendFailedDuplicate": "Der opstod et problem ved afsendense af kommentaren - der eksisterer en identisk.",
  "commentErrorDuplicate": "Kopi! Kommentaren eksisterer allerede.",
  "commentErrorConversationClosed": "Denne samtale er lukket. Der kan ikke afgives flere kommentarer.",
  "commentIsEmpty": "Kommentar er tom",
  "commentIsTooLong": "Kommentar er for lang",
  "hereIsNextStatement": "Succes. Naviger op for at se næste kommentar.",

  "connectFacebook": "Forbind Facebook",
  "connectTwitter": "Forbind Twitter",
  "connectToPostPrompt": "Forbind en identitet for at kommentere. Vi poster ikke på din tidslinje.",
  "connectToVotePrompt": "orbind en identitet for at kommentere. Vi poster ikke på din tidslinje.",
  "commentWritingTipsHintsHeader": "Råd til at skrive kommentarer",
  "tipCharLimit": "Kommentarer er begrænset til {{char_limit}} tegn.",
  "tipCommentsRandom": "Kommentarer vises tilfældigt. Du svarer ikke direkte til nogen.",
  "tipOneIdea": "Bryd længere kommentarer op i flere. Det gør det nemmere for andre at stemme på din kommentar.",
  "tipNoQuestions": "Kommentarer bør udtrykke holdninger i stedet for spørgsmål. Deltagere skal enten være enige eller uenige i dine kommentarer.",
  "commentTooLongByChars": "Længde på kommentar overskrider grænsen med {{CHARACTERS_COUNT}} tegn.",
  "submitComment": "Indsend",
  "tipStarred": "Markeret som vigtig.",
  "participantHelpWelcomeText": "Velkommen til en ny slags samtale - <span style='font-weight: 700;'>stem</span> på personers holdninger og <span style='font-weight: 700;'>bidrag</span> med dine egne.",
  "participantHelpGroupsText": "Personer der stemmer lig hinanden <span style='font-weight: 700;'>grupperes.</span> Klik på en gruppe for at se, hvilke synspunkter de deler <a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...mere</a>",
  "participantHelpGroupsNotYetText": "Visualisering kan først ses når 7 deltagere har stemt",
  "helpWhatAreGroupsDetail": "<p>Du har sikkert set 'anbefalede produkter' på Amazon eller 'anbefalede film' på Netflix. Tjenesterne grupperer dig med personer, der køber eller ser lignende ting, så du får anbefalet, hvad de købte eller så.</p> <p> Når du stemmer på en kommentar, bliver du grupperet med personer der stemte ligesom dig. Du kan se grupperne her. Hver gruppe er sammensat af personer med lignende holdninger. Der kan være fascinerende indsigt i dette - gå på opdagelse og se, hvad der gør grupperne unikke. </p>",
  "socialConnectPrompt": "Du kan forbinde for at se venner og personer du følger i visualiseringen.",
  "connectFbButton": "Forbind med Facebook",
  "connectTwButton": "Forbind med Twitter",
  "polis_err_reg_fb_verification_email_sent": "Check din email for et link, så vi kan verificere dig.",
  "polis_err_reg_fb_verification_noemail_unverified": "Din Facebook-konto er ikke verificeret, Verificer den og kom tilbage..",
  "showTranslationButton": "Aktiver oversættelse",
  "hideTranslationButton": "Deaktiver oversættelse",

  "notificationsAlreadySubscribed": "Du abonnerer på opdateringer for denne samtale.",
  "notificationsGetNotified": "Få notifikationer når der kommer flere kommentarer:",
  "notificationsEnterEmail": "Indtast din email og få besked, når der kommer flere kommentarer:",
  "notificationsSubscribeButton": "Abonner",
  "noCommentsYet": "Der er endnu ingen kommentarer.",
  "noCommentsYetSoWrite": "Start samtalen ved at tilføje en kommentar.",
  "noCommentsYetSoInvite": "Start samtalen ved at inviterer flere deltagere eller tilføj en kommentar.",
  "noCommentsYouVotedOnAll": "Du har stemt på alle kommentarer.",
  "noCommentsTryWritingOne": "Hvis du har noget at tilføje, så prøv at skrive en kommentar.",
  "convIsClosed": "Samtalen er lukket.",
  "noMoreVotingAllowed": "Det er ikke muligt at stemme mere.",
};