// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

module.exports = {
  "agree": "Agree",
  "disagree": "Disagree",
  "pass": "Pass / Unsure",

  "importantCheckbox": "This comment is important",
  "howImportantPrompt": "How important is this statement?",
  "howImportantLow": "Low",
  "howImportantMedium": "Medium",
  "howImportantHigh": "High",

  "modSpam": "Spam",
  "modOffTopic": "Off Topic",
  "modImportant": "Important",
  "modSubmitInitialState": "Skip (none of the above), next statement",
  "modSubmit": "Done, next statement",

  "x_wrote": "wrote:",
  "x_tweeted": "tweeted:",
  "comments_remaining": "{{num_comments}} remaining",
  "comments_remaining2": "{{num_comments}} remaining statements",
  "group_123": "Group:",
  "comment_123": "Statement:",
  "majorityOpinion": "Majority Opinion",
  "majorityOpinionShort": "Majority",
  "info": "Info",
  "addPolisToYourSite": "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>",
  "privacy": "Privacy",
  "TOS": "TOS",
  "writePrompt": "Share your perspective...",
  "anonPerson": "Anonymous",
  "helpWhatAmISeeingTitle": "What am I seeing?",
  "helpWhatAmISeeing": "People who vote similarly are grouped. Click a group to see which viewpoints they share.",
  "helpWhatDoIDoTitle": " What do I do?",
  "helpWhatDoIDo": "Vote on other people's statements by clicking 'agree' or 'disagree'. Write a statement (keep each to a single idea). Invite your friends to the conversation!",
  "writeCommentHelpText": "Are your perspectives or experiences missing from the conversation? If so, <b>add them</b> in the box below.",
  "helpWriteListIntro": "What makes a good statement?",
  "helpWriteListStandalone": "Stand alone idea",
  "helpWriteListRaisNew": "Raise new perspectives, experiences or issues",
  "helpWriteListShort": "Clear & concise (limited to 140 characters)",
  "heresHowGroupVoted": "Here's how Group {{GROUP_NUMBER}} voted:",
  "one_person": "{{x}} person",
  "x_people": "{{x}} people",
  "acrossAllPtpts": "Across all participants:",
  "xPtptsSawThisComment": " saw this statement",
  "xOfThoseAgreed": "of those participants agreed",
  "xOfthoseDisagreed": "of those participants disagreed",
  "opinionGroups": "Opinion Groups",
  "topComments": "Top Statements",
  "divisiveComments": "Divisive Statements",
  "pctAgreed": "{{pct}}% Agreed",
  "pctDisagreed": "{{pct}}% Disagreed",
  "pctAgreedLong": "{{pct}}% of everyone who voted on statement {{comment_id}} agreed.",
  "pctAgreedOfGroup": "{{pct}}% of Group {{group}} Agreed",
  "pctDisagreedOfGroup": "{{pct}}% of Group {{group}} Disagreed",
  "pctDisagreedLong": "{{pct}}% of everyone who voted on statement {{comment_id}} disagreed.",
  "pctAgreedOfGroupLong": "{{pct}}% of those in group {{group}} who voted on statement {{comment_id}} agreed.",
  "pctDisagreedOfGroupLong": "{{pct}}% of those in group {{group}} who voted on statement {{comment_id}} disagreed.",
  "commentSent": "Statement submitted! Only other participants will see your statement and agree or disagree.",
  "commentSendFailed": "There was an error submitting your statement.",
  "commentSendFailedEmpty": "There was an error submitting your statement - Statement should not be empty.",
  "commentSendFailedTooLong": "There was an error submitting your statement - Statement is too long.",
  "commentSendFailedDuplicate": "There was an error submitting your statement - An identical statement already exists.",
  "commentErrorDuplicate": "Duplicate! That statement already exists.",
  "commentErrorConversationClosed": "This conversation is closed. No further statements can be submitted.",
  "commentIsEmpty": "Statement is empty",
  "commentIsTooLong": "Statement is too long",
  "hereIsNextStatement": "Vote success. Navigate up to see the next statement.",

  "connectFacebook": "Connect Facebook",
  "connectTwitter": "Connect Twitter",
  "connectToPostPrompt": "Connect an identity to submit a statement. We will not post to your timeline.",
  "connectToVotePrompt": "Connect an identity to vote. We will not post to your timeline.",
  "tip": "Tip:",
  "commentWritingTipsHintsHeader": "Tips for writing statements",
  "tipCharLimit": "Statements are limited to {{char_limit}} characters.",
  "tipCommentsRandom": "Please remember, statements are displayed randomly and you are not replying directly to other participants' statements.",
  "tipOneIdea": "Break up long statements that contain multiple ideas. This makes it easier for others to vote on your statement.",
  "tipNoQuestions": "Statements should not be in the form of a question. Participants will agree or disagree with the statements you make.",
  "commentTooLongByChars": "Statement length limit exceeded by {{CHARACTERS_COUNT}} characters.",
  "notSentSinceDemo": "(not really, this is a demo)",
  "submitComment": "Submit",
  "tipStarred": "Marked as important.",
  "participantHelpWelcomeText": "Welcome to a new kind of conversation - <em>vote</em> on other people's statements.",
  "participantHelpGroupsText": "People who vote similarly <span style='font-weight: 700;'>are grouped.</span> Click a group to see which viewpoints they share. <a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...more</a>",
  "participantHelpGroupsNotYetText": "The visualization will appear once 7 participants have begun voting",
  "helpWhatAreGroupsDetail": "<p>You've probably seen 'recommended products' on Amazon, or 'recommended movies' on Netflix. Each of those services uses statistics to group the user with people who buy and watch similar things, then show them things that those people bought or watched.</p> <p> When a user votes on statements, they are grouped with people who voted like they did! You can see those groups below. Each is made up of people who have similar opinions. There are fascinating insights to discover in each conversation. Go ahead - click a group to see what brought them together and what makes them unique! </p>",
  "socialConnectPrompt": "Optionally connect to see friends and people you follow in the visualization.",
  "connectFbButton": "Connect with Facebook",
  "connectTwButton": "Connect with Twitter",
  "polis_err_reg_fb_verification_email_sent": "Please check your email for a verification link, then return here to continue.",
  "polis_err_reg_fb_verification_noemail_unverified": "Your Facebook account is unverified. Please verify your email address with Facebook, then return here to continue.",
  "showTranslationButton": "Activate third-party translation",
  "hideTranslationButton": "Deactivate Translation",
  "thirdPartyTranslationDisclaimer": "Translation provided by a third party",

  "notificationsAlreadySubscribed": "You are subscribed to updates for this conversation.",
  "notificationsGetNotified": "Get notified when more statements arrive:",
  "notificationsEnterEmail": "Enter your email address to get notified when more statements arrive:",
  "labelEmail": "Email",
  "notificationsSubscribeButton": "Subscribe",
  "notificationsSubscribeErrorAlert": "Error subscribing",
  "noCommentsYet": "There aren't any statements yet.",
  "noCommentsYetSoWrite": "Get this conversation started by adding a statement.",
  "noCommentsYetSoInvite": "Get this conversation started by inviting more participants, or add a statement.",
  "noCommentsYouVotedOnAll": "You've voted on all the statements.",
  "noCommentsTryWritingOne": "If you have something to add, try writing your own statement.",
  "convIsClosed": "This conversation is closed.",
  "noMoreVotingAllowed": "No further voting is allowed.",


  "topic_good_01": "What should we do about the pingpong room?",
  "topic_good_01_reason": "open ended, anyone can have an opinion on answers to this question",
  "topic_good_02": "What do you think about the new proposal?",
  "topic_good_02_reason": "open ended, anyone can have an opinion on answers to this question",
  "topic_good_03": "Can you think of anything that's slowing productivity?",

  "topic_bad_01": "everyone report your launch readiness",
  "topic_bad_01_reason": "people from various teams will be voting on the responses, but may not have enough knowledge to vote confidently.",
  "topic_bad_02": "what are our launch blockers?",
  "topic_bad_02_reason": "",
};
