// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Do not delete empty comment line below. It's required to mitigate a bug.
// See: https://github.com/box/mojito/issues/588

//

module.exports = {
  "agree": "Acordar",
  "disagree": "Discrepar",
  "pass": "Pasar / Indeciso",

  "modSpam": "Spam",
  "modOffTopic": "Fuera de Contexto",
  "modImportant": "Importante",
  "modSubmitInitialState": "Saltártelo (ninguna de las anteriores), próximo comentario",
  "modSubmit": "Terminado, próximo comentario",

  "x_wrote": "escribió:",
  "x_tweeted": "tuiteó:",
  "comments_remaining": "{{num_comments}} restante",
  "comments_remaining2": "{{num_comments}} comentarios restantes",
  "group_123": "Grupo:",
  "comment_123": "Comentario:",
  "majorityOpinion": "Opinión de la Mayoría",
  "majorityOpinionShort": "Mayoría",
  "info": "Info",
  "addPolisToYourSite": "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>",
  "privacy": "Privacidad",
  "TOS": "Condiciones de Servicio",
  "writePrompt": "Compartir su perspectiva...",
  "anonPerson": "Anónimo",
  "helpWhatAmISeeingTitle": "¿Qué es lo que veo?",
  "helpWhatAmISeeing": "Se agrupa la gente que vota de manera similar. Haz clic en un grupo para ver sus puntos de vista compartidos.",
  "helpWhatDoIDoTitle": " ¿Qué hago?",
  "helpWhatDoIDo": "Haz clic en 'Acordar' o 'Discrepar' para votar en comentarios ajenos. Escribe un comentario (manténgalo a una sola idea). Invita a tus amigos a la discusión!",
  "writeCommentHelpText": "Si su perspectiva no está representada ya, <strong>escribe</strong> un comentario!",
  "helpWriteListIntro": "Qué hace que un comentario sea exitoso?",
  "helpWriteListStandalone": "Idea única",
  "helpWriteListRaisNew": "Plantear nuevas perspectivas, experiencias o problemas",
  "helpWriteListShort": "Claro y conciso (límite - 140 carácteres)",
  "heresHowGroupVoted": "Aquí está como votó el Grupo {{GROUP_NUMBER}}:",
  "one_person": "{{x}} persona",
  "x_people": "{{x}} personas",
  "acrossAllPtpts": "Por todos los participantes:",
  "xPtptsSawThisComment": " vio este comentario",
  "xOfThoseAgreed": "de esos participantes acordaron",
  "xOfthoseDisagreed": "de esos participantes discreparon",
  "opinionGroups": "Grupos de Opinión",
  "pctAgreed": "{{pct}}% Acordaron",
  "pctDisagreed": "{{pct}}% Discreparon",
  "pctAgreedLong": "{{pct}}% de groupo que acordaron con el comentario {{comment_id}}.",
  "pctAgreedOfGroup": "{{pct}}% de Grupo {{group}} Acordaron",
  "pctDisagreedOfGroup": "{{pct}}% de Grupo {{group}} Discreparon",
  "pctDisagreedLong": "{{pct}}% de todos que votaron {{comment_id}} discreparon.",
  "pctAgreedOfGroupLong": "{{pct}}% de los del group {{group}} que votaron en el comentario {{comment_id}} acordaron.",
  "pctDisagreedOfGroupLong": "{{pct}}% de los en el {{group}} que votaron por el comentario {{comment_id}} discreparon.",
  "commentSent": "Comentario Enviado! Otros participantes verán tu comentario y acordarán or discreparán con él.",
  "commentSendFailed": "Hubo un error procesando su comentario.",
  "commentSendFailedEmpty": "Hubo un error procesando su comentario - Comentario incompleto.",
  "commentSendFailedTooLong": "Hubo un error procesando su comentario - Comentario es demasiado largo.",
  "commentSendFailedDuplicate": "Hubo un error procesando su comentario. Este comentario ya existe.",
  "commentErrorDuplicate": "!Duplicado! Este comentario ya existe.",
  "commentErrorConversationClosed": "Esta conversación está cerrada. No puede recibir más comentarios.d.",
  "commentIsEmpty": "Comentario incompleto",
  "commentIsTooLong": "Comentario es demasiado largo",
  "hereIsNextStatement": "Voto procesado. Navigue arriba para ver el comentario próximo.",

  "connectFacebook": "Conecta a Facebook",
  "connectTwitter": "Conecta a Twitter",
  "connectToPostPrompt": "Conecta a una identidad para comentar. No publicaremos tu línea de tiempo.",
  "connectToVotePrompt": "Conecta a una identidad para votar. No publicaremos tu línea de tiempo.",
  "commentWritingTipsHintsHeader": "Cómo escribir un comentario",
  "tipCharLimit": "Comentarios son limitados a {{char_limit}} carácteres.",
  "tipCommentsRandom": "Los comentarios se exponen aleatoriamente. No puedes responder directamente a una persona.",
  "tipOneIdea": "Desagrega los comentarios largos que contienen varias ideas. Así será más fácil que los demás voten en su comentario.",
  "tipNoQuestions": "Los comentarios deben ser declaraciones en vez de preguntas. Los participantes acordarán o discreparán con lo que declares.",
  "commentTooLongByChars": "Excedió el límite de carácters por {{CHARACTERS_COUNT}} carácters.",
  "notSentSinceDemo": "(en realidad no, este es un demo)",
  "submitComment": "Enviar",
  "tipStarred": "Marcado como importante.",
  "participantHelpWelcomeText": "Bienvenido a un nuevo tipo de discusión - <span style='font-weight: 700;'>vota</span> en las opiniones de los demás y <span style='font-weight: 700;'>contribuye</span> opiniones propias.",
  "participantHelpGroupsText": "<span style='font-weight: 700;'>Se agrupa</span> toda la gente que vota de manera similar. Haz clic en un grupo para ver los puntos de vista que comparten sus miembros <a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...más</a>",
  "participantHelpGroupsNotYetText": "La visualización aparecerá cuando 7 participantes votan",
  "helpWhatAreGroupsDetail": "<p>Probablemente has visto los 'productos recomendados' en Amazon, o las 'películas recomendadas' en Netflix. Esos servicios usan la estadística para agruparte con la demás gente que compra y mira cosas similares y entonces mostrarte cosas compradas o miradas por ellos.</p> <p> Cuando votas en un comentario de Pol.is, ¡serás agrupado con gente que ha votado de manera similar! Aquí abajo puedes explorar los grupos. Cada grupo se compone de gente con opiniones similares. Cada conversación tiene percepciones nuevas y fascinantes para descubrir. ¡Dale! - ¡haz clic en un grupo para ver cuáles opiniones lo unen y cuáles lo hace único! </p>",
  "socialConnectPrompt": "Conéctate para ver tus amigos y la gente que sigues en la visualización.",
  "connectFbButton": "Conecta con Facebook",
  "connectTwButton": "Conecta con Twitter",
  "polis_err_reg_fb_verification_email_sent": "Por favor, chequea tu email para el enlace de verificación, y entonces regresa aquí para continuar.",
  "polis_err_reg_fb_verification_noemail_unverified": "Tu cuenta de Facebook no está verificada. Por favor, verifica tu email con Facebook, y entonces regresa aquí para continuar.",
  "showTranslationButton": "Active Traducción",
  "hideTranslationButton": "Deactive el servicio traducción",
  "thirdPartyTranslationDisclaimer": "Traducción proporcionada por un tercero",

  "notificationsAlreadySubscribed": "Está suscrito para recibir actualizaciones a esta conversación.",
  "notificationsGetNotified": "Recibe notificaciones cuando comentarios nuevos aparecen:",
  "notificationsEnterEmail": "Ingrese su dirección de email para recibir notificaciones cuando lleguen más comentarios:",
  "labelEmail": "Email",
  "notificationsSubscribeButton": "Subscribe",
  "notificationsSubscribeErrorAlert": "Error al suscribirse",
  "noCommentsYet": "Aún no hay comentarios",
  "noCommentsYetSoWrite": "Agregue un comentario para comenzar esta conversación.",
  "noCommentsYetSoInvite": "Comience esta conversación - invite más participantes o agregue un comentario.",
  "noCommentsYouVotedOnAll": "Yo votó para todos los comentarios.",
  "noCommentsTryWritingOne": "Si tiene algo más para decir, escriba un comentario nuevo.",
  "convIsClosed": "Esta conversación está cerrada",
  "noMoreVotingAllowed": "No puede votar más.",
};