// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

export default {
  "agree": "En accord",
  "disagree": "En désaccord",
  "pass": "Neutre / Incertain",

  "modSpam": "Pourriel",
  "modOffTopic": "Hors sujet",
  "modImportant": "Important",
  "modSubmitInitialState": "Aucune de ces réponses – Passer à la prochaine affirmation",
  "modSubmit": "Terminé – Passer à la prochain affirmation",

  "x_wrote": "a écrit :",
  "x_tweeted": "a publié sur Twitter :",
  "comments_remaining": "Il en reste {{num_comments}}",
  "comments_remaining2": "Il reste {{num_comments}} autres affirmations",
  "group_123": "Groupe :",
  "comment_123": "Affirmation :",
  "majorityOpinion": "Opinion de la majorité",
  "majorityOpinionShort": "Majorité",
  "info": "Info",
  "addPolisToYourSite": "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>",
  "privacy": "Avis de confidentialité",
  "TOS": "Conditions du service",
  "writePrompt": "Faites connaître votre point de vue...",
  "anonPerson": "Anonyme",
  "helpWhatAmISeeingTitle": "Que suis-je en train de voir?",
  "helpWhatAmISeeing": "Toutes les personnes qui ont voté de façon semblable sont regroupées. Cliquez sur un groupe pour connaître le point de vue des membres.",
  "helpWhatDoIDoTitle": "Que dois-je faire?",
  "helpWhatDoIDo": "Votez sur les affirmations des autres participants. Pour ce faire, cliquez sur « En accord » ou « En désaccord », puis rédigez une affirmation (une idée = une affirmation). Invitez vos amis à participer à la conversation!",
  "writeCommentHelpText": "Vous souhaitez faire connaître votre point de vue ou partager votre expérience dans une conversation? Il vous suffit de <b>les ajouter</b> dans le champ ci-dessous.",
  "heresHowGroupVoted": "Voici comment le groupe {{GROUP_NUMBER}} a voté :",
  "one_person": "{{x}} personne",
  "x_people": "{{x}} personnes",
  "acrossAllPtpts": "Parmi tous les participants :",
  "xPtptsSawThisComment": " ont vu cette affirmation ",
  "xOfThoseAgreed": "d’entre eux sont en accord avec l’affirmation",
  "xOfthoseDisagreed": "d’entre eux sont en désaccord avec l’affirmation",
  "opinionGroups": "Groupes d’opinion",
  "pctAgreed": "{{pct}} % étaient en accord avec l’affirmation",
  "pctDisagreed": "{{pct}} % étaient en désaccord avec l’affirmation",
  "pctAgreedLong": "{{pct}} % des personnes qui ont voté au sujet de l’énoncé {{comment_id}} étaient en accord avec celui-ci.",
  "pctAgreedOfGroup": "{{pct}} % des membres du groupe {{group}} étaient en accord avec l'affirmation",
  "pctDisagreedOfGroup": "{{pct}} % des membres du groupe {{group}} étaient en désaccord avec l’affirmation",
  "pctDisagreedLong": "{{pct}} % des personnes qui ont voté au sujet de l’énoncé {{comment_id}} étaient en désaccord avec celui-ci.",
  "pctAgreedOfGroupLong": "{{pct}} % des membres du groupe {{group}} ayant voté au sujet de l’énoncé {{comment_id}} étaient en accord avec celui-ci.",
  "pctDisagreedOfGroupLong": "{{pct}} % des membres du groupe {{group}} ayant voté au sujet de l’affirmation {{comment_id}} étaient en désaccord avec celui-ci.",
  "commentSent": "Énoncé publié! Les autres participants verront votre publication et indiqueront s’ils sont en accord ou en désaccord avec l’affirmation.",
  "commentSendFailed": "Une erreur est survenue. Impossible de publier l’affirmation.",
  "commentSendFailedEmpty": "Une erreur s’est produite lors de la soumission de votre affirmation - L’affirmation ne devrait pas être vide.",
  "commentSendFailedTooLong":  "Une erreur s’est produite lors de la soumission de votre affirmation – L’affirmation est trop longue ",
  "commentSendFailedDuplicate": "Une erreur s’est produite lors de la soumission de votre affirmation – Une affirmation identique existe déjà.",
  "commentErrorDuplicate": "Une erreur s’est produite lors de la soumission de votre affirmation – Une affirmation identique existe déjà.",
  "commentErrorConversationClosed": "Cette conversation est fermée. Impossible de publier de nouvelles affirmations.",
  "commentIsEmpty": "L’affirmation est vide.",
  "commentIsTooLong": "L’affirmation est trop longue.",
  "hereIsNextStatement": "Vote effectué avec succès. Naviguez vers le haut pour voir l’affirmation suivante.",

  "connectFacebook": "Connexion à Facebook",
  "connectTwitter": "Connexion à Twitter",
  "connectToPostPrompt": "Connectez-vous pour publier une affirmation. Nous ne publierons pas votre journal.",
  "connectToVotePrompt": "Connectez-vous pour voter. Nous ne publierons pas votre journal.",
  "tip": "Conseil :",
  "commentWritingTipsHintsHeader": "Conseils pour rédiger une affirmation",
  "tipCharLimit": "Les énoncés doivent compter au plus {{char_limit}} caractères.",
  "tipCommentsRandom": "Gardez à l’esprit que les énoncés sont affichés de façon aléatoire et que vous ne répondez pas directement à l'affirmation d'un autre participant.",
  "helpWriteListIntro": "Une bonne affirmation:",
  "helpWriteListStandalone": "présente une seule idée;",
  "helpWriteListRaisNew": "présente un nouveau point de vue, de nouvelles expériences ou de nouveaux enjeux;",
  "helpWriteListShort": "est claire et concise (compte au plus 140 caractères)",
  "heresHowGroupVoted": "Here's how Group {{GROUP_NUMBER}} voted:",
  "tipOneIdea": "Subdivisez en plusieurs affirmations les affirmations trop longues qui traitent de plus d’une idée. Cela facilitera le vote.",
  "tipNoQuestions": "Une affirmation ne doit pas être présentée sous la forme d’une question. Les participants indiqueront s’ils sont en accord ou en désaccord avec votre affirmation.",
  "commentTooLongByChars": "L’affirmation compte {{CHARACTERS_COUNT}} caractères en trop.",
  "notSentSinceDemo": "(Ceci est une démonstration)",
  "submitComment": "Publier",
  "tipStarred": "Marqué comme étant important.",
  "participantHelpWelcomeText": "Bienvenue à un nouveau mode de conversation : <em>votez</em> sur les affirmations des autres participants ",
  "participantHelpGroupsText": "Toutes les personnes qui ont voté de façon semblable <span style='font-weight: 700;'>sont regroupées.</span> Cliquez sur un groupe pour connaître le point de vue des membres.<a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...(plus)</a>",
  "participantHelpGroupsNotYetText": "Le volet de visualisation s’affichera une fois qu’au moins 7 participants auront voté. ",
  "helpWhatAreGroupsDetail": "<p>Vous avez probablement déjà consulté la section sur les produits recommandés d’Amazon, ou celle des films recommandés sur Netflix. Chacun de ces services se fonde sur les statistiques pour regrouper l’utilisateur avec d’autres qui achètent des produits ou regardent des films similaires, puis présente les articles que ces autres utilisateurs ont acheté ou regardé. </p> <p> Lorsqu’un participant vote au sujet d’une affirmation, il est regroupé avec d’autres participants qui ont voté comme lui! Vous pouvez voir ci-dessous les groupes ainsi formés. Chacun est constitué de participants ayant des opinions semblables. Chaque conversation permet de faire des découvertes fascinantes. Allez-y! Cliquez sur un groupe pour voir ce que les membres ont en commun et ce qui les distingue des autres! </p>",
  "socialConnectPrompt": "Vous pouvez aussi vous connecter au forum pour voir vos amis et les personnes que vous suivez dans le volet de visualisation.",
  "connectFbButton": "Connectez-vous avec votre compte Facebook",
  "connectTwButton": "Connectez-vous avec votre compte Twitter",
  "polis_err_reg_fb_verification_email_sent": "Veuillez vérifier votre boîte de courriel et cliquez sur le lien de vérification. Revenez ensuite ici pour continuer.",
  "polis_err_reg_fb_verification_noemail_unverified": "Votre compte Facebook n’a pas été confirmé. Veuillez vérifier l’adresse de courriel que vous utilisez avec votre compte Facebook, puis revenez ici pour continuer.",
  "showTranslationButton": "Activer la traduction par un tiers",
  "hideTranslationButton": "Désactiver le service de traduction",

  "thirdPartyTranslationDisclaimer": "Traduction fournie par un tiers",

  "notificationsAlreadySubscribed": "Vous êtes abonné aux mises jour de cette conversation.",
  "notificationsGetNotified": "Recevez un avis lorsque de nouvelles affirmations sont publiées :",
  "notificationsEnterEmail": "Saisissez votre adresse de courriel pour recevoir un message lorsque de nouvelles affirmations sont publiées :",
  "labelEmail": "Adresse",
  "notificationsSubscribeButton": "M’abonner",
  "noCommentsYet": "Aucune affirmation n’a encore été publiée.",
  "noCommentsYetSoWrite": "Lancez la conversation en publiant une affirmation.",
  "noCommentsYetSoInvite": "Lancez la conversation en invitant d’autres participants ou en ajoutant une affirmation.",
  "noCommentsYouVotedOnAll": "Vous avez voté sur toutes les affirmations.",
  "noCommentsTryWritingOne": "Si vous souhaitez ajouter quelque chose, rédigez votre propre affirmation.",
  "convIsClosed": "Cette conversation est fermée.",
  "noMoreVotingAllowed": "Aucun autre vote n’est autorisé.",
}
