// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

module.exports = {
  "agree": "Son d'accordo",
  "disagree": "Non la penso così",
  "pass": "Passo / Non so",

  "modSpam": "Spam",
  "modOffTopic": "Off Topic / Fuori Tema",
  "modImportant": "Importante",
  "modSubmitInitialState": "Salta / nessuna risposta va bene / passa al prossimo",
  "modSubmit": "Ok, passa al prossimo",

  "x_wrote": "dice:",
  "x_tweeted": "twitta:",
  "group_123": "Gruppo:",
  "majorityOpinion": "Opinione della maggioranza",
  "majorityOpinionShort": "Maggioranza",
  "info": "Info",
  "addPolisToYourSite": "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>",
  "privacy": "Privacy",
  "TOS": "TOS",
  "writePrompt": "Condividi il tuo punto di vista...",
  "anonPerson": "Anonimo",
  "helpWhatAmISeeingTitle": "Cos'è questo?",
  "helpWhatAmISeeing": "Chi vota in modo simile viene aggregato. Clicca su un gruppo per conoscere quali punti di vista vengono condivisi.",
  "helpWhatDoIDoTitle": " Che faccio?",
  "helpWhatDoIDo": "Vota sui commenti degli altri, cliccando su \"Son d'accordo\" o \"Non la penso così.\". Scrivi un commento (uno per ogni singola idea). Invita i tuoi amici alla discussione!",
  "writeCommentHelpText": "Se il tuo punto di vista manca, <strong>scrivi</strong> un commento!</i>",
  "heresHowGroupVoted": "Ecco come il Gruppo {{GROUP_NUMBER}} ha votato:",
  "one_person": "{{x}} persona",
  "x_people": "{{x}} persone",
  "acrossAllPtpts": "Tra tutti i partecipanti:",
  "xPtptsSawThisComment": " ha/hanno visto questo commento.",
  "xOfThoseAgreed": "di quei partecipanti è d'accordo",
  "xOfthoseDisagreed": "di quei partecipanti non la pensa così",
  "opinionGroups": "Gruppi di opinione",
  "pctAgreed": "{{pct}}% Son d'accordo",
  "pctDisagreed": "{{pct}}% Non la pensano così.",
  "pctAgreedOfGroup": "{{pct}}% del Gruppo {{group}} è d'accordo",
  "pctDisagreedOfGroup": "{{pct}}% del Gruppo {{group}} non la pensa così",
  "commentSent": "Commento Inviato! Altri partecipanti vedranno il tuo commento e saranno d'accordo o meno.",
  "connectFacebook": "Collegati tramite Facebook",
  "connectTwitter": "Collegati tramite Twitter",
  "connectToPostPrompt": "Collega un identità al commento. Non posteremo nulla sul tuo profilo.",
  "tip": "Attenzione:",
  "tipCommentsRandom": "I commenti vengono mostrati casualmente. Non stai rispondendo a nessuno.",
  "tipOneIdea": "Spezza i commenti lunghi quando essi contengono più idee. Questo renderà più facile per gli altri votare sul tuo commento.",
  "tipNoQuestions": "I commenti dovrebbero contenere affermazioni ed evitare di avere la forma di una domanda. I partecipanti saranno d'accordo con i tuoi commenti singoli o la penseranno diversamente.",
  "notSentSinceDemo": "(non davvero, questa è solo una demo)",
  "submitComment": "Invia",
  "tipStarred": "Segnato come importante.",
  "participantHelpWelcomeText": "Benvenuti a un nuovo tipo di discussione - <span style='font-weight: 700;'>votate</span> sulle opinioni della gente o <span style='font-weight: 700;'>controbuite</span> alla vostra.",
  "participantHelpGroupsText": "Chi vota in modo simile <span style='font-weight: 700;'>viene aggregato.</span> Clicca su un gruppo per conoscere quali punti di vista vengono condivisi.<a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...continua</a>",
  "helpWhatAreGroupsDetail": "<p>Avrai visto le raccomandazioni di Amazon sui prodotti o di Netflix sui film o le serie. Ognuno di quei servizi usa le statistiche per unirti a gruppi che comprano o guardano cose simili per poi farti vedere quali cose quelle persone hanno guardato o ascoltato.</p> <p> Quando voti o commenti, vieni messo insieme alle persone che votano no come hai fatto tu! Puoi vedere quei gruppi qui sotto. Ognuno è fatto di persone che hanno opzioni simili. Ci sono alcuni insight molto interessanti da scoprire in ogni conversazione. Vai avanti! Clicca su un gruppo e scopri quali punti di vista sono condivisi e cosa hanno di unico! </p>",
  "socialConnectPrompt": "Collegati per vedere le persone e gli amici che segui nella visualizzazione.",
  "connectFbButton": "Collegati tramite Facebook",
  "connectTwButton": "Collegati tramite Twitter",
  "polis_err_reg_fb_verification_email_sent": "Per favore, controlla la mail e cerca il link di attivazione, poi continua da qui.",
  "polis_err_reg_fb_verification_noemail_unverified": "Il tuo account Facebook non è verificato. Per favore verifica il tuo indirizzo mail di Facebook, poi torna qui per proseguire.",
};
