// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY. without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>,

module.exports = {
  "agree": "Akkoord",
  "disagree": "Niet akkoord",
  "pass": "Pass / onzeke",

  "modSpam": "Spam",
  "modOffTopic": "Off Topic",
  "modImportant": "Belangrijk",
  "modSubmitInitialState": "Overslaan (geen enkel van bovenstaande), volgende reactie",
  "modSubmit": "Klaar, ga naar volgende reactie",

  "x_wrote": "schreef:",
  "x_tweeted": "tweette:",
  "comments_remaining": "{{num_comments}} overblijvend",
  "comments_remaining2": "{{num_comments}} resterende reacties",
  "group_123": "Groep:",
  "comment_123": "Reactie:",
  "majorityOpinion": "Meerderheidsmening",
  "majorityOpinionShort": "Meerderheid",
  "info": "Info",
  "addPolisToYourSite": "<img style='height: 20px. margin: 0px 4px.' src='{{URL}}'/>",
  "privacy": "Privacy",
  "TOS": "Servicevoorwaarden",
  "writePrompt": "Geef uw mening...",
  "anonPerson": "Anoniem",
  "helpWhatAmISeeingTitle": "Wat ben ik aan het bekijken?",
  "helpWhatAmISeeing": "Mensen met een gelijkaardige mening zijn gegroepeerd. Klik op een groep om hun mening te bekijken.",
  "helpWhatDoIDoTitle": "Wat moet ik doen?",
  "helpWhatDoIDo": "Stem op andere reacties door op 'akkoord' of 'niet akkoord' te klikken. Schrijf een reactie (blijf kort en bondig, één idee per lijn). Nodig vrienden uit om deel te nemen aan de discussie!",
  "writeCommentHelpText": "<strong>schrijf</strong> een reactie indien uw mening niet wordt vertegenwoordigd</i>",
  "helpWriteListIntro": "Wat is een goed voorstel?",
  "helpWriteListStandalone": "Een idee dat op zichzelf staat",
  "helpWriteListRaisNew": "Kaart nieuwe perspectieven, ervaringen of problemen aan",
  "helpWriteListShort": "Duidelijk en beknopt (beperkt tot 140 tekens)",
  "heresHowGroupVoted": "Groep {{GROUP_NUMBER}} stemde:",
  "one_person": "{{x}} persoon",
  "x_people": "{{x}} personen",
  "acrossAllPtpts": "Van alle ondervraagde personen:",
  "xPtptsSawThisComment": " zag deze reactie",
  "xOfThoseAgreed": "van deze deelnemers zijn akkoord",
  "xOfthoseDisagreed": "van deze deelnemers zijn niet akkoord",
  "opinionGroups": "Opiniegroep",
  "pctAgreed": "{{pct}}% zijn akkoord",
  "pctDisagreed": "{{pct}}% zijn niet akkoord",
  "pctAgreedLong": "{{pct}}% van iedereen wie stemden op reactie {{comment_id}} waren akkoord.",
  "pctAgreedOfGroup": "{{pct}}% van Groep {{group}} waren akkoord",
  "pctDisagreedOfGroup": "{{pct}}% van Groep {{group}} waren niet akkoord",
  "pctDisagreedLong": "{{pct}}% van iedereen wie stemden op {{comment_id}} waren niet akkoord.",
  "pctAgreedOfGroupLong": "{{pct}}% van de Groep {{group}} wie stemden op reactie {{comment_id}} waren akkoord.",
  "pctDisagreedOfGroupLong": "{{pct}}% van de Groep {{group}} wie stemden op reactie {{comment_id}} waren niet akkoord.",
  "commentSent": "Reactie verzonden! Andere deelnemers zullen uw reactie zien en akkoord zijn of niet.",
  "commentSendFailed": "Er was een fout bij het toevoegen van uw reactie.",
  "commentErrorDuplicate": "Dubbel! Deze reactie bestaat al.",
  "commentErrorConversationClosed": "Deze conversatie is afgesloten. Reageren is niet meer toegestaan.",
  "commentIsEmpty": "Reactie is leeg",
  "commentIsTooLong": "Reactie is te lang",

  "connectFacebook": "Verbinden met Facebook",
  "connectTwitter": "Verbinden met Twitter",
  "connectToPostPrompt": "Verbindt om te reageren, we zullen niets publiceren op uw tijdlijn.",
  "connectToVotePrompt": "Verbindt om te stemmen, we zullen niets publiceren op uw tijdlijn.",
  "tip": "Tip:",
  "commentWritingTipsHintsHeader": "Tips om reacties te schrijven",
  "tipCharLimit": "De lengte van reacties zijn beperkt to {{char_limit}} tekens.",
  "tipCommentsRandom": "Reacties zijn willekeurig gesorteerd. U bent op niemand aan het reageren",
  "tipOneIdea": "Splits lange reacties op in verschillende ideeën. Dit maakt het makkelijker voor anderen om te stemmen.",
  "tipNoQuestions": "Probeer vragen in uw reacties te vermijden. Deelnemers zullen vervolgens al dan niet akkoord gaan met uw stelling.",
  "commentTooLongByChars": "De lengte van uw reactie werd met  {{CHARACTERS_COUNT}} karakters overschreden.",
  "notSentSinceDemo": "(niet echt, dit is een demo)",
  "submitComment": "Reageer",
  "tipStarred": "Gemarkeerd als belangrijk.",
  "participantHelpWelcomeText": "Welkom bij een nieuwe soort discussie - <span style='font-weight: 700.'>stem</span> op de meningen van personen en draag bij tot het gesprek door zelf te reageren.",
  "participantHelpGroupsText": "Personen die gelijkaardig stemmen <span style='font-weight: 700.'>worden gegroepeerd.</span> Klik op een groep om te zien welk standpunt zij innemen <a style='font-weight: 700. cursor: pointer. text-decoration: underline' id='helpTextGroupsExpand'>...more</a>",
  "participantHelpGroupsNotYetText": "De visualisatie zal verschijnen zodra er 7 personen zijn begonnen met stemmen",
  "helpWhatAreGroupsDetail": "<p>U hebt allicht al 'aanbevolen artikels' op Amazon, of ‘aanbevolen films' op Netflix. Elk van deze services gebruiken statistieken om u te groeperen in bij personen die dezelfde dingen kopen of bekijken, vervolgend wordt er u getoond wat deze mensen kochten of naar welke film ze keken.</p> <p> Wanneer u een stem uitbrengt op een reactie wordt u vervolgens gegroepeerd met mensen die dezelfde stem uitbrachten! Onderaan kan u deze groepen bekijken. Elk van deze groepen bestaan uit personen met dezelfde opinie. Er zijn fascinerende inzichten de ontdekken elk van deze gesprekken. Wacht niet langer – klik op een groep om te zien wat hun bijeen bracht en wat hun uniek maakt! </p>",
  "socialConnectPrompt": "Verbind optioneel om te zien welke vrienden en andere personen uw volgt in de visualisatie.",
  "connectFbButton": "Verbind met Facebook",
  "connectTwButton": "Verbind met Twitter",
  "polis_err_reg_fb_verification_email_sent": "Gelieve uw mail te controleren voor een verificatie link, kom vervolgens terug op deze pagina.",
  "polis_err_reg_fb_verification_noemail_unverified": "Uw Facebook account is niet geverifieerd. Gelieven eerst uw emailadres te controleren bij Facebook, kom vervolgens terug op deze pagina om verder te gaan.",
  "showTranslationButton": "Toon vertalingen",
  "hideTranslationButton": "Verberg vertalingen",

  "notificationsAlreadySubscribed": "U bent al geabonneerd voor updates in dit gesprek.",
  "notificationsGetNotified": "Wordt op de hoogte gebracht zodra er nieuwe reacties verschijnen:",
  "notificationsEnterEmail": "Vul uw emailadres in om op de hoogte gesteld te worden van nieuwe reacties:",
  "labelEmail": "Email",
  "notificationsSubscribeButton": "Abonneer",
  "noCommentsYet": "Er zijn nog geen reacties beschikbaar.",
  "noCommentsYetSoWrite": "Start dit gesprek door als eerste een reactie toe te voegen.",
  "noCommentsYetSoInvite": "Start dit gesprek door nieuwe deelnemers toe te voegen, of voeg als eerste een reactie toe.",
  "noCommentsYouVotedOnAll": "U hebt op alle reacties gestemd.",
  "noCommentsTryWritingOne": "Als u zelf iets wilt toevoegen aan het gesprek, probeer dan een reactie te schrijven.",
  "convIsClosed": "Dit gesprek is afgesloten.",
  "noMoreVotingAllowed": "Er mag niet meer gestemd worden.",

  "topic_good_01": "Wat zouden we kunnen doen met de pingpong kamer?",
  "topic_good_01_reason": "vrijblijvend, iedereen kan een opinie of vraag hebben voor deze vraag",
  "topic_good_02": "Wat denkt u over het nieuwe voorstel?",
  "topic_good_02_reason": "vrijblijvend, iedereen kan een opinie of vraag hebben voor deze vraag",
  "topic_good_03": "Kan u iets bedenken dat de productiviteit vertraagt?",

  "topic_bad_01": "iedereen moet rapporteren over hun vorderingen i.v.m. de start",
  "topic_bad_01_reason": "verschillende mensen van verschillende teams zullen reageren op het antwoord, zij zullen echt niet allemaal de kennis hebben om vastbesloten te kunnen stemmen.",
  "topic_bad_02": "welke factoren remmen onze start af?",
  "topic_bad_02_reason": "",
};
