// Copyright (C) 2012-present, The Authors. This program is free software: you can redistribute it and/or  modify it under the terms of the GNU Affero General Public License, version 3, as published by the Free Software Foundation. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.

export default {
  "agree": "贊成",
  "disagree": "反對",
  "pass": "略過 / 不確定",
  "x_wrote": "表示：",
  "x_tweeted": "推文：",
  "group_123": "群組：",
  "majorityOpinion": "共同意見",
  "majorityOpinionShort": "共識",
  "info": "說明",
  "addPolisToYourSite": "<img style='height: 20px; margin: 0px 4px;' src='{{URL}}'/>",
  "privacy": "隱私",
  "TOS": "使用條款",
  "writePrompt": "分享您的觀點...",
  "anonPerson": "匿名人士",
  "helpWhatAmISeeingTitle": "這是什麼？",
  "helpWhatAmISeeing": "立場相近的人，會自動歸類到同一個群組。點擊群組，就可以看到這些人的共同意見。",
  "helpWhatDoIDoTitle": " 我可以做什麼？",
  "helpWhatDoIDo": "針對其他人的意見，按下「贊成」或「反對」。你也可以寫下您的觀點（每個意見單獨一則）。邀請朋友來一起討論！",
  "writeCommentHelpText": "如果您的觀點沒有人寫過，請務必將它<strong>寫下來</strong>！</i>",
  "heresHowGroupVoted": "這是群組 {{GROUP_NUMBER}} 的看法：",
  "one_person": "{{x}} 人",
  "x_people": "{{x}} 人",
  "acrossAllPtpts": "所有參與者：",
  "xPtptsSawThisComment": "位參與者看過這個意見。",
  "xOfThoseAgreed": "位參與者表示贊成。",
  "xOfthoseDisagreed": "位參與者表示反對。",
  "pctAgreed": "{{pct}}% 贊成",
  "pctDisagreed": "{{pct}}% 反對",
  "pctAgreedOfGroup": "群組 {{group}} 裡，有 {{pct}}% 的人贊成",
  "pctDisagreedOfGroup": "群組 {{group}} 裡，有 {{pct}}% 的人反對",
  "commentSent": "意見已送出！",
  "commentSendFailed": "送出意見時發生錯誤。",
  "commentSendFailedEmpty": "送出意見時發生錯誤：意見不可為空白。",
  "commentSendFailedTooLong": "送出意見時發生錯誤：意見過長。",
  "commentSendFailedDuplicate": "送出意見時發生錯誤：完全相同的意見已存在。",
  "connectFacebook": "連結 Facebook",
  "connectTwitter": "連結 Twitter",
  "connectToPostPrompt": "發表意見前，請先連結登入帳號。我們不會貼文在您的牆上。",
  "tip": "祕訣：",
  "tipCommentsRandom": "意見會隨機顯示。您不需要回覆別人的看法。",
  "tipOneIdea": "有多個意見請分開來寫，一次一個，好讓其他人表達贊成或反對。",
  "tipNoQuestions": "請直接陳述您的感受或觀點，不要使用問句。",
  "notSentSinceDemo": "（純屬測試，並未送出）",
  "submitComment": "送出",
  "tipStarred": "已經標記為重點。",
  "participantHelpWelcomeText": "歡迎來到一種嶄新的討論方式 - 對眾人的意見<span style='font-weight: 700;'>投票</span>，並且<span style='font-weight: 700;'>貢獻</span>您的觀點。",
  "participantHelpGroupsText": "立場相近的人，會<span style='font-weight: 700;'>自動歸類到同一個群組。</span>點擊群組，就可以看到這些人的共同意見<a style='font-weight: 700; cursor: pointer; text-decoration: underline' id='helpTextGroupsExpand'>...</a>",
  "helpWhatAreGroupsDetail": "<p>您可能在其他網站上看過「推薦產品」或「推薦電影」的服務。這些服務使用統計資訊，找出和您品味相近的人，然後用那些人的紀錄來向您推薦。</p> <p>當您在這裡按下「贊成」或「反對」時，您就會自動將您的頭像移動到相近的群組裡！上方顯示的每個群組，都是由立場相近的人組成的。這樣的公開討論，每次都能展現出令人意外的洞見。請點擊一個群組 - 看看他們共同的意見、發現某個群組的獨特之處！",
  "socialConnectPrompt": "連結帳號，就可以看到您的朋友、追蹤的人的立場如何。",
  "connectFbButton": "與 Facebook 連結",
  "connectTwButton": "與 Twitter 連結",

  "showTranslationButton": "啟用外部翻譯",
  "hideTranslationButton": "停用外部翻譯",
  "thirdPartyTranslationDisclaimer": "翻譯服務由第三方提供",
}
