
var ServerClient = function(params) {

    var iran_comments = [
        
        {userID: 1, id: 1001, text: "Would Iran really launch such a weapon? Wrap your mind around these words delivered by Iranian President Mahmoud Ahmadinejad on Israel\'s milestone, 60th birthday in 2008: \"Those who think they can revive the stinking corpse of the usurping and fake Israeli regime by throwing a birthday party are seriously mistaken. Today, the reason for the Zionist regime\'s existence is questioned, and this regime is on its way to annihilation. They should know that regional nations hate this fake and criminal regime and if the smallest and briefest chance is given to regional nations they will destroy it.\" Some weeks ago Ahmadinejad reaffirmed his intentions in a televised speech he gave in Teheran marking Quds Day, the annual protest against the Jewish presence in Jerusalem which is held on the last Friday of Ramadan.  He said, \"The nations of the region will soon finish off the usurper Zionists [Israel] in the Palestinian land. A new Middle East will definitely be formed. With the grace of God and help of the nations, in the new Middle East there will be no trace of the Americans and Zionists.\" Tell us who are those western expert that are not convinced this regime hasn\'t made the decision to build the bomb?",},

        {userID: 2, id: 1002, text: "Bill Keller says the mullahs are rational, which suggests we should trust them when they have nukes. But was it rational to sacrifice a generation of young boys during the Iran-Iraq war by having them repeatedly cross mine fields as human detectors forced to march ahead of Iran\'s military? is it rational to send agents half way across the globe to places like Buenos Aires to blow up Jews? Is it rational for an observer sitting in New York to believe, on the one hand, that the mullahs are truthful when they say their nuclear program is only for peaceful purposes, but that it is hard to believe, on the other hand, that they mean what they say when characterizing Israel as a cancer that must be eliminated? Wordsmith Bill Keller must have intended to use the word \"rationalize\" rather than \"rational\" to explain how desperate many are to accommodate a nuclear Iran. That\'s a lot easier to do sitting in New York rather than Jerusalem, Riyadh, Baku and other capitals in Tehran\'s neighborhood.",},

        {userID: 3, id: 1003, text: "Great piece. In the meantime, though, Israel is ratcheting up the hysteria. My fear is an October surprise that goes like this: Netanyahu (maybe inspired by Sheldon Adelson?) attacks Iran, insisting that the US come to Israel\'s aid. Obama is forced to do so against his better judgment under intense pressure from the uncritically pro-Israel crowd. Romney and the republicans jump all over Obama for not being aggressive enough, right-wing evangelicals are delirious, liberals and the war-weary in general are appalled that Obama has caved, and R & R end up winning the election.  Please, somebody, tell me this can\'t happen.",},

        {userID: 4, id: 1004, text: "Mr. Keller has presented a thoughtful, logical argument that a world living with a nuclear-armed Iran would be better than one after a pre-emptive U.S. and/or Israeli strike to take out Iran\'s nuclear capability. In fact, I think he has weakened, if not demolished, the alarmist cries from some Israelis and some Americans that a nuclear Iran is, ipso facto, unacceptable because it would lead inevitably to Israel\'s annihilation and an Iran on the rampage in support of radical Islam. The first assumption is far from the given that that some make it out to be, but the second would undoubtedly be the consequence of a pre-emptive strike--and Iran would occupy the moral high ground.  The other \"given\" is that a military attack, whatever its initial success, would not by any means put an end to Iran\'s nuclear ambitions. All the above is the reason that some of Mr. Keller\'s strongest allies in arguing against an Israeli strike are current and former leaders of Israel\'s security and intelligence establishment. They have become Prime Minister Netanyahu\'s strongest critics. Why America\'s media continue to ignore that Israeli consensus escapes me.",},

        {userID: 5, id: 1005, text: "Hmmm ... I wonder if Mr. Keller is related to John Boehner or Harry Reid? I ask because his \'solution\' appears to be simply to kick the can down the road. Any serious student of history understands that to be the most dangerous alternative as it abandons control of events to the winds of fate. Mr. Keller\'s analysis of the distastefulness of the available alternatives is spot-on but that does not suggest that treading water is a better choice. That course is likely to result in fewer alternatives and far more limited maneuvering room when can-kicking is no longer possible and all of the initiative rests with Iran.",},

        {userID: 6, id: 1006, text: "What is most disconcerting (and saddening) about most of these commentaries is the ease with which many people assume that Iran is a rational entity with rational leadership and that Israel, not anyone else, must take the existential leap of faith that the assumption of Iran\'s rationality is true. If such assumption is proven false, do those who made it say \"Oops. Our bad. Sorry about that.\"?  Or, to put it another way, how many people (or peoples)have faced an existential threat to their (its) existence, twice within recent memory, more often within history?",},

        {userID: 7, id: 1007, text: "Anyone who champions any type of preemptive strike and subsequent occupation of Iran must either themselves sign up for some branch of the military or offer their own children. It is easy to talk about the prospect of war on some distant battlefield but the actual horror of war should never be underestimated and putting \"boots on the ground\" should be the absolute LAST choice available. Its always funny to see that those with the least connection to actual fighting are always the first ones to suggest starting a war.",},
        
        {userID: 8, id: 1008, text: "At last, some common sense on this issue. I have never understood all of the fear-mongering about a nuclear Iran. There seems to be a general assumption that the lunacy among Iran\'s rulers, combined with nuclear weapons, would lead to disaster all around, particularly for Israel. But the Iranians have shown themselves to be calculating, rational, opponents. Any use of nuclear weapons on their part would lead to the destruction of Iran in retaliation. The idea that they would ignore these consequences and pursue mutual destruction anyway is a weak one. On the other hand, a preemptive strike at Iran would drag the US into a prolonged war, both overt and covert. We played the waiting game with the Soviet Union for many years, and it proved to be the right choice. I hope the leaders of the US and Israel make the right choice this time as well.",},
        
        {userID: 9, id: 1009, text: "I suspect that you are correct in your analysis. The fact is that Iran\'s logic for seeking nuclear capabilities is not that different from what drove Israel\'s ambitions. Iran views itself as surrounded by adversaries, several of whom have nuclear weapons, and so sees a vital need to have the same capability. Frankly, I do not see how we can prevent this. Delay it, yes, but prevention would involve destroying capabilities on the ground, which means war. No country has ever used nuclear weapons against a country capable of retaliating. We were certainly not thrilled to see such weapons in the hands of the Soviets, but we learned to live with the bomb. I would expect the same to be true for Iran. So while a despotic regime with nuclear capabilities is hardly ideal, we have successfully lived with this situation for decades. And attacking Iran will only delay the fall of the current regime which is really the overarching concern. Despotic regimes are ultimately unsustainable. In the modern era, they appear to last around 70-80 years at best (which leaves the mullahs another couple of decades). So it seems to me that our choices are: a) total war for regime change now (think how well Iraq worked out), b) limited war that turns the Iranian people against us and bolsters the mullahs, or c) containment until the day the Iranian people take destiny into their own hands. Seems pretty much a no-brainer.",},
        
        {userID: 10, id: 1010, text: "Politicians\' bluster that \"Iran will never have nuclear capability\" is obligatory tough-guy talk for domestic consumption -- a fake issue pumped to the max for political and K-Street advantage. More than 30 countries, including Japan, although they do not possess nuclear weapons possess \"nuclear capability\" -- the ability to produce a bomb in a weekend. This is just another example of bipartisan fear-mongering to: further the surveillance state, destabilize international relations to support imperial aims, withdraw support for necessary domestic programs and waste more money on the military. Sabre rattling at Iran also bolsters right-wing Israeli intransigence with respect to Palestinian/Israeli relations.",},
        
        {userID: 11, id: 1011, text: "Even asking this question risks howls of outrage. But you still do not ask the other question, even more vital: what should we offer in negotiations to avoid a bomb? We have offered nothing. We are not negotiating. We are demanding. We are threatening. We are attacking: economic with sanctions, cyber war with worms, and overt war with terrorist attacks. We are not actually doing the negotiation you presume.  We what could we, should we offer? What does Iran want, other than a bomb? We have never even discussed that. In fact, when talks were inevitable in this last round, the Israelis demanded assurances that nothing would be offered, and they were given those assurances. After each round our \"negotiator\" went first to Israel to report before coming home to report.  Because of Israeli objections, all offers that had been hinted were left unmade. Israel demands we fight a war for them. They won\'t have negotiations.  The choice is not just bomb or bombing. There is also negotiation, and we haven\'t tried it yet.",},
        
        {userID: 12, id: 1012, text: "Mr. Keller, I agree. What the United States should be seeking, and what President Obama has explicitly stated as his goal, is a nuclear-free world. This means that along with demanding that Iran not develop a nuclear weapons capability, we should be demanding that Israel and Pakistan destroy their nuclear weapons. But should Iran build a nuclear bomb, it would not be the end of the world. It is not worth my son\'s life, or the life of any mother\'s son or daughter, to prevent this from happening.",},
        
        {userID: 13, id: 1013, text: "Finally! A sane look at the problem! The Mullas may be mad, but they are not suicidal! Besides, after enabling Israel to go nuclear, the West has no legitimacy in its stand against Iran. I hope the powers that be pay close heed to these arguments and not involve us in yet another costly and useless war. The war mongers and the war profiteers of course will raise a hue and cry, but that\'s what they always do.",},
        
        {userID: 14, id: 1014, text: "Containing a nuclear Iran will be no more difficult and probably far less a real issue than containing a nuclear Pakistan which the west has been doing for a generation. The Pakistani government is as volatile and the population far more anti-US than Iran. I have family in Iran and have regular contact. The Iranian people are as afraid of nukes as any one else.  The Iranian government has no more desire to use nukes on its neighbors than the Israelis or the Pakistanis. They know that it is not the use of the weapons, but the possession of them that gives them the deterrent status and negotiation handle. Their involvement in the Syrian conflict, having 2 million Afghan refugees inside their own border, and their being the lead Shiite nation in the region makes then a natural target for all the Sunni Arab states which are far different than the Persians in culture, language and, more importantly, in military might. Iran\' government is also far more under the influence of Russia and China even though the vast majority of their young population is favorable towards the west and the US. But that would end in a blink if the US strikes at their nuclear facilities.",},

        {userID: 15, id: 1015, text: "Kudos to Bill Keller for his superb analysis of the ramifications if Iran acquires nuclear weapons. As he points out, given Israel’s enormous military superiority, an Iranian bomb would likely not be a threat to Israel’s national security. The slightest indication that Iran intended to use the bomb would trigger an instant and devastating Israeli pre-emptive attack. The downside of a military attack is overwhelming. A military assault would most certainly drag America into the conflict. Iranian — and regional — reaction would be catastrophic for American and Western interests. Iran would unquestionably launch a multifront military and terrorist reaction. American lives would most surely be endangered worldwide. Finally, most military strategists agree that even a prolonged air campaign would set the Iranian program back by only a few years. Mr. Keller deserves our gratitude for heroically standing up to the unrelenting beating of war drums by the Israeli leadership. BRUCE van VOORST  is former senior national security correspondent for Time magazine.",},
        
        {userID: 16, id: 1016, text: "Bill Keller’s analysis of containing a nuclear-armed Iran suffers from a glaring omission: He did not address the possibility that an Iranian nuke might fall into terrorists’ hands. The Iranian regime could deliberately arm a terrorist cell, or terrorists could exploit Iran’s inferior security infrastructure to steal a weapon, or an unstable future Iran could collapse, leaving its stockpile vulnerable. How, then, would the United States know where to direct its “flock of reciprocal nukes\" before the mushroom cloud swallowed Tel Aviv, or Manhattan? Even if the detonated bomb could be traced to Iran, the damage would be done. The potential destruction of another state will not deter a rogue group, let alone one of eager would-be martyrs. We also mustn’t forget that while America stakes its military strategy on such an optimistic gamble, Israel stakes its existence.",},
        
        {userID: 17, id: 1017, text: "Bill Keller makes a compelling case that it is better to tolerate a nuclear Iran than endure all the horrific consequences that a military strike would produce. He assures us that Iran is not likely to launch a nuclear attack against Israel, knowing that it would be suicidal, and that its threats to wipe Israel off the map are just words. Mr. Keller may be correct, but what if he is mistaken? How can Israeli leaders who are even 90 percent certain that deterrence will work allow their citizens to be subject to a second Holocaust, knowing that this time the Jewish people have the means to stop it? In a nuclear Iran, accidents, miscalculations, unauthorized launchings or the dying gasps of a beleaguered regime could each mean the end of Israel. Maybe Mr. Keller is right that the prudent course for Israel (and the United States) is to allow Iran to acquire nuclear arms. But if Israel or the United States does strike to prevent Iran from getting nuclear weapons, it will have ample justification to do so. STEVEN R. DAVID  is a professor of political science at Johns Hopkins University.",},
        
        {userID: 18, id: 1018, text: "Bill Keller thoughtfully tempers the worst fears about a nuclear-armed Iran. And he is certainly correct that Iran would be deterred from directly using nuclear weapons because of the threat of retaliation. But he plays down what would likely be the most destabilizing and dangerous impact of a nuclear Iran: Tehran’s use of its arsenal as a protective shield while it expanded power and influence across the region.  Mr. Keller says this “nuclear shield\" would mostly just embolden Iran’s support for subversive proxies like Hezbollah. But with territorial (and other) disputes against nearly all of its neighbors, Iran could also use a nuclear deterrent to try to alter the map of the Middle East. This is not simply an idle hypothetical: If Saddam Hussein had nuclear weapons in the summer of 1990, Kuwait would most likely now be part of Iraq. The United States and its allies cannot allow Iran such a waiver to engage in reckless aggression. Perhaps if that became clear, Iran would finally think twice about proceeding with its nuclear ambitions. STUART GOTTLIEB teaches international security at Columbia University.",},

        {userID: 19, id: 2019, text: "I am very surprised by Waltz's assumptions and conclusions in this article. If one were going to argue that Iran should be allowed to develop a nuclear weapon, one should use much better rationale to do so. My initial shock stems from the fact that Mr. Waltz actually seems to believe that Iran is a state just like any other. That they have rationallity and long-term stability in their present, as well as in their future. I would argue that this is not the case at all. There are significant power struggles happening within the country - between political factions, as well as between the Ayatollas and the politicians. In addition to that, the populace is not the contented entity that his article assumes. The reaction after the elections a couple years ago, along with the response of the regime underscore this. In addition, Iran has been very willing in the past - and possibly in the present - to make use of terrorist organizations to do their dirty work. Iran has worked through and with both Hamas and Hezbollah. Disavowal of these types of activities have been long in coming, did I miss them? Or are we still waiting? Ah yes, still waiting. The idea that a handoff of nukes to these organizations would be known in time, or not done because the weapons are expensive is fantasy. Iran doesn't play by those rules. Waltz's assertion that countries attaining nuclear capability tend to reduce imbalances in military power is specious, seeing as the other countries joining the nuclear club have NOT been Iran. Lumping this country with others from the past is a bit like saying that a strain of bird flu with mutations is bird flu like we have encountered elsewhere in the world. Iran is a country like other countries, yet Iran with nuclear weapons is an unknown entity that has in the past threatened various European powers, the United States, and Israel. Acting as though the country will not use these weapons if they are attained is whistling past the graveyard. As for the balance of power in the region, despite the fact that the weapons in Turkey are NATO nukes, there is a balancing aspect to their control of them. Turkey, although not aligned with Iran as Syria is, has an Islamist government which has a role in NATO as well as at the UN. The country has influence with the US and the world through these ties. And finally, Iran is a state protected by Russia - and to a lesser extent China - on the world stage. Both these countries have nuclear weapons that can be considered to balance Israel's arsenal. I fear Mr. Waltz is mistaken in his assumptions as well as his conclusion that Iran should not be disallowed from attaining nuclear weapons. He seems to have a very rosey view of the matter.",},

        {userID: 20, id: 2020, text: "I can’t agree with this argument because of two reasons. First, this idea regards the handoff to terrorists as improbable. But not a few of them are much eager to acquire the atomic bombs because it enables them to wound the \"Trunk\". The threat of nuclear proliferation originates in the simplicity of weaponizing. Anyone who gets the high enriched uranium can make the bombs. Imagine the people in China or Russia who resort to the suitcase bomb for protesting against the regime. Loose nuclear management triggers the world unacceptable vulnerability. Second, this notice admit the possession of nuclear weapons politically. But the hypotheses of NPT regime demand that no country can develop nuclear weapons because it is a necessary evil. The status is dramatically different, political measure from evil. This concession denies NPT regime, which is unprecedented. Finally, power begs to be balanced or to avoid massive disaster; that is the question. Accounting for the lack of Israel’s geographical depth, the current status is balancing. Even if rebalancing is required, we should seek another way. Japan decides not to develop nuclear weapons because it knows that isolationism is not the way to prosperity. Isolationism stiffens the foreign policy unpredictably, as Japan once experienced in 1930s. I’d like to say to Iranian people; Take handle while you can choose your course.",},

        {userID: 21, id: 2021, text: "What about the balance of having Islamic nations totaling 300 million Arabs, 85 million Turks, 75 million Persians, all of whom are opposed to Israel's 1.5 million Arabs and 5 million Jews? Israel has defended herself well, but she does not talk about wiping out any Islamic nation as they freely threaten to wipe out Israel. Israel is the target now because Islamic nations have the power of oil, but are still in flux. As they acquire physical power, their focus will change to America, which is the great Western power. It was America, not Israel, that overthrew Mohammad Mosaddegh, the democratically elected leader of Iran and replaced him with the despotic Shah, the leader the present Iranian regime overthrew. It would be as smart of us to allow Iran to acquire the bomb as it was of Europe and America to allow Hitler to rearm Germany. And this time round, not even England will be much help to America. (She was never much help to the Jews).",},

        {userID: 22, id: 2022, text: "Mr. Waltz is indeed a genius when it comes to \"appeasement and surrender\". While Adolf would have been proud of him, Churchill would have had Waltz hanged for high treason. Based on his principles enunciated in this article, the successful outcome of the Manhattan Project should have been revealed to the Axis Powers (those that were still standing) rather than used to put an end to WW2. Moral equivalence, especially where Israel is involved, is just another way to surrender to Islamists. Offering six million Jewish lives as payment for Muslim terrorists' blackmail seems to be Mr. Waltz's eminent recommendation to the free world. As it happens, we are not ready or willing to surrender to anyone – least of all to our mortal enemies. Different from cowardly appeasers, Americans will never forget 9/11. Never! Maybe this should be the title of the next article (on the subject) to be published by Foreign Affairs magazine. Or maybe not.",},

        {userID: 23, id: 2023, text: "Bottom line gentlemen. The world will never have peace, until the 2nd coming of Jesus Christ. If Iran decides to bomb Israel they will be fighting the Lord Himself. Not what I would want to do by any means. The Hand of the Lord holds, in its midst, tiny Israel. The world is heading quickly into the Tribulation Period and then the end.",},

        {userID: 24, id: 2024, text: "There is something of an appeasement, \"peace at any price\" core to Kenneth Waltz’s shocking assertion that we should just let Iran build nukes. Yes, the road to stopping Iran’s nuclear ambitions will not be easy and it will come at a price in human lives and financial resources. However, Waltz’s suggestion of a Nuclear Shiite Iran – one with a regime that believes in a better life after death – creating stability in the Middle East that is simply ridiculous on the surface and then considerably less funny when one truly digs into the issue. There’s no point in comparing Iran with the China/India/Pakistan situation because they are completely different. Yes, all have funded terrorist organizations to varying degrees -- largely for political and financial purposes rather than ideological ones -- and Pakistan still looms as a far greater danger than either China or India – and a Pakistani-Iranian alliance would indeed be a substantial danger. But at the moment the new “Persian Empire\" as the Iranian Mullahs frequently like to refer to themselves (although not in public forums) is determined to export its radical views of Islam not only throughout the region but throughout the world. To even attempt to compare a nuclear-armed Iran vs. Israel scenario as stabilizing is absurd. Israel built a bomb because it had seven million citizens facing some HUNDRED MILLION in hostile Islamic countries. Moreover, even setting Israel aside, how does Waltz explain what the Saudis and their Sunni allies will do? And we must make no mistake that the Shiite-Sunni rivalry is every bit as dangerous as Iran’s designs on Israel. Let’s make this simple: Can you trust a country that sends assassins to kill journalists in the Netherlands after they wrote cartoons about Islam? That’s how Waltz defines stability?",},

        {userID: 25, id: 2025, text: "I have to admire Mr.Waltz's courage to write this article which would be helpful to achive world peace. The world needs a good geopolitical balance for lasting peace. I have to also congratulate the editor for accepting the article for publication.",},
        
        {userID: 26, id: 2026, text: "Although Israel has been at the fore of nuclear deterrence in Iran, this article only captured half, or perhaps two thirds, of the power-struggle revolving around this issue in the Middle East. Saudi Arabia has also made clear that it does not want to see a nuclear armed Iran emerge, and that in such a case, it would seek nuclear weapons as well. The author of this article makes an interesting case, regarding the balancing affect of nuclear weapons, yet he neglects to note that despite acquiring nuclear weapons, India and Pakistan have not ceased hostilities (i.e. Mumbai massacre), or the demilitarization of Kashmir. North Korea, as well, has taken lethal action against the South, despite their MAD deterrence. While these instances are far from full fledged war, they are certainly worth consideration, though it is true, perhaps MAD did prevent the outbreak of further bloodshed. However, with a steady flow of blood already flowing in the Middle East, such an effect is more doubtable. Irans proxy wars, being waged in Afghanistan, Iraq, and Syria, as well, would, indeed, only be emboldened by a nuclear armed Iran. Such an accomplishment would serve as a certain propaganda/morale feat, while giving the Iranian Gov.'t a certain level of insurance that overt, exterior retaliation against it could be avoided for its proxy efforts in regional countries. With a Sunni-Shia conflict unfolding in Syria, Saudi Arabia, and other gulf states, should have been taken into consideration, in this article, along with Israel.",},
        
        {userID: 27, id: 2027, text: "I think, too, that is finally a great example of voice of reason, which was needed to everyone of us. Kenneth Waltz pointed out main concerns and gave an exhaustive handmaiden of why we should not attack Iran and try to hold it back from getting a nuclear bomb. After all, I think his voice unfortunately will mingle with the crowd...",},
        
        {userID: 28, id: 2028, text: "An interesting outline of a view very different from my own. I wonder if the author remembers Ahmadinejad's letter to Angela Merkel where he applauded Germany for their particular efforts with the Jewish people during the last of the great wars? Much 'rational' argument was passed back and forth  in the days before the war to assess or play down the danger of Hitler. Most notably was Prime Minister of the UK, Mr Chamberlain's peace negotiations with Hitler. The ruling Labour Party of my own little Scandinavian country didn't think there were any danger neither, and we therefore had practically no defences when Hitler struck. Where rationale is influenced to such a degree by beliefs, that self-destruction gives you advancement in Heaven's halls for eternity, pure logic looses its bite. I hope it's not too hard to remember across the Atlantic that hatred against Jews has found several seemingly irrational, but very tangible outlets, such as the Holocaust. In spite of a well formulated view-point, I find no trace of such understanding in the author. I would hate to live in a world where millions of Jews or people of any other race needed to pay with their lives for our academic experiments. On the other hand, I agree with the author that a hard line sometimes begets a hard response. But this works, and should work both ways. Like some of the other commenters have pointed out, the article does not explore the responses of Saudi Arabia and a whole host of other countries in the region. Nor does it explore potential global alliances between a new breed of nuclear superpowers, which would render their combined powers anything but regional. Hence, the article feels like work-in-progress rather than a completed argument. Many thanks.",},

        {userID: 30, id: 3030, text: "Netanyahu really is intent on helping his friend, Romney, win the White House. In so doing, he is intentionally interfering in domestic U.S. politics--a wholly inappropriate act for a foreign leader, especially one which deems itself an \"ally\". If Netanyahu (ethically compromised already as the record show) and Romney (a man with so little faith in America that he deposits large sums of money off shore) feel that their perception of Israel's security (which is all it is--a perception) trumps the larger issue of U.S. and global security, I'll trust the leader (Obama) who has neither of these marks against him and who has already amply demonstrated that he is willing and able to take the necessary steps when the time is right.",},
        
        {userID: 31, id: 3031, text: "What is most troubling about all this from an American's perspective is that our leaders feel so compelled to repeat that our bond with Israel is \"unbreakable.\" It's as though some invisible handshake of history has determined that the United States' and Israel's interests will forever remain one in the same. There is no argument as anti-realist as this. Israel's outlook under Netanyahu mirror the infantile \"clash of civilizations\" approach of the Bush administration, which were disastrous for U.S. interests and credibility. Our new, thoughtful president understands this, and he is attempting mold a foreign policy agenda in which nuance, cross-cultural dialogue and diplomacy are of first resort. It's the right way to go for out country's sake, and if Israel would like to play an allied role, it can be very useful. But if Israel would rather play out its pre-Cold War delusions, then our \"sacred bond\" can and should be broken.",},

        {userID: 32, id: 3032, text: "Although I have always been a supporter of Israel, I find Netanyahu repulsive, the Likud utterly uninterested in the two state solution, and, I might point out, in charge of a nation with hundreds of its own nuclear weapons. Yes, the Iran government is bad both for its own people and for the region. It is not, however, crazy. Any attempted attack by Iran on Israel would lead to a massive retaliation which would leave that nation in ruins. Sadly, there is no resolution to this conflict in the short term. Over the long haul, with patience and diplomacy, we can anticipate a collapse of the Iranian regime much in the same way that the corrupt and incompetent Soviet regime fell. There are no swift fixes.",},
        
        {userID: 33, id: 3033, text: "Netanyahu is war-monger who would like nothing better than to bomb Iran and draw the United States into another bloody war with an uncertain outcome. The President and Secretary Clinton are right in refusing to commit to a \"bright line\" that would inevitably precipitate a confrontation, and war.  Netanyahu's secondary agenda is to force the U.S. to commit to that bright line, so that the U.S. could not complain when Iran inevitably ignored the warning and Israel bombed Iran. Either way, we lose. Israel rightly fears Iranian nuclear capability, but we have no obligation to follow Israel's preferred plan -- bombing Iran -- for avoiding that outcome. The President's policies, which succeeded in Libya, require international cooperation, diplomacy and, where need be, strategic military intervention. Unilateral bombing is not among those choices and would not achieve the goal -- to stop Iran, without starting a bonfire in the Mid-East. Netanyahu's third agenda, moreover, is to help elect Romney, who like Bush will allow Israel to do whatever it wants to do. We had two Israeli bloody invasions -- of Lebanon and Gaza -- during the Bush administration, -- neither of which accomplished anything but bloodshed. For all these reasons, Obama should be re-elected and Netanyahu should be ignored.",},
        
        {userID: 34, id: 3034, text: "Regardless of the Romney-Netanyahu friendship or even the wisdom of an attack on Iran, an objective look at the situation reveals two facts which defenders of Secretary Clinton must refute: No evidence exists that the sanctions regime, as harmful to the Iranian economy as it may be, has deterred the Iranians from pushing forward with their enrichment program in which they continue to enrich uranium at levels beyond that unnecessary for medical research. Second, by continuing to both publicly announce that Israel will be unable to effectively damage the Iranian program; that Israel should not unilaterally attack; that sanctions are working and that no red lines exist in U.S. policy, the U.S. continues to signal Iran that the U.S. will not take military action. Assuming that Israel should rely on the President 's words opposing containment, Secretary Clinton's remarks nonetheless may be mis-read by the mullahs and.or the revolutionary guard (which may be making policy) as a reluctance by the U.S. to take any military action -- ever. The failure to take any action to support the Green revolution whatever in 2009 would confirm the Iranian perspective. The burden on those who agree with the President's statement that the U.S. will not countenance a nuclear-armed Iran is to explain how Secretary Clinton's comments advance that policy as opposed to convincing the Israelis and Iranians that the U.S. will be reluctant to take any military action.",},
        
        {userID: 35, id: 3035, text: "Voters should heed this story as yet another wake-up call on the eve of another important presidential election. Mitt Romney has ZERO foreign policy experience, while President Obama has been largely successful on foreign policy in his first term in office. The last thing the U.S. and the world at large needs is another full scale war in the Middle East. Netanyahoo apparently hasn't gotten the memo and fails to recognize that more violence and discontent will be more threatening to Israeli security than deterrence. ",},

        {userID: 36, id: 3036, text: "Why is the conservative Prime Minister of Israel intervening in a major American election by throwing red meat to the Republicans? This is just so very transparent. For a recipient nation to treat its one major ally in this manner is disgraceful, tacky, uncalled-for.  It makes me wonder if Netanjahu's Israel is truly a friend of America, and American democracy. ",},

        {userID: 37, id: 3037, text: "The trouble with most folks isn't so much their ignorance--it's that they know so much that ain't so. Israel is the homeland of the Jewish people--an ancient nation that is one of the few remaining from its time that is a nationality with a common national religion. As such, Israel is concerned with, and charged with, the protection of Jews around the world.  And Iran HAS been attacking Jews around the world for many years now. Bombing Jewish centers in South America and Europe in addition to funding and arming terrorists that have been attacking Israel directly are just the tip of the iceberg. Israel and Iran are at war and have been for some time. The actions of the Obama administration are consistent with a policy that is tolerant of a nuclear Iran--despite any protestations to the contrary. Refusing to create any red lines is indicative of this reality. If Obama truly means to use the military to prevent a nuclear Iran, it would have no trouble setting a deadline based on US intelligence assessments. Netanyahu understands that Obama has no intention of supporting a military attack against Iran. The problem is, Obama's telling Iran the same thing.  Israel has fought many proxy wars on behalf of the US over the last several decades at a tremendous human cost. So, a thank you to Israel is more appropriate than the ignorant vitriol displayed here. And all that US technology Israel gets? They improve it and share the improvements with the US. You're welcome for that, too.",},
        
        {userID: 38, id: 3038, text: "This would be a big enough war (if we are dragged in ) that I would hope this country votes first about it before entering it.",},
        
        {userID: 39, id: 3039, text: "I am wondering if perhaps Prime Minister Netanyahu watched a replay of the Democratic National Convention. If so, he saw, or at least heard, the handwriting on the wall. The numbers of those who opposed the changes in the wording of the party's platform startled me, and if the prime minister heard the nays perhaps he was startled, too. If he were not, well, he should have been. Those thundering nays constitute, to the best of my knowledge, the first public outcry against the corrosive influence of the Israel-first lobby in the political life of this country, and, mirabile dictu, that outcry was broadcast not only to the entire nation but to the entire world. Perhaps the prime minister has concluded that the days of Israeli suzerainty are drawing to a close and that he must act quickly or not at all. More than half a century has elapsed now since I began to write to my elected representatives in opposition to our support for Israel. Neither crystal ball nor special perception was required to see that uncritical support for Israel was not only immoral but dangerous, yet for five decades and more those of us who held such opinions were simply not heard. Times have changed, though, thanks in large measure to Walt and Mearsheimer, and once I recovered from the shock of hearing all those thundering nays from the Democratic delegates in Charlotte, I began to think for the very first time that, yes, we are, in fact, going to win this battle after all.",},
        
        {userID: 40, id: 3040, text: "Everyone seems to be forgetting that supporting the only true ally and true democracy in the region should be a strong goal of our administration. I was watching 9/11 footage today from the day it occurred with Palestinians dancing in the street passing out candy, while Israel tried to send over search and rescue groups and aid. Giving a radical country nuclear missiles causes a major problem for us in the region as well. We do send them tax money in the form of different programs and military aid but we also send money to Pakistan and various South American countries who do not like the US at all. If things get out of hand in the Middle East it would be good to have a staging ground for attacks such as Israel. We are not in a position to ostracize one of our only friends in the world.",},

        {userID: 41, id: 3041, text: "As pointed out in this piece, Netanyahu does not even have solid support in Israel for striking Iran. The U.S. is a steadfast ally of Israel, and would not hesitate to intervene should it's own intelligence - underpinned by the IAEA and Israel itself - point to Iran on a \"deliberate\" and \"unalterable\" path to developing a nuclear device. Iran knows this, and is not about to enter a suicide pact, especially with their interests threatened in Syria and sanctions forcing them to scramble to sell oil and keep their beleaguered middle-class from taking to the streets once again. The Obama administration has shown a steady hand in orchestrating a measured foreign policy in a manner that strengthens our status on the world scene - and has stated plainly that we will not tolerate a nuclear armed Iran. Bibi would be better served working in tandem with Secretary Clinton, and not trying to impose his hard line on a U.S. goverment that's a repeatedly proven benefactor and protector. Coming in the midst of a presidental campaign makes his remarks seem more political posturing than a genuine declaration of an immediate existential threat. The last thing we need is a reprise of the Bush/Cheney/Rumsfeld/Wolfowitz/Rice disastors. Let's stay calm, remain vigilent, and strive for reason and mutual trust when it comes to handling the admittedly complex situation in Iran.",},
  
        {userID: 42, id: 3042, text: "At what point did the United States hand off its foreign policy to Israel? At what point does Netanyahu decide when to send American men and women to fight, yet, another war? Is there another country in the world who so arrogantly asks another nation to do it's bidding? I for one, will not agree, or allow my conscience to be dictated by a blustery sable-rattling politician for whom I, as an American citizen do not have to answer to. This, my friends, is a true definition of Chutzpah. Mr. Netanyahu, go fight your own war, America is tired of demonstrating power and violence on your behalf.",},
  
        {userID: 43, id: 3043, text: "No, the sanctions haven't worked and there's no indication that they will work as long as there continues to be a strong international demand for Iran's crude. So, under the circumstances, I can't fault Israel for taking whatever actions it deems necessary. If Israel fails to act then I think that it's likely that Iran will obtain nuclear weapons. This will then prompt other countries in the region, including Saudi Arabia, to also want nuclear weapons - thus making the Middle East a more dangerous place.",},
  
        {userID: 44, id: 3044, text: "Your lack of sensitivity to the incredibly difficult dilemmas facing Israel as Iran gets closer to its nuclear goal is shocking. No one suggests that there are easy answers to the challenge. It would have been helpful for The Times at least to acknowledge Israeli concerns: That diplomacy shows no signs of working and is just the most recent Iranian stalling tactic. That Iran is so very close to embedding its nuclear facilities underground, creating a “zone of immunity\" from attack, that Israel has to worry how much time is left. That there is a degree of uncertainty in Israel about the United States’ willingness to take military action against Iran if sanctions do not do the trick. Israel is our ally, with existential dangers facing it if Iran should gain a weapon. Putting oneself in Israel’s place should be the first order of business in trying to understand and comment on the situation. Unfortunately, this perspective was completely absent from your editorial. ABRAHAM H. FOXMAN National Director Anti-Defamation League New York, Aug. 14, 2012",},
  
        {userID: 45, id: 3045, text: "I fervently hope that President Obama will have the courage to continue pressing for diplomatic efforts rather than bellicose rants to address the issue of Iran’s nuclear program. For Israel to insist on its right to destroy Iran’s nuclear research while it holds a purported nuclear arsenal is the height of arrogance, as is its assumption that the United States will be obliged to follow meekly along. We do not need to blunder into another war.",},
  
        {userID: 46, id: 3046, text: "Your editorial suggests that the Israeli prime minister needs to table the military option and give negotiations more time because there is “no proof that Iran is at the point of producing a weapon.\" Unfortunately, you fail to provide any evidence that negotiations have any hope of succeeding. Even while the sanctions have dramatically decreased Iran’s ability to export oil, the Iranian regime has done a masterful job of dragging out the negotiations while not showing any signs of slowing down the enrichment process or any willingness to compromise. Furthermore, Iran continues to call explicitly for Israel’s destruction. If you are going to denounce the Israeli government over its willingness to use the military option, you will soon have to come up with a more practical alternative than giving the negotiations more time.",},

         ];
         
    var commentIndex = 0;

    // function getNextStimulus() {}
    
    function isValidCommentID(commentID) {
        return isNumber(commentID);
    }

    function getNextComment() {
        var dfd = $.Deferred();
        if (commentIndex >= iran_comments.length) {
            dfd.reject();
        } else {
            dfd.resolve(iran_comments[commentIndex]);
            commentIndex += 1;
        }
        return dfd.promise();
    }

    function push(commentID) {
        var dfd = $.Deferred();
        if (isValidCommentID(commentID)) {
            dfd.reject();
        }
        console.log("ServerClient PUSH: " + commentID);
        setTimeout(dfd.resolve, 1000);
        return dfd.promise();
    }

    function pull(commentID) {
        var dfd = $.Deferred();
        if (isValidCommentID(commentID)) {
            dfd.reject();
        }
        console.log("ServerClient PULL: " + commentID);
        setTimeout(dfd.resolve, 1000);
        return dfd.promise();
    }

    function reportAsShown(commentID) {
        var dfd = $.Deferred();
        console.log("ServerClient SHOWN: " + commentID);
        setTimeout(dfd.resolve, 1000);
        return dfd.promise();
    }

    return {
        getNextComment: getNextComment,
        push: push,
        pull: pull,
        reportAsShown: reportAsShown,
    }
};
