env:
  doc: The application environment
  format:
  - production
  - development
  - test
  default: development
  env: NODE_ENV

aws_region:
  doc: aws_region
  default: us-east-1
  env: AWS_REGION

domainWhitelist: 
  doc: domainWhitelist
  default:
    - ^localhost$
    - ^192\\.168\\.1\\.141$
    - ^192\\.168\\.1\\.140$
    - ^pol\\.is
    - .+\\.pol\\.is$
    - ^xip\\.io$
    - .+\\.xip\\.io$
  env: DOMAIN_WHITELIST

uploader:
  doc: uploader for compiled static javascript
  format:
    - local
    - s3
    - scp
  default: local
  env: UPLOADER

service_url:
  doc: Point to a polisServer instance (local recommended for dev)
  default: http://localhost:5000
  env: SERVICE_URL

client_participation_port:
  doc: Note that this must match the participation client port specified in polisServer instance
  default: 5001
  env: CLIENT_PARTICIPATION_PORT

fb_app_id:
  doc: must register with facebook and get a facebook app id to use the facebook auth features
  default: 661042417336977
  env: FB_APP_ID

local_output_path:
  doc: Uploader settings local
  default: ./build
  env: LOCAL_OUTPUT_PATH

s3_bucket_prod:
  doc: uploader settings s3
  default: pol.is
  env: S3_BUCKET_PROD

s3_bucket_preprod:
  doc: uploader settings s3
  default: preprod.pol.is
  env: S3_BUCKET_PREPROD

scp_subdir_preprod:
  doc: uploader settings scp
  default: preprod
  env: SCP_SUBDIR_PREPROD

scp_subdir_prod:
  doc: uploader settings scp
  default: prod
  env: SCP_SUBDIR_PROD

port:
  doc: port
  default: 5000
  env: PORT

service_hostname:
  doc: service_hostname
  default: undefined
  env: SERVICE_HOSTNAME
disable_plans:
  doc: disable_plans
  default: true
  env: DISABLE_PLANS
disable_intercom:
  doc: disable_intercom
  default: true
  env: DISABLE_INTERCOM