const settings = {
  polisBlue: "rgb(81, 171, 244)",
  textColor: "#3e3e3e",
  linkColor: "#777777",
  darkColorBase: "#202020",
  lightColorBase: "#F1F1F1",
  clickCursor: "pointer",
  linkHoverColor: "#3e3e3e",
  highlightColor: "#006FC7",
  transitionAll: "all ease .3s",
  bgColorOffset: "#f8f8f8",
  bgColorBase: "#ffffff",
  borderColorBase: "#BEBEBE",
  borderRadiusBase: 4,
  borderStyleBase: "solid",
  borderWidthBase: 1,
  fontFamilyMonospace: "\"Courier New\", monospace",
  fontFamilySansSerif: "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
  fontSizeBase: 14,
  lineHeightBase: 1.428571429,
  lineHeightSmall: 1.3,

  lightestGray: "#FFFFFF",
  lighterGray: "#F6F6F6",
  lightGray: "#F1F1F1",
  mediumGray: "#E0E0E0",
  gray: "#979B9F",
  darkBlueGray: "#ACB1B8",
  blueGray: "#BFC5CC",
  darkGray: "#6C7277",
  darkerGray: "#34383C",
  darkestGray: "#1E2226",
};

export default settings;
