env:
  browser: true
  es2020: true
  jquery: true
plugins:
  - babel
  - react
extends:
  - standard
  - prettier-standard
  - eslint:recommended
  - plugin:react/recommended
  - prettier/react
rules: #{}
  camelcase: off
  eqeqeq: off
  no-const-assign: off
  no-throw-literal: off
  no-undef: off
  no-unused-vars: off
  react/display-name: off
  react/jsx-no-target-blank: off
  react/no-string-refs: off
  react/no-unescaped-entities: off
  react/prop-types: off
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
settings:
  react:
    version: detect
