name: "Registry Publish: All"

on:
  push:
    branches: [ dev ]

jobs:
  server:
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ github.job }}
    steps:
      - name: Check for file changes
        id: file-changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Flag if COMPONENT changed
        run: echo "::set-env name=IS_CHANGED::true"
        if: contains(steps.file-changes.outputs.files, '"${{ env.COMPONENT }}/')

      - name: Checkout
        uses: actions/checkout@v2
        if: env.IS_CHANGED == 'true'

      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
        if: env.IS_CHANGED == 'true'
 
      - env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose build --build-arg GIT_HASH=xxxxxxx ${{ env.COMPONENT }}
          docker tag polisdemo/${{ env.COMPONENT }}:dev localhost:5000/polisdemo/${{ env.COMPONENT }}:dev # REMOVE before PR merge
        if: env.IS_CHANGED == 'true'

      - name: Publish to Registry
        # See: https://github.com/elgohr/Publish-Docker-Github-Action/tags
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: polisdemo/${{ env.COMPONENT }}
          tags: dev
          registry: localhost:5000 # REMOVE before PR merge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # Acts as no-op so that build is skipped
          buildoptions: "--help"
        if: env.IS_CHANGED == 'true'

  math:
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ github.job }}
    steps:
      - name: Check for file changes
        id: file-changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Flag if COMPONENT changed
        run: echo "::set-env name=IS_CHANGED::true"
        if: contains(steps.file-changes.outputs.files, '"${{ env.COMPONENT }}/')

      - name: Checkout
        uses: actions/checkout@v2
        if: env.IS_CHANGED == 'true'

      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
        if: env.IS_CHANGED == 'true'
 
      - env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose build --build-arg GIT_HASH=xxxxxxx ${{ env.COMPONENT }}
          docker tag polisdemo/${{ env.COMPONENT }}:dev localhost:5000/polisdemo/${{ env.COMPONENT }}:dev # REMOVE before PR merge
        if: env.IS_CHANGED == 'true'

      - name: Publish to Registry
        # See: https://github.com/elgohr/Publish-Docker-Github-Action/tags
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: polisdemo/${{ env.COMPONENT }}
          tags: dev
          registry: localhost:5000 # REMOVE before PR merge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # Acts as no-op so that build is skipped
          buildoptions: "--help"
        if: env.IS_CHANGED == 'true'

  client-admin:
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ github.job }}
    steps:
      - name: Check for file changes
        id: file-changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Flag if COMPONENT changed
        run: echo "::set-env name=IS_CHANGED::true"
        if: contains(steps.file-changes.outputs.files, '"${{ env.COMPONENT }}/')

      - name: Checkout
        uses: actions/checkout@v2
        if: env.IS_CHANGED == 'true'

      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
        if: env.IS_CHANGED == 'true'
 
      - env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose build --build-arg GIT_HASH=xxxxxxx ${{ env.COMPONENT }}
          docker tag polisdemo/${{ env.COMPONENT }}:dev localhost:5000/polisdemo/${{ env.COMPONENT }}:dev # REMOVE before PR merge
        if: env.IS_CHANGED == 'true'

      - name: Publish to Registry
        # See: https://github.com/elgohr/Publish-Docker-Github-Action/tags
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: polisdemo/${{ env.COMPONENT }}
          tags: dev
          registry: localhost:5000 # REMOVE before PR merge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # Acts as no-op so that build is skipped
          buildoptions: "--help"
        if: env.IS_CHANGED == 'true'

  client-participation:
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ github.job }}
    steps:
      - name: Check for file changes
        id: file-changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Flag if COMPONENT changed
        run: echo "::set-env name=IS_CHANGED::true"
        if: contains(steps.file-changes.outputs.files, '"${{ env.COMPONENT }}/')

      - name: Checkout
        uses: actions/checkout@v2
        if: env.IS_CHANGED == 'true'

      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
        if: env.IS_CHANGED == 'true'
 
      - env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose build --build-arg GIT_HASH=xxxxxxx ${{ env.COMPONENT }}
          docker tag polisdemo/${{ env.COMPONENT }}:dev localhost:5000/polisdemo/${{ env.COMPONENT }}:dev # REMOVE before PR merge
        if: env.IS_CHANGED == 'true'

      - name: Publish to Registry
        # See: https://github.com/elgohr/Publish-Docker-Github-Action/tags
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: polisdemo/${{ env.COMPONENT }}
          tags: dev
          registry: localhost:5000 # REMOVE before PR merge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # Acts as no-op so that build is skipped
          buildoptions: "--help"
        if: env.IS_CHANGED == 'true'

  client-report:
    runs-on: ubuntu-latest
    env:
      COMPONENT: ${{ github.job }}
    steps:
      - name: Check for file changes
        id: file-changes
        uses: trilom/file-changes-action@v1.2.4

      - name: Flag if COMPONENT changed
        run: echo "::set-env name=IS_CHANGED::true"
        if: contains(steps.file-changes.outputs.files, '"${{ env.COMPONENT }}/')

      - name: Checkout
        uses: actions/checkout@v2
        if: env.IS_CHANGED == 'true'

      - name: Run local registry
        run: docker run -d -p 5000:5000 registry:2
        if: env.IS_CHANGED == 'true'
 
      - env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
        run: |
          docker-compose build --build-arg GIT_HASH=xxxxxxx ${{ env.COMPONENT }}
          docker tag polisdemo/${{ env.COMPONENT }}:dev localhost:5000/polisdemo/${{ env.COMPONENT }}:dev # REMOVE before PR merge
        if: env.IS_CHANGED == 'true'

      - name: Publish to Registry
        # See: https://github.com/elgohr/Publish-Docker-Github-Action/tags
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: polisdemo/${{ env.COMPONENT }}
          tags: dev
          registry: localhost:5000 # REMOVE before PR merge
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # Acts as no-op so that build is skipped
          buildoptions: "--help"
        if: env.IS_CHANGED == 'true'
