name: Deploy to Heroku Preprod

on:
  push:
    branches:
      - edge

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "polis-preprod"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "edge"
          
      - name: Deploy to Heroku
        run: |
          git push https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/polis-preprod.git edge:main
