name: Pull & Commit Translations from Mojito

on:
  schedule:
    # Run every hour.
    - cron: '0 * * * *'

jobs:
  pull-translations:
    if: github.repository_owner == 'patcon'
    runs-on: ubuntu-latest
    env:
      BRANCH: 320-continuous-localization
      CHECKOUT_DIR: code
      MOJITO_VERSION: "0.110"
      MOJITO_REPO: polis
      MOJITO_CLI_SERVER: polis-translations.herokuapp.com
      MOJITO_CLI_USERNAME: admin
      MOJITO_CLI_PASSWORD: ${{ secrets.MOJITO_CLI_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.0
        with:
          ref: ${{ env.BRANCH }}
          path: ${{ env.CHECKOUT_DIR }}

      - name: Cache Mojito CLI
        uses: actions/cache@v2.0.0
        with:
          path: moojito-cli.jar
          key: ${{ env.MOJITO_VERSION }}-cli

      - name: Download Mojito CLI
        run: |
          wget --continue --progress=dot:giga --output-document mojito-cli.jar https://github.com/box/mojito/releases/download/v${MOJITO_VERSION}/mojito-cli-${MOJITO_VERSION}.jar

      - name: Write Mojito CLI config
        run: |
          cat <<-EOF > application.properties
            l10n.resttemplate.host=${MOJITO_CLI_SERVER}
            l10n.resttemplate.port=443
            l10n.resttemplate.scheme=https
            l10n.resttemplate.authentication.credentialProvider=CONFIG
            l10n.resttemplate.authentication.username=${MOJITO_CLI_USERNAME}
            l10n.resttemplate.authentication.password=${MOJITO_CLI_PASSWORD}
          EOF

      - name: Pull translations from Mojito server
        run: |
          # Setting "inheritance-mode" to "REMOVE_UNTRANSLATED" ensures that
          # when a specific string has no translations written (e.g., no French
          # string for "hideTranslationButton") then the locale file will NOT
          # be populated with an English placeholder (e.g., no "Deactivate
          # translation" as "hideTranslationButton" in fr-FR.js). Instead, the
          # key will be absent from `fr-FR.js`. This works fine since our app's
          # translation setup falls back to English strings on its own.
          java -jar mojito-cli.jar pull --repository ${MOJITO_REPO} --source-directory ${CHECKOUT_DIR}/client-participation/js/strings/ --inheritance-mode REMOVE_UNTRANSLATED

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.8.0
        with:
          path: code
          title: Update translations
          branch: auto/translations
          labels: "♿ accessibility, 🔩 p:client-participation"
          body: |
            This is an automated pull request, created by the translation platform that we use.

            https://polis-translations.herokuapp.com/

            If you need to make changes to any of the localized strings in this pull request, please use the translation system.
            (If you make any changes within GitHub, they will get overridden next time the system runs, every hour.)
